#!/usr/bin/env bash
# estia — one-shot bootstrap. Reach for this right after cloning:
#
#   git clone git@github.com:dimitrios-git/estia.git ~/Development/estia
#   cd ~/Development/estia/bootstrap && ./setup.sh
#
# It (1) installs Ansible if missing, (2) asks a few questions — auto-detecting
# sensible defaults — and writes your answers to the untracked host_vars file,
# then (3) runs the playbook. Re-runnable: it pre-fills from your last answers.
# Extra args are passed straight through to ansible-playbook, e.g.:
#   ./setup.sh --tags dotfiles --check
#
# This is the configurable-installer front-end (docs/repo-structure-design.md §6).
# Interactive / external follow-ups stay manual — your SSH/GPG identity, the Samba
# password, the claude bot identity, pinentry + dark mode, the credential keyring:
# see ../docs/install-runbook.md.
set -euo pipefail

HERE=$(cd -- "$(dirname -- "$0")" && pwd)      # bootstrap/
HOSTVARS="$HERE/host_vars/localhost.yml"        # gitignored; this host's answers

# --- helpers ------------------------------------------------------------------
# cur KEY -> the current value of a flat `key: value` (or `key: "value"`) line
cur() { [ -f "$HOSTVARS" ] && sed -n "s/^$1: *\"\\?\\([^\"]*\\)\"\\?\$/\\1/p" "$HOSTVARS" | head -1; }

# ask VAR "Prompt" "default"  -> sets global $VAR (Enter accepts the default)
ask() {
    local __var=$1 prompt=$2 def=$3 ans
    read -r -p "$prompt [$def]: " ans
    printf -v "$__var" '%s' "${ans:-$def}"
}

# askyn VAR "Prompt" true|false  -> sets $VAR to the string true|false
askyn() {
    local __var=$1 prompt=$2 def=$3 hint ans
    [ "$def" = true ] && hint="Y/n" || hint="y/N"
    read -r -p "$prompt ($hint): " ans
    ans=${ans:-$def}
    case "$ans" in [yY]*|true) printf -v "$__var" true ;; *) printf -v "$__var" false ;; esac
}

# --- 1. Ansible ---------------------------------------------------------------
if ! command -v ansible-playbook >/dev/null 2>&1; then
    echo "==> Installing Ansible (needs sudo)…"
    sudo apt-get update && sudo apt-get install -y ansible
fi

# --- 2. Gather answers (existing value -> detected -> hardcoded fallback) ------
echo "==> Configure this host (press Enter to accept each [default]):"

# LAN subnet: the link-scope route IS the LAN network in CIDR (e.g. 192.168.0.0/24)
det_lan=$(ip -o -4 route show scope link 2>/dev/null \
            | awk '$1 ~ /\// && $1 !~ /^169\.254/ {print $1; exit}')
def_lan=$(cur samba_lan_subnet);     def_lan=${def_lan:-${det_lan:-192.168.1.0/24}}
def_music=$(cur cmus_music_dir);     def_music=${def_music:-$HOME/Music}
def_samba=$(cur enable_samba);       def_samba=${def_samba:-true}
def_claude=$(cur enable_claude_user); def_claude=${def_claude:-true}
def_creds=$(cur enable_credentials);  def_creds=${def_creds:-true}

askyn enable_samba       "Set up the Samba-over-Tailscale share?"   "$def_samba"
if [ "$enable_samba" = true ]; then
    ask samba_lan_subnet "  Home LAN subnet allowed to reach it"    "$def_lan"
else
    samba_lan_subnet=$def_lan
fi
askyn enable_claude_user "Create the dedicated 'claude' agent user?" "$def_claude"
askyn enable_credentials "Enable login auto-unlock of SSH + GPG?"    "$def_creds"
ask   cmus_music_dir     "Music library directory (cmus)"           "$def_music"

# --- 3. Write the answers file (gitignored) -----------------------------------
mkdir -p "$HERE/host_vars"
cat > "$HOSTVARS" <<EOF
---
# Generated by setup.sh — this host's answers. Gitignored; re-run setup.sh to update.
enable_samba: $enable_samba
enable_claude_user: $enable_claude_user
enable_credentials: $enable_credentials
samba_lan_subnet: "$samba_lan_subnet"
cmus_music_dir: "$cmus_music_dir"
EOF
echo "==> Wrote $HOSTVARS"

# --- 4. Run the playbook ------------------------------------------------------
echo "==> Running the bootstrap (sudo for package installs / system roles)…"
ansible-playbook "$HERE/site.yml" --ask-become-pass "$@"

cat <<'EOF'

==> Done. Remaining manual / external steps (see ../docs/install-runbook.md):
    pinentry + dark mode; your SSH/GPG identity; the Samba password (smbpasswd);
    the claude bot identity; and storing the credential-keyring passphrases.
EOF
