#!/usr/bin/env bash
# estia — one-shot bootstrap. Reach for this right after cloning:
#
#   git clone git@github.com:dimitrios-git/estia.git ~/Development/estia
#   cd ~/Development/estia/bootstrap && ./setup.sh
#
# It (1) installs Ansible if missing, (2) asks a few questions — auto-detecting
# sensible defaults — and writes your answers to the untracked host_vars file,
# then (3) runs the playbook. Re-runnable: it pre-fills from your last answers.
# Extra args are passed straight through to ansible-playbook. Passing `--check`
# makes it a true DRY-RUN — your answers go to a temp file (the real host_vars is
# untouched) and ansible only previews, so nothing on the system or in the repo
# changes. e.g.:
#   ./setup.sh --check --diff                  # preview everything, change nothing
#   ./setup.sh --tags dotfiles --check --diff  # preview just the dotfiles re-link
#
# This is the configurable-installer front-end (docs/repo-structure-design.md §6).
# Interactive / external follow-ups stay manual — your SSH/GPG identity, the Samba
# password, the claude bot identity, pinentry + dark mode, the credential keyring:
# see ../docs/install-runbook.md.
set -euo pipefail

HERE=$(cd -- "$(dirname -- "$0")" && pwd)      # bootstrap/
HOSTVARS="$HERE/host_vars/localhost.yml"        # gitignored; this host's answers

# `--check` anywhere in the args makes this a true DRY-RUN: answers go to a temp
# file (the real host_vars is untouched) and ansible runs in --check, so nothing
# on the system OR in the repo changes. e.g.: ./setup.sh --check --diff
dry_run=false
for _a in "$@"; do [ "$_a" = --check ] && dry_run=true; done

# --- helpers ------------------------------------------------------------------
# cur KEY -> the current value of a flat `key: value` (or `key: "value"`) line.
# Always returns 0 (empty if the file/key is absent) so `set -e` doesn't abort the
# first run on a fresh machine where host_vars doesn't exist yet.
cur() {
    [ -f "$HOSTVARS" ] || return 0
    sed -n "s/^$1: *\"\\?\\([^\"]*\\)\"\\?\$/\\1/p" "$HOSTVARS" | head -1
}

# ask VAR "Prompt" "default"  -> sets global $VAR (Enter accepts the default)
ask() {
    local __var=$1 prompt=$2 def=$3 ans
    read -r -p "$prompt [$def]: " ans
    printf -v "$__var" '%s' "${ans:-$def}"
}

# askyn VAR "Prompt" true|false  -> sets $VAR to the string true|false
askyn() {
    local __var=$1 prompt=$2 def=$3 hint ans
    [ "$def" = true ] && hint="Y/n" || hint="y/N"
    read -r -p "$prompt ($hint): " ans
    ans=${ans:-$def}
    case "$ans" in [yY]*|true) printf -v "$__var" true ;; *) printf -v "$__var" false ;; esac
}

# write_answers FILE -> write the gathered answers as YAML to FILE
write_answers() {
    cat > "$1" <<EOF
---
# Generated by setup.sh — this host's answers. Gitignored; re-run setup.sh to update.
enable_samba: $enable_samba
enable_claude_user: $enable_claude_user
enable_credentials: $enable_credentials
samba_lan_subnet: "$samba_lan_subnet"
cmus_music_dir: "$cmus_music_dir"
git_user_name: "$git_user_name"
git_user_email: "$git_user_email"
git_signingkey: "$git_signingkey"
gpg_keygrip: "$gpg_keygrip"
ssh_key_file: "$ssh_key_file"
EOF
}

# --- 1. Ansible ---------------------------------------------------------------
if ! command -v ansible-playbook >/dev/null 2>&1; then
    echo "==> Installing Ansible (needs sudo)…"
    sudo apt-get update && sudo apt-get install -y ansible
fi

# --- 2. Gather answers (existing value -> detected -> hardcoded fallback) ------
echo "==> Configure this host (press Enter to accept each [default]):"

# LAN subnet: the link-scope route on the DEFAULT-route interface — so we pick the
# real NIC, not docker0/bridges/veth/tailscale (whose routes often sort first).
# Fall back to the first non-virtual link route, then a generic default.
det_if=$(ip -o -4 route show default 2>/dev/null | awk '{print $5; exit}')
det_lan=$(ip -o -4 route show scope link 2>/dev/null \
            | awk -v ifc="$det_if" '$1 ~ /\// && index($0, " dev " ifc " ") {print $1; exit}')
[ -n "$det_lan" ] || det_lan=$(ip -o -4 route show scope link 2>/dev/null \
            | awk '$1 ~ /\// && $0 !~ /docker|veth|br-|virbr|tailscale|169\.254/ {print $1; exit}')
def_lan=$(cur samba_lan_subnet);     def_lan=${def_lan:-${det_lan:-192.168.1.0/24}}
def_music=$(cur cmus_music_dir);     def_music=${def_music:-$HOME/Music}
def_samba=$(cur enable_samba);       def_samba=${def_samba:-true}
def_claude=$(cur enable_claude_user); def_claude=${def_claude:-true}
def_creds=$(cur enable_credentials);  def_creds=${def_creds:-true}

# Identity defaults: existing host_vars -> existing git config -> gpg/ssh detect.
def_gname=$(cur git_user_name);   [ -n "$def_gname" ]  || def_gname=$(git config --global user.name 2>/dev/null || true)
[ -n "$def_gname" ]  || def_gname=$(getent passwd "$USER" 2>/dev/null | cut -d: -f5 | cut -d, -f1 || true)
def_gmail=$(cur git_user_email);  [ -n "$def_gmail" ]  || def_gmail=$(git config --global user.email 2>/dev/null || true)
def_skey=$(cur git_signingkey);   [ -n "$def_skey" ]   || def_skey=$(git config --global user.signingkey 2>/dev/null || true)
[ -n "$def_skey" ] || def_skey=$(gpg --list-secret-keys --keyid-format=long 2>/dev/null | awk -F/ '/^sec/{split($2,a," ");print a[1];exit}' || true)
def_grip=$(cur gpg_keygrip)
[ -n "$def_grip" ] || [ -z "$def_skey" ] || def_grip=$(gpg --list-secret-keys --with-keygrip "$def_skey" 2>/dev/null | awk '/Keygrip/{print $3;exit}' || true)
def_sshkey=$(cur ssh_key_file)
if [ -z "$def_sshkey" ]; then
    for _k in "$HOME"/.ssh/id_*; do
        case "$_k" in *.pub) continue ;; esac
        [ -f "$_k" ] && { def_sshkey=$(basename "$_k"); break; }
    done
fi
[ -n "$def_sshkey" ] || def_sshkey=id_ed25519

askyn enable_samba       "Set up the Samba-over-Tailscale share?"   "$def_samba"
if [ "$enable_samba" = true ]; then
    ask samba_lan_subnet "  Home LAN subnet allowed to reach it"    "$def_lan"
else
    samba_lan_subnet=$def_lan
fi
askyn enable_claude_user "Create the dedicated 'claude' agent user?" "$def_claude"
askyn enable_credentials "Enable login auto-unlock of SSH + GPG?"    "$def_creds"
ask   cmus_music_dir     "Music library directory (cmus)"           "$def_music"

echo
echo "  Identity (commit author, signing, and the login key-unlock hook):"
ask git_user_name  "  Git user name" "${def_gname:-Your Name}"
ask git_user_email "  Git email"     "${def_gmail:-you@example.com}"
ask git_signingkey "  GPG signing key id (blank = no commit signing)" "$def_skey"
if [ -n "$git_signingkey" ]; then
    ask gpg_keygrip "  GPG keygrip of that key (gpg --with-keygrip)" "$def_grip"
else
    gpg_keygrip=""
fi
ask ssh_key_file   "  SSH private key in ~/.ssh the login hook loads" "$def_sshkey"

# --- 3. Confirm before writing/applying (catch a bad auto-detect here) ---------
$dry_run && _verb="preview (DRY-RUN — nothing written or changed)" || _verb="write + apply"
cat <<EOF

  Answers to $_verb:
    enable_samba       = $enable_samba$( [ "$enable_samba" = true ] && echo "   (LAN: $samba_lan_subnet)" )
    enable_claude_user = $enable_claude_user
    enable_credentials = $enable_credentials
    cmus_music_dir     = $cmus_music_dir
    git identity       = $git_user_name <$git_user_email>$( [ -n "$git_signingkey" ] && echo "   signing $git_signingkey" )
    ssh login key      = ~/.ssh/$ssh_key_file
EOF
askyn _proceed "Proceed?" true
[ "$_proceed" = true ] || { echo "Aborted — nothing written or changed."; exit 0; }

# --- 4. Write answers + run ----------------------------------------------------
if $dry_run; then
    # DRY-RUN: don't touch the real host_vars; preview the answers via -e (highest
    # precedence, so it overrides the on-disk host_vars for this check only).
    _tmp=$(mktemp); write_answers "$_tmp"
    echo "==> DRY-RUN (--check): not writing $HOSTVARS; previewing your answers via -e."
    ansible-playbook "$HERE/site.yml" --ask-become-pass -e "@$_tmp" "$@"
    rm -f "$_tmp"
    echo "==> Dry-run complete — nothing was changed. Re-run without --check to apply."
    exit 0
fi

mkdir -p "$HERE/host_vars"
write_answers "$HOSTVARS"
echo "==> Wrote $HOSTVARS"
echo "==> Running the bootstrap (sudo for package installs / system roles)…"
ansible-playbook "$HERE/site.yml" --ask-become-pass "$@"

cat <<'EOF'

==> Done. Remaining manual / external steps (see ../docs/install-runbook.md):
    pinentry + dark mode; your SSH/GPG identity; the Samba password (smbpasswd);
    the claude bot identity; and storing the credential-keyring passphrases.
EOF
