# GENERATED by themes/hestia/render.py from palette.yml v0.10.1 + scopes.yml — do not edit; edit the sources and re-render
# ranger colorscheme — hestia dark (hestia-dark/-light pair; the
# bootstrap symlinks the `theme_variant` one to colorschemes/hestia.py).
# Structure follows ranger's stock default.py; colours are xterm-256 indices
# resolved from palette.yml — the file classes from the SAME filetype_colors()
# table as vifm + dircolors, so all of them agree by construction.

from __future__ import absolute_import, division, print_function

from ranger.gui.color import bold, default, default_colors, normal, reverse
from ranger.gui.colorscheme import ColorScheme

ACCENT = 99
ACCENT_DARK = 55
DIM = 245
MUTED = 145
BORDER = 240
DIR = 39
EXEC = 71
LINK = 44
BROKEN = 203
FIFO = 37
DEVICE = 172
SOCKET = 211
IMAGES = 211
VIDEO = 199
AUDIO = 44
DOCS = 214
ARCHIVES = 203
MARKED = 214
GREEN = 29
CYAN = 37
MAGENTA = 211
BRIGHT_RED = 203
YELLOW = 172
BAR = 247


class Hestia(ColorScheme):
    progress_bar_color = ACCENT

    def use(self, context):  # noqa: C901  pylint: disable=too-many-branches,too-many-statements
        fg, bg, attr = default_colors

        if context.reset:
            return default_colors

        elif context.in_browser:
            attr = reverse if context.selected else normal
            if context.empty or context.error:
                fg, bg = 231, ACCENT_DARK
            if context.border:
                fg = BORDER
            if context.media:
                fg = IMAGES if context.image else (AUDIO if context.audio else VIDEO)
            if context.document:
                fg = DOCS
            if context.container:
                fg = ARCHIVES
            if context.directory:
                attr |= bold
                fg = DIR
            elif context.executable and not any(
                    (context.media, context.container, context.fifo, context.socket)):
                attr |= bold
                fg = EXEC
            if context.socket:
                attr |= bold
                fg = SOCKET
            if context.fifo:
                fg = FIFO
            if context.device:
                attr |= bold
                fg = DEVICE
            if context.link:
                fg = LINK if context.good else BROKEN
            if context.tag_marker and not context.selected:
                attr |= bold
                fg = ACCENT
            if not context.selected and (context.cut or context.copied):
                attr |= bold
                fg = DIM
            if context.main_column:
                if context.selected:
                    attr |= bold
                if context.marked:
                    attr |= bold
                    fg = MARKED
            if context.badinfo:
                if attr & reverse:
                    bg = MAGENTA
                else:
                    fg = MAGENTA
            if context.selected:
                # the uniform hestia cursor bar (vifm CurrLine / yazi indicator)
                # instead of reverse-video over the item's own colour
                fg = BAR
            if context.inactive_pane:
                fg = MUTED

        elif context.in_titlebar:
            if context.hostname:
                fg = BRIGHT_RED if context.bad else ACCENT
            elif context.directory:
                fg = DIR
            elif context.tab:
                if context.good:
                    fg, bg = 231, ACCENT
            elif context.link:
                fg = LINK
            attr |= bold

        elif context.in_statusbar:
            if context.permissions:
                fg = CYAN if context.good else BRIGHT_RED
            if context.marked:
                attr |= bold | reverse
                fg = MARKED
            if context.frozen:
                attr |= bold | reverse
                fg = CYAN
            if context.message:
                if context.bad:
                    attr |= bold
                    fg = BRIGHT_RED
            if context.loaded:
                bg = self.progress_bar_color
            if context.vcsinfo:
                fg = DIR
                attr &= ~bold
            if context.vcscommit:
                fg = YELLOW
                attr &= ~bold
            if context.vcsdate:
                fg = CYAN
                attr &= ~bold

        if context.text and context.highlight:
            attr |= reverse

        if context.in_taskview:
            if context.title:
                fg = DIR
            if context.selected:
                attr |= reverse
            if context.loaded:
                if context.selected:
                    fg = self.progress_bar_color
                else:
                    bg = self.progress_bar_color

        if context.vcsfile and not context.selected:
            attr &= ~bold
            if context.vcsconflict:
                fg = MAGENTA
            elif context.vcsuntracked:
                fg = ACCENT
            elif context.vcschanged:
                fg = ACCENT
            elif context.vcsunknown:
                fg = BRIGHT_RED
            elif context.vcsstaged:
                fg = GREEN
            elif context.vcssync:
                fg = GREEN
            elif context.vcsignored:
                fg = default
        elif context.vcsremote and not context.selected:
            attr &= ~bold
            if context.vcssync or context.vcsnone:
                fg = GREEN
            elif context.vcsbehind:
                fg = BRIGHT_RED
            elif context.vcsahead:
                fg = DIR
            elif context.vcsdiverged:
                fg = MAGENTA
            elif context.vcsunknown:
                fg = BRIGHT_RED

        return fg, bg, attr
