#!/usr/bin/env python3
"""render.py — generate the theme artifacts from the palette.

Layer 3 of the theme pipeline (docs/theme-roadmap.md): reads palette.yml
(colours, per variant) + scopes.yml (the shared role→scope map) and renders

TextMate family (syntax + chrome):
  user/bat/themes/wildcharm.tmTheme                      (dark; terminal chrome)
  themes/wildcharm/dist/shiki/hestia-{dark,light}.json   (web code blocks;
                                                          bg = the code SURFACE)
  user/vscode/hestia/themes/hestia-{dark,light}-color-theme.json
                                                         (editor; bg = the app
                                                          CANVAS + UI chrome)

Desktop chrome fragments (roles/ANSI only — no scopes; both variants, the
bootstrap symlinks the one `theme_variant` selects, M7):
  user/kitty/theme-{dark,light}.conf                     (terminal colours)
  user/sway/theme-{dark,light}.conf                      ($vars + output bg +
                                                          the gsettings execs)
  user/waybar/theme-{dark,light}.css                     (@define-color tokens)

Same tokenColors everywhere; only the per-target chrome differs. The WCAG AA
contrast gate runs before anything is written — a palette edit that breaks a
plain-text role fails the render (reverse/fill roles are exempt; they are
checked as pairings by eye).

Usage:  render.py            render all artifacts in place
        render.py --check    exit 1 if any committed artifact differs from a
                             fresh render (use before/in review)

Never edit the generated files by hand — scope decisions go in scopes.yml,
colours in palette.yml, chrome maps below.
"""

import json
import sys
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent

PALETTE = yaml.safe_load((HERE / "palette.yml").read_text())
SCOPES = yaml.safe_load((HERE / "scopes.yml").read_text())["rules"]
VERSION = PALETTE["version"]
PROVENANCE = (
    f"GENERATED by themes/wildcharm/render.py from palette.yml v{VERSION} "
    f"+ scopes.yml — do not edit; edit the sources and re-render"
)

ROLES = PALETTE["roles"]
ANSI = PALETTE["ansi"]
LIGHT = PALETTE["light"]

# role → colour, per variant. `link` on light is the accent (it clears AA as
# text on white — decision log); error is the paired fill role.
VARIANTS = {
    "dark": {
        **PALETTE["syntax"],
        "text": ROLES["text"],
        "link": ROLES["link"],
        "error_fg": "#ffffff",
        "error_bg": ROLES["accent_dark"],
        # surfaces the plain-text roles must clear AA against. Since 0.5.0 the
        # web code surface IS the ground (it reads raised on tci's darker
        # page); surface_alt is transient (hover/line-highlight), not a body-
        # text surface, so it is deliberately NOT gated here.
        "_aa_surfaces": [ROLES["bg"]],
        # per-target canvas/surface
        "_canvas": ROLES["bg"],          # vim/bat/VS Code app canvas
        "_code_surface": ROLES["bg"],    # web code blocks == the ground
    },
    "light": {
        **LIGHT["syntax"],
        "text": LIGHT["roles"]["text"],
        "link": LIGHT["roles"]["accent"],
        "error_fg": "#ffffff",
        "error_bg": LIGHT["syntax"]["error"],
        # the light gate runs against the #f5f5f5 DESKTOP ground (M7) — stricter
        # than the #ffffff code surface, so white is covered by implication
        "_aa_surfaces": [LIGHT["roles"]["bg"]],
        "_canvas": LIGHT["roles"]["bg"],
        # the web code surface keeps the M3 pure white (light-only split;
        # dark's code surface == the ground)
        "_code_surface": LIGHT["roles"]["code_surface"],
    },
}

# per-variant role/ANSI tables for the desktop-chrome emitters
def vroles(variant: str) -> dict:
    return ROLES if variant == "dark" else LIGHT["roles"]


def vansi(variant: str) -> dict:
    return ANSI if variant == "dark" else LIGHT["ansi"]

FILL_ROLES = {"error", "todo"}  # reverse/fill — exempt from the plain-text gate


def _lum(hexval: str) -> float:
    h = hexval.lstrip("#")
    c = [int(h[i : i + 2], 16) / 255 for i in (0, 2, 4)]
    c = [x / 12.92 if x <= 0.04045 else ((x + 0.055) / 1.055) ** 2.4 for x in c]
    return 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2]


def contrast(a: str, b: str) -> float:
    la, lb = sorted((_lum(a), _lum(b)), reverse=True)
    return (la + 0.05) / (lb + 0.05)


def aa_gate() -> None:
    failures = []
    for variant, colors in VARIANTS.items():
        for role, hexval in colors.items():
            if role.startswith("_") or role in FILL_ROLES or role.startswith("error"):
                continue
            for surface in colors["_aa_surfaces"]:
                r = contrast(hexval, surface)
                if r < 4.5:
                    failures.append(f"{variant}.{role} {hexval} on {surface}: {r:.2f}:1")
    if failures:
        sys.exit("AA contrast gate FAILED:\n  " + "\n  ".join(failures))


def token_colors(colors: dict) -> list:
    out = []
    for rule in SCOPES:
        settings = {}
        role = rule.get("role")
        if rule.get("paired"):
            settings["foreground"] = colors["error_fg"]
            settings["background"] = colors["error_bg"]
        elif role:
            settings["foreground"] = colors[role]
        if rule.get("font_style"):
            settings["fontStyle"] = rule["font_style"]
        out.append({"name": rule["name"], "scope": rule["scopes"], "settings": settings})
    return out


# ---------------------------------------------------------------- tmTheme (bat)

def render_tmtheme() -> str:
    c = VARIANTS["dark"]
    chrome = {
        "background": c["_canvas"],
        "foreground": c["text"],
        "caret": ROLES["accent"],
        "lineHighlight": ROLES["surface_alt"],
        "selection": ROLES["border"],
        "invisibles": ROLES["dim"],
        "guide": ROLES["border"],
        "activeGuide": ROLES["dim"],
        "gutterForeground": ROLES["dim"],
    }
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
        f"<!-- {PROVENANCE} -->",
        '<plist version="1.0">',
        "<dict>",
        "  <key>name</key>",
        "  <string>wildcharm</string>",
        "  <key>settings</key>",
        "  <array>",
        "",
        "    <dict>",
        "      <key>settings</key>",
        "      <dict>",
    ]
    for k, v in chrome.items():
        lines.append(f"        <key>{k}</key> <string>{v}</string>")
    lines += ["      </dict>", "    </dict>"]
    for tc in token_colors(VARIANTS["dark"]):
        lines += [
            "",
            "    <dict>",
            f"      <key>name</key><string>{tc['name']}</string>",
            f"      <key>scope</key><string>{', '.join(tc['scope'])}</string>",
            "      <key>settings</key>",
            "      <dict>",
        ]
        for k, v in tc["settings"].items():
            lines.append(f"        <key>{k}</key><string>{v}</string>")
        lines += ["      </dict>", "    </dict>"]
    lines += ["", "  </array>", "</dict>", "</plist>", ""]
    return "\n".join(lines)


# ------------------------------------------------------------------ theme JSON

def theme_json(variant: str, target: str) -> str:
    c = VARIANTS[variant]
    if target == "shiki":
        colors = {
            "editor.background": c["_code_surface"],
            "editor.foreground": c["text"],
        }
    elif variant == "dark":  # vscode dark — full chrome from roles + ANSI
        acc, accfg = ROLES["accent"], ROLES["accent_fg"]
        colors = {
            "focusBorder": acc,
            "foreground": c["text"],
            # links in UI text (chat/welcome/notifications) + ctrl-hover links
            # in the editor — default to VS Code blue unless mapped
            "textLink.foreground": c["link"],
            "textLink.activeForeground": c["link"],
            "editorLink.activeForeground": c["link"],
            "editor.background": c["_canvas"],
            "editor.foreground": c["text"],
            "editor.lineHighlightBackground": ROLES["surface_alt"],
            "editor.selectionBackground": ROLES["border"],
            "editorCursor.foreground": acc,
            "editorLineNumber.foreground": ROLES["dim"],
            "editorLineNumber.activeForeground": c["text"],
            "editorIndentGuide.background1": ROLES["border"],
            "editorIndentGuide.activeBackground1": ROLES["dim"],
            "editorWhitespace.foreground": ROLES["border"],
            "sideBar.background": ROLES["surface"],
            "sideBar.foreground": ROLES["muted"],
            "sideBar.border": ROLES["border"],
            "sideBarTitle.foreground": c["text"],
            "activityBar.background": c["_canvas"],
            "activityBar.foreground": c["text"],
            "activityBar.inactiveForeground": ROLES["dim"],
            "activityBarBadge.background": acc,
            "activityBarBadge.foreground": accfg,
            "statusBar.background": acc,
            "statusBar.foreground": accfg,
            "statusBar.noFolderBackground": ROLES["accent_dark"],
            "statusBar.debuggingBackground": ROLES["accent_dark"],
            "titleBar.activeBackground": ROLES["surface"],
            "titleBar.activeForeground": c["text"],
            "titleBar.inactiveBackground": c["_canvas"],
            "titleBar.inactiveForeground": ROLES["dim"],
            "tab.activeBackground": c["_canvas"],
            "tab.activeForeground": c["text"],
            "tab.activeBorderTop": acc,
            "tab.inactiveBackground": ROLES["surface"],
            "tab.inactiveForeground": ROLES["dim"],
            "editorGroupHeader.tabsBackground": ROLES["surface"],
            "panel.background": c["_canvas"],
            "panel.border": ROLES["border"],
            "input.background": ROLES["surface"],
            "input.foreground": c["text"],
            "input.border": ROLES["border"],
            "dropdown.background": ROLES["surface"],
            "dropdown.foreground": c["text"],
            "button.background": acc,
            "button.foreground": accfg,
            "badge.background": acc,
            "badge.foreground": accfg,
            "list.activeSelectionBackground": acc,
            "list.activeSelectionForeground": accfg,
            "list.inactiveSelectionBackground": ROLES["surface_alt"],
            "list.hoverBackground": ROLES["surface_alt"],
            "scrollbarSlider.background": ROLES["border"],
            "scrollbarSlider.hoverBackground": ROLES["dim"],
            # semantic info/warning/error — same meanings the terminal tools
            # use (buildkit run-blue, git/zathura warning-yellow, vifm
            # ErrorMsg bright-red); covers notification toasts, editor
            # squiggles and the Problems panel
            "notifications.background": ROLES["surface"],
            "notifications.foreground": c["text"],
            "notifications.border": ROLES["border"],
            "notificationCenterHeader.background": ROLES["surface_alt"],
            "notificationsInfoIcon.foreground": ANSI["blue"],
            "notificationsWarningIcon.foreground": ANSI["yellow"],
            "notificationsErrorIcon.foreground": ANSI["bright_red"],
            "editorInfo.foreground": ANSI["blue"],
            "editorWarning.foreground": ANSI["yellow"],
            "editorError.foreground": ANSI["bright_red"],
            "terminal.background": c["_canvas"],
            "terminal.foreground": c["text"],
            "terminalCursor.foreground": acc,
            "terminal.ansiBlack": ANSI["black"],
            "terminal.ansiRed": ANSI["red"],
            "terminal.ansiGreen": ANSI["green"],
            "terminal.ansiYellow": ANSI["yellow"],
            "terminal.ansiBlue": ANSI["blue"],
            "terminal.ansiMagenta": ANSI["magenta"],
            "terminal.ansiCyan": ANSI["cyan"],
            "terminal.ansiWhite": ANSI["white"],
            "terminal.ansiBrightBlack": ANSI["bright_black"],
            "terminal.ansiBrightRed": ANSI["bright_red"],
            "terminal.ansiBrightGreen": ANSI["bright_green"],
            "terminal.ansiBrightYellow": ANSI["bright_yellow"],
            "terminal.ansiBrightBlue": ANSI["bright_blue"],
            "terminal.ansiBrightMagenta": ANSI["bright_magenta"],
            "terminal.ansiBrightCyan": ANSI["bright_cyan"],
            "terminal.ansiBrightWhite": ANSI["bright_white"],
        }
    else:  # vscode light — minimal chrome for now; the light desktop ramp
        # exists since 0.6.0 (M7 PR1), and the full role-mapped light chrome
        # lands with the long-tail PR (M7 PR2). Until then unspecified UI
        # falls back to VS Code's own light defaults.
        acc, accfg = LIGHT["roles"]["accent"], ROLES["accent_fg"]
        colors = {
            "focusBorder": acc,
            "textLink.foreground": c["link"],
            "textLink.activeForeground": c["link"],
            "editorLink.activeForeground": c["link"],
            "editor.background": c["_canvas"],
            "editor.foreground": c["text"],
            "editorCursor.foreground": acc,
            "editorLineNumber.foreground": LIGHT["roles"]["dim"],
            "statusBar.background": acc,
            "statusBar.foreground": accfg,
            "button.background": acc,
            "button.foreground": accfg,
            "badge.background": acc,
            "badge.foreground": accfg,
        }
    doc = {
        "_provenance": PROVENANCE,
        "name": f"hestia-{variant}",
        "type": variant,
        "colors": colors,
        "tokenColors": token_colors(c),
    }
    return json.dumps(doc, indent=2, ensure_ascii=False) + "\n"


# ------------------------------------------------- desktop chrome (M7 switch)
# Per-app colour fragments, both variants; the bootstrap manifest symlinks the
# `theme_variant` one to a variant-neutral destination (theme.conf / theme.css).
# Roles/ANSI only — no syntax scopes. Mappings live here (platform-quirk rule).

def render_kitty(variant: str) -> str:
    r, a = vroles(variant), vansi(variant)
    slots = [
        "black", "red", "green", "yellow", "blue", "magenta", "cyan", "white",
        "bright_black", "bright_red", "bright_green", "bright_yellow",
        "bright_blue", "bright_magenta", "bright_cyan", "bright_white",
    ]
    lines = [f"# {PROVENANCE}", f"# kitty colours — {variant} (see kitty.conf: include theme.conf)", ""]
    if variant == "dark":
        lines += ["# Note: bg == ANSI color0 — accepted; watch item in the roadmap backlog.", ""]
    lines += [
        f"background            {r['bg']}",
        f"foreground            {r['text']}",
        f"cursor                {r['accent']}",
        f"cursor_text_color     {r['accent_fg']}",
        f"selection_background  {r['accent']}",
        f"selection_foreground  {r['accent_fg']}",
        "",
    ]
    for i, slot in enumerate(slots):
        lines.append(f"color{i:<2} {a[slot]}")
    lines += [
        "",
        f"active_tab_background   {r['accent']}",
        f"active_tab_foreground   {r['accent_fg']}",
        f"inactive_tab_background {r['surface']}",
        f"inactive_tab_foreground {r['dim']}",
        f"tab_bar_background      {r['bg']}",
        "",
        "# Split borders (kitty's default active is green) — quiet greys",
        f"active_border_color   {r['surface']}",
        f"inactive_border_color {r['border']}",
        "",
    ]
    return "\n".join(lines)


def render_sway(variant: str) -> str:
    r = vroles(variant)
    scheme = "prefer-dark" if variant == "dark" else "prefer-light"
    gtk_theme = "hestia-dark" if variant == "dark" else "hestia"
    return f"""# {PROVENANCE}
# sway theme fragment — {variant} (see config: include ~/.config/sway/theme.conf)

# Colors (roles from palette.yml)
set $bg        {r["bg"]}
set $surface   {r["surface"]}
set $border    {r["border"]}
set $text      {r["text"]}
set $dim       {r["dim"]}
set $accent    {r["accent"]}
set $accent_fg {r["accent_fg"]}

# Desktop background
output * bg {r["bg"]} solid_color

# GTK / portal appearance for this variant (CLAUDE.md GTK section): color-scheme
# is what Firefox/portal-aware/libadwaita apps follow; gtk-theme is what the
# portal file chooser reads (in-process GTK3 apps follow start-sway's GTK_THEME).
# `exec` runs at login only — not re-run on `swaymsg reload`.
exec gsettings set org.gnome.desktop.interface color-scheme {scheme}
exec gsettings set org.gnome.desktop.interface gtk-theme {gtk_theme}
# Icon theme: the #d7005f-accent Yaru built by the opt-in yaru_icons role
# (Yaru-hestia). Guard on the theme actually existing so a spin without that
# role doesn't force a missing theme.
exec sh -c 'test -d "$HOME/.local/share/icons/Yaru-hestia" && gsettings set org.gnome.desktop.interface icon-theme Yaru-hestia'
"""


def render_waybar_css(variant: str) -> str:
    r, a = vroles(variant), vansi(variant)
    tokens = {
        "bg": r["bg"],
        "text": r["text"],
        "muted": r["muted"],
        "border": r["border"],
        "surface_alt": r["surface_alt"],
        "accent": r["accent"],
        "accent_fg": r["accent_fg"],
        # muted-state icons (pulseaudio.muted) — ANSI bright_black, the
        # quietest grey that still reads on the bar
        "icon_muted": a["bright_black"],
    }
    lines = [f"/* {PROVENANCE}",
             f"   waybar colour tokens — {variant} (style.css: @import \"theme.css\") */", ""]
    lines += [f"@define-color {k} {v};" for k, v in tokens.items()]
    lines.append("")
    return "\n".join(lines)


OUTPUTS = {
    REPO / "user/bat/themes/wildcharm.tmTheme": render_tmtheme,
    HERE / "dist/shiki/hestia-dark.json": lambda: theme_json("dark", "shiki"),
    HERE / "dist/shiki/hestia-light.json": lambda: theme_json("light", "shiki"),
    REPO / "user/vscode/hestia/themes/hestia-dark-color-theme.json": lambda: theme_json("dark", "vscode"),
    REPO / "user/vscode/hestia/themes/hestia-light-color-theme.json": lambda: theme_json("light", "vscode"),
    REPO / "user/kitty/theme-dark.conf": lambda: render_kitty("dark"),
    REPO / "user/kitty/theme-light.conf": lambda: render_kitty("light"),
    REPO / "user/sway/theme-dark.conf": lambda: render_sway("dark"),
    REPO / "user/sway/theme-light.conf": lambda: render_sway("light"),
    REPO / "user/waybar/theme-dark.css": lambda: render_waybar_css("dark"),
    REPO / "user/waybar/theme-light.css": lambda: render_waybar_css("light"),
}


def main() -> None:
    aa_gate()
    check = "--check" in sys.argv
    drift = []
    for path, renderer in OUTPUTS.items():
        content = renderer()
        rel = path.relative_to(REPO)
        if check:
            if not path.exists() or path.read_text() != content:
                drift.append(str(rel))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
            print(f"rendered {rel}")
    if check:
        if drift:
            sys.exit("STALE (re-run render.py):\n  " + "\n  ".join(drift))
        print(f"check ok — all {len(OUTPUTS)} artifacts match palette v{VERSION}")


if __name__ == "__main__":
    main()
