#!/usr/bin/env python3
"""render.py — generate the theme artifacts from the palette.

Layer 3 of the theme pipeline (docs/theme-roadmap.md): reads palette.yml
(colours, per variant) + scopes.yml (the shared role→scope map) and renders

TextMate family (syntax + chrome):
  user/bat/themes/wildcharm.tmTheme                      (dark; terminal chrome)
  themes/wildcharm/dist/shiki/hestia-{dark,light}.json   (web code blocks;
                                                          bg = the code SURFACE)
  user/vscode/hestia/themes/hestia-{dark,light}-color-theme.json
                                                         (editor; bg = the app
                                                          CANVAS + UI chrome)

Desktop chrome, both variants each (roles/ANSI only — no scopes; the bootstrap
symlinks the one `theme_variant` selects to a variant-neutral dest, M7):
  fragments   kitty/sway/mako theme-*.conf, waybar theme-*.css, zathura
              theme-* (include'd/@import'ed by the main configs), wofi
              colors-* (wofi's own colors-file macro mechanism — no @import)
  whole-file  swaylock/swaynag config-* (no include support)
  theme pairs vifm wildcharm-*.vifm, bat wildcharm-*.tmTheme (TM family),
              glow wildcharm-*.json, bash .dircolors-* (ls file colours —
              generated from the SAME table as vifm so they cannot drift)
  single-file thunderbird userChrome/userContent.css — CSS light-dark()
              carries both variants in one file (TB follows the portal
              color-scheme), so no pair + variant symlink

Same tokenColors everywhere; only the per-target chrome differs. The WCAG AA
contrast gate runs before anything is written — a palette edit that breaks a
plain-text role fails the render (reverse/fill roles are exempt; they are
checked as pairings by eye).

Usage:  render.py            render all artifacts in place
        render.py --check    exit 1 if any committed artifact differs from a
                             fresh render (use before/in review)

Never edit the generated files by hand — scope decisions go in scopes.yml,
colours in palette.yml, chrome maps below.
"""

import json
import sys
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent

PALETTE = yaml.safe_load((HERE / "palette.yml").read_text())
SCOPES = yaml.safe_load((HERE / "scopes.yml").read_text())["rules"]
VERSION = PALETTE["version"]
PROVENANCE = (
    f"GENERATED by themes/wildcharm/render.py from palette.yml v{VERSION} "
    f"+ scopes.yml — do not edit; edit the sources and re-render"
)

ROLES = PALETTE["roles"]
ANSI = PALETTE["ansi"]
LIGHT = PALETTE["light"]

# role → colour, per variant. `link` on light is the accent (it clears AA as
# text on white — decision log); error is the paired fill role.
VARIANTS = {
    "dark": {
        **PALETTE["syntax"],
        "text": ROLES["text"],
        "link": ROLES["link"],
        "error_fg": "#ffffff",
        "error_bg": ROLES["accent_dark"],
        # surfaces the plain-text roles must clear AA against. Since 0.5.0 the
        # web code surface IS the ground (it reads raised on tci's darker
        # page); surface_alt is transient (hover/line-highlight), not a body-
        # text surface, so it is deliberately NOT gated here.
        "_aa_surfaces": [ROLES["bg"]],
        # per-target canvas/surface
        "_canvas": ROLES["bg"],          # vim/bat/VS Code app canvas
        "_code_surface": ROLES["bg"],    # web code blocks == the ground
    },
    "light": {
        **LIGHT["syntax"],
        "text": LIGHT["roles"]["text"],
        "link": LIGHT["roles"]["accent"],
        "error_fg": "#ffffff",
        "error_bg": LIGHT["syntax"]["error"],
        # the light gate runs against the #f5f5f5 DESKTOP ground (M7) — stricter
        # than the #ffffff code surface, so white is covered by implication
        "_aa_surfaces": [LIGHT["roles"]["bg"]],
        "_canvas": LIGHT["roles"]["bg"],
        # the web code surface keeps the M3 pure white (light-only split;
        # dark's code surface == the ground)
        "_code_surface": LIGHT["roles"]["code_surface"],
    },
}

# per-variant role/ANSI tables for the desktop-chrome emitters
def vroles(variant: str) -> dict:
    return ROLES if variant == "dark" else LIGHT["roles"]


def vansi(variant: str) -> dict:
    return ANSI if variant == "dark" else LIGHT["ansi"]

FILL_ROLES = {"error", "todo"}  # reverse/fill — exempt from the plain-text gate


def _lum(hexval: str) -> float:
    h = hexval.lstrip("#")
    c = [int(h[i : i + 2], 16) / 255 for i in (0, 2, 4)]
    c = [x / 12.92 if x <= 0.04045 else ((x + 0.055) / 1.055) ** 2.4 for x in c]
    return 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2]


def contrast(a: str, b: str) -> float:
    la, lb = sorted((_lum(a), _lum(b)), reverse=True)
    return (la + 0.05) / (lb + 0.05)


def aa_gate() -> None:
    failures = []
    for variant, colors in VARIANTS.items():
        for role, hexval in colors.items():
            if role.startswith("_") or role in FILL_ROLES or role.startswith("error"):
                continue
            for surface in colors["_aa_surfaces"]:
                r = contrast(hexval, surface)
                if r < 4.5:
                    failures.append(f"{variant}.{role} {hexval} on {surface}: {r:.2f}:1")
    if failures:
        sys.exit("AA contrast gate FAILED:\n  " + "\n  ".join(failures))


def token_colors(colors: dict) -> list:
    out = []
    for rule in SCOPES:
        settings = {}
        role = rule.get("role")
        if rule.get("paired"):
            settings["foreground"] = colors["error_fg"]
            settings["background"] = colors["error_bg"]
        elif role:
            settings["foreground"] = colors[role]
        if rule.get("font_style"):
            settings["fontStyle"] = rule["font_style"]
        out.append({"name": rule["name"], "scope": rule["scopes"], "settings": settings})
    return out


# ---------------------------------------------------------------- tmTheme (bat)

def render_tmtheme(variant: str = "dark") -> str:
    c = VARIANTS[variant]
    r = vroles(variant)
    chrome = {
        "background": c["_canvas"],
        "foreground": c["text"],
        "caret": r["accent"],
        "lineHighlight": r["surface_alt"],
        "selection": r["border"],
        "invisibles": r["dim"],
        "guide": r["border"],
        "activeGuide": r["dim"],
        "gutterForeground": r["dim"],
    }
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
        f"<!-- {PROVENANCE} -->",
        '<plist version="1.0">',
        "<dict>",
        "  <key>name</key>",
        "  <string>wildcharm</string>",
        "  <key>settings</key>",
        "  <array>",
        "",
        "    <dict>",
        "      <key>settings</key>",
        "      <dict>",
    ]
    for k, v in chrome.items():
        lines.append(f"        <key>{k}</key> <string>{v}</string>")
    lines += ["      </dict>", "    </dict>"]
    for tc in token_colors(c):
        lines += [
            "",
            "    <dict>",
            f"      <key>name</key><string>{tc['name']}</string>",
            f"      <key>scope</key><string>{', '.join(tc['scope'])}</string>",
            "      <key>settings</key>",
            "      <dict>",
        ]
        for k, v in tc["settings"].items():
            lines.append(f"        <key>{k}</key><string>{v}</string>")
        lines += ["      </dict>", "    </dict>"]
    lines += ["", "  </array>", "</dict>", "</plist>", ""]
    return "\n".join(lines)


# ------------------------------------------------------------------ theme JSON

def theme_json(variant: str, target: str) -> str:
    c = VARIANTS[variant]
    if target == "shiki":
        colors = {
            "editor.background": c["_code_surface"],
            "editor.foreground": c["text"],
        }
    else:  # vscode — full UI chrome from the variant's roles + ANSI (since M7
        # PR2 light mirrors dark's chrome key-for-key; before that light shipped
        # minimal chrome and fell back to VS Code's stock light UI)
        r, a = vroles(variant), vansi(variant)
        acc, accfg = r["accent"], r["accent_fg"]
        colors = {
            "focusBorder": acc,
            "foreground": c["text"],
            # links in UI text (chat/welcome/notifications) + ctrl-hover links
            # in the editor — default to VS Code blue unless mapped
            "textLink.foreground": c["link"],
            "textLink.activeForeground": c["link"],
            "editorLink.activeForeground": c["link"],
            "editor.background": c["_canvas"],
            "editor.foreground": c["text"],
            "editor.lineHighlightBackground": r["surface_alt"],
            "editor.selectionBackground": r["border"],
            "editorCursor.foreground": acc,
            "editorLineNumber.foreground": r["dim"],
            "editorLineNumber.activeForeground": c["text"],
            "editorIndentGuide.background1": r["border"],
            "editorIndentGuide.activeBackground1": r["dim"],
            "editorWhitespace.foreground": r["border"],
            "sideBar.background": r["surface"],
            "sideBar.foreground": r["muted"],
            "sideBar.border": r["border"],
            "sideBarTitle.foreground": c["text"],
            "activityBar.background": c["_canvas"],
            "activityBar.foreground": c["text"],
            "activityBar.inactiveForeground": r["dim"],
            "activityBarBadge.background": acc,
            "activityBarBadge.foreground": accfg,
            "statusBar.background": acc,
            "statusBar.foreground": accfg,
            "statusBar.noFolderBackground": r["accent_dark"],
            "statusBar.debuggingBackground": r["accent_dark"],
            "titleBar.activeBackground": r["surface"],
            "titleBar.activeForeground": c["text"],
            "titleBar.inactiveBackground": c["_canvas"],
            "titleBar.inactiveForeground": r["dim"],
            "tab.activeBackground": c["_canvas"],
            "tab.activeForeground": c["text"],
            "tab.activeBorderTop": acc,
            "tab.inactiveBackground": r["surface"],
            "tab.inactiveForeground": r["dim"],
            "editorGroupHeader.tabsBackground": r["surface"],
            "panel.background": c["_canvas"],
            "panel.border": r["border"],
            "input.background": r["surface"],
            "input.foreground": c["text"],
            "input.border": r["border"],
            "dropdown.background": r["surface"],
            "dropdown.foreground": c["text"],
            "button.background": acc,
            "button.foreground": accfg,
            "badge.background": acc,
            "badge.foreground": accfg,
            "list.activeSelectionBackground": acc,
            "list.activeSelectionForeground": accfg,
            "list.inactiveSelectionBackground": r["surface_alt"],
            "list.hoverBackground": r["surface_alt"],
            "scrollbarSlider.background": r["border"],
            "scrollbarSlider.hoverBackground": r["dim"],
            # semantic info/warning/error — same meanings the terminal tools
            # use (buildkit run-blue, git/zathura warning-yellow, vifm
            # ErrorMsg bright-red); covers notification toasts, editor
            # squiggles and the Problems panel
            "notifications.background": r["surface"],
            "notifications.foreground": c["text"],
            "notifications.border": r["border"],
            "notificationCenterHeader.background": r["surface_alt"],
            "notificationsInfoIcon.foreground": a["blue"],
            "notificationsWarningIcon.foreground": a["yellow"],
            "notificationsErrorIcon.foreground": a["bright_red"],
            "editorInfo.foreground": a["blue"],
            "editorWarning.foreground": a["yellow"],
            "editorError.foreground": a["bright_red"],
            "terminal.background": c["_canvas"],
            "terminal.foreground": c["text"],
            "terminalCursor.foreground": acc,
            "terminal.ansiBlack": a["black"],
            "terminal.ansiRed": a["red"],
            "terminal.ansiGreen": a["green"],
            "terminal.ansiYellow": a["yellow"],
            "terminal.ansiBlue": a["blue"],
            "terminal.ansiMagenta": a["magenta"],
            "terminal.ansiCyan": a["cyan"],
            "terminal.ansiWhite": a["white"],
            "terminal.ansiBrightBlack": a["bright_black"],
            "terminal.ansiBrightRed": a["bright_red"],
            "terminal.ansiBrightGreen": a["bright_green"],
            "terminal.ansiBrightYellow": a["bright_yellow"],
            "terminal.ansiBrightBlue": a["bright_blue"],
            "terminal.ansiBrightMagenta": a["bright_magenta"],
            "terminal.ansiBrightCyan": a["bright_cyan"],
            "terminal.ansiBrightWhite": a["bright_white"],
        }
    doc = {
        "_provenance": PROVENANCE,
        "name": f"hestia-{variant}",
        "type": variant,
        "colors": colors,
        "tokenColors": token_colors(c),
    }
    return json.dumps(doc, indent=2, ensure_ascii=False) + "\n"


# ------------------------------------------------- desktop chrome (M7 switch)
# Per-app colour fragments, both variants; the bootstrap manifest symlinks the
# `theme_variant` one to a variant-neutral destination (theme.conf / theme.css).
# Roles/ANSI only — no syntax scopes. Mappings live here (platform-quirk rule).

def render_kitty(variant: str) -> str:
    r, a = vroles(variant), vansi(variant)
    slots = [
        "black", "red", "green", "yellow", "blue", "magenta", "cyan", "white",
        "bright_black", "bright_red", "bright_green", "bright_yellow",
        "bright_blue", "bright_magenta", "bright_cyan", "bright_white",
    ]
    lines = [f"# {PROVENANCE}", f"# kitty colours — {variant} (see kitty.conf: include theme.conf)", ""]
    if variant == "dark":
        lines += ["# Note: bg == ANSI color0 — accepted; watch item in the roadmap backlog.", ""]
    lines += [
        f"background            {r['bg']}",
        f"foreground            {r['text']}",
        f"cursor                {r['accent']}",
        f"cursor_text_color     {r['accent_fg']}",
        f"selection_background  {r['accent']}",
        f"selection_foreground  {r['accent_fg']}",
        "",
    ]
    for i, slot in enumerate(slots):
        lines.append(f"color{i:<2} {a[slot]}")
    lines += [
        "",
        f"active_tab_background   {r['accent']}",
        f"active_tab_foreground   {r['accent_fg']}",
        f"inactive_tab_background {r['surface']}",
        f"inactive_tab_foreground {r['dim']}",
        f"tab_bar_background      {r['bg']}",
        "",
        "# Split borders (kitty's default active is green) — quiet greys",
        f"active_border_color   {r['surface']}",
        f"inactive_border_color {r['border']}",
        "",
    ]
    return "\n".join(lines)


def render_sway(variant: str) -> str:
    r = vroles(variant)
    scheme = "prefer-dark" if variant == "dark" else "prefer-light"
    gtk_theme = "hestia-dark" if variant == "dark" else "hestia"
    # KDE Breeze cursors (breeze-cursor-theme, apt): the WHITE cursor on the
    # dark desktop, the standard dark "Breeze" on light. Names are the theme
    # DIRS in /usr/share/icons (index.theme: Breeze Light / Breeze).
    cursor = "Breeze_Light" if variant == "dark" else "breeze_cursors"
    return f"""# {PROVENANCE}
# sway theme fragment — {variant} (see config: include ~/.config/sway/theme.conf)

# Colors (roles from palette.yml)
set $bg        {r["bg"]}
set $surface   {r["surface"]}
set $border    {r["border"]}
set $text      {r["text"]}
set $dim       {r["dim"]}
set $accent    {r["accent"]}
set $accent_fg {r["accent_fg"]}

# Desktop background
output * bg {r["bg"]} solid_color

# Mouse cursor — sway's own cursor (window drags, resize, the bare desktop).
# Clients draw their own: GTK reads the gsettings exec below + settings.ini,
# XWayland/Qt read start-sway's XCURSOR_THEME export (all follow the variant).
seat * xcursor_theme {cursor} 24

# GTK / portal appearance for this variant (CLAUDE.md GTK section): color-scheme
# is what Firefox/portal-aware/libadwaita apps follow; gtk-theme is what the
# portal file chooser reads (in-process GTK3 apps follow start-sway's GTK_THEME).
# `exec` runs at login only — not re-run on `swaymsg reload`.
exec gsettings set org.gnome.desktop.interface color-scheme {scheme}
exec gsettings set org.gnome.desktop.interface gtk-theme {gtk_theme}
exec gsettings set org.gnome.desktop.interface cursor-theme {cursor}
# Icon theme: the #d7005f-accent Yaru built by the opt-in yaru_icons role
# (Yaru-hestia). Guard on the theme actually existing so a spin without that
# role doesn't force a missing theme.
exec sh -c 'test -d "$HOME/.local/share/icons/Yaru-hestia" && gsettings set org.gnome.desktop.interface icon-theme Yaru-hestia'
"""


def render_waybar_css(variant: str) -> str:
    r, a = vroles(variant), vansi(variant)
    tokens = {
        "bg": r["bg"],
        "text": r["text"],
        "muted": r["muted"],
        "border": r["border"],
        "surface_alt": r["surface_alt"],
        "accent": r["accent"],
        "accent_fg": r["accent_fg"],
        # muted-state icons (pulseaudio.muted) — ANSI bright_black, the
        # quietest grey that still reads on the bar
        "icon_muted": a["bright_black"],
    }
    lines = [f"/* {PROVENANCE}",
             f"   waybar colour tokens — {variant} (style.css: @import \"theme.css\") */", ""]
    lines += [f"@define-color {k} {v};" for k, v in tokens.items()]
    lines.append("")
    return "\n".join(lines)


# ----------------------------------------------- xterm-256 index (vifm cterm)

_CUBE = [0, 95, 135, 175, 215, 255]


def xterm_index(hexval: str) -> int:
    """Nearest xterm-256 index (16-255). Palette values are xterm-native except
    the two grounds (#1a1a1a -> 234, #f5f5f5 -> 255) — nearest steps, matching
    the cterm fallbacks hestia.vim uses."""
    h = hexval.lstrip("#")
    r, g, b = (int(h[i : i + 2], 16) for i in (0, 2, 4))
    best, best_d = 16, 3 * 255 ** 2 + 1
    for ri, rv in enumerate(_CUBE):
        for gi, gv in enumerate(_CUBE):
            for bi, bv in enumerate(_CUBE):
                d = (r - rv) ** 2 + (g - gv) ** 2 + (b - bv) ** 2
                if d < best_d:
                    best, best_d = 16 + 36 * ri + 6 * gi + bi, d
    for i in range(24):
        v = 8 + 10 * i
        d = (r - v) ** 2 + (g - v) ** 2 + (b - v) ** 2
        if d < best_d:
            best, best_d = 232 + i, d
    return best


# ------------------------------------------- desktop chrome, the long tail (M7)

EXT = PALETTE["extended"]
LEXT = LIGHT["extended"]


def vext(variant: str) -> dict:
    # light falls back to the shared extended for variant-invariant values (ink)
    return EXT if variant == "dark" else {**EXT, **LEXT}


def _css_tokens(variant: str, tokens: dict, note: str) -> str:
    lines = [f"/* {PROVENANCE}", f"   {note} */", ""]
    lines += [f"@define-color {k} {v};" for k, v in tokens.items()]
    lines.append("")
    return "\n".join(lines)


def render_mako(variant: str) -> str:
    r, e = vroles(variant), vext(variant)
    return f"""# {PROVENANCE}
# mako colours — {variant}. Included LAST by ~/.config/mako/config so the
# [urgency=high] section below can't swallow main-config keys. default-timeout=0
# rides with the section (criteria keys must stay inside it): urgent sticks.

background-color={r["bg"]}
text-color={r["text"]}
border-color={r["accent"]}

[urgency=high]
background-color={r["accent"]}
border-color={r["accent_dark"]}
text-color={r["accent_fg"]}
default-timeout=0
"""


# wofi does NOT support @import/@define-color fragments: it preprocesses the
# stylesheet TEXT itself (substituting --wofi-color<n> macros from its "colors
# file") and then hands the result to GTK, so a relative @import never resolves
# (caught live — the launcher rendered transparent). The native mechanism is the
# colors file: newline-separated hexes, line N referenced as --wofi-color<N-1>
# in style.css, path wired by `colors=` in the wofi config (relative paths
# resolve against ~/.config/wofi). SLOT ORDER (style.css documents it too):
WOFI_SLOTS = ["bg", "text", "muted", "border", "surface", "accent", "accent_fg"]


def render_wofi_colors(variant: str) -> str:
    # NO comments/provenance in this file — wofi parses every line as a hex
    r = vroles(variant)
    return "\n".join(r[slot] for slot in WOFI_SLOTS) + "\n"


def render_swaylock(variant: str) -> str:
    r, a, e = vroles(variant), vansi(variant), vext(variant)
    def b(h):  # swaylock wants bare RRGGBB
        return h.lstrip("#")
    return f"""# {PROVENANCE}
# swaylock — wildcharm lockscreen, {variant} (config-dark / config-light pair;
# the bootstrap symlinks the `theme_variant` one to ~/.config/swaylock/config).
#
# IMPORTANT: swaylock's config parser only supports WHOLE-LINE `#` comments — it
# does NOT strip trailing/inline comments. Keep every annotation on its own line;
# values are bare RRGGBB (no leading '#').
#
# Sway invokes `swaylock -f` (no -c flag), so `color` below is the single source
# for the lock background. `indicator-idle-visible` keeps the ring on when idle.

color={b(r["bg"])}
font=Lilex Nerd Font Mono
indicator-radius=110
indicator-thickness=8
indicator-idle-visible
indicator-caps-lock
show-failed-attempts

# idle (no input): inside=sunken, ring=border, line/separator=bg, text=text
inside-color={b(e["sunken"])}
ring-color={b(r["border"])}
line-color={b(r["bg"])}
separator-color={b(r["bg"])}
text-color={b(r["text"])}

# typing: key highlight = accent, backspace = bright_red
key-hl-color={b(r["accent"])}
bs-hl-color={b(a["bright_red"])}

# verifying (checking password): ring = blue
inside-ver-color={b(e["sunken"])}
ring-ver-color={b(a["blue"])}
line-ver-color={b(r["bg"])}
text-ver-color={b(r["text"])}

# wrong password: ring = bright_red, inside = accent_dark, text = accent_fg
inside-wrong-color={b(r["accent_dark"])}
ring-wrong-color={b(a["bright_red"])}
line-wrong-color={b(r["bg"])}
text-wrong-color={b(r["accent_fg"])}

# cleared (input wiped): ring = accent
inside-clear-color={b(e["sunken"])}
ring-clear-color={b(r["accent"])}
line-clear-color={b(r["bg"])}
text-clear-color={b(r["text"])}

# caps lock on: ring + highlight = bright_yellow (warning), backspace = bright_red
inside-caps-lock-color={b(e["sunken"])}
ring-caps-lock-color={b(a["bright_yellow"])}
caps-lock-key-hl-color={b(a["bright_yellow"])}
caps-lock-bs-hl-color={b(a["bright_red"])}
text-caps-lock-color={b(r["text"])}
"""


def render_swaynag(variant: str) -> str:
    # Typeless dialogs keep the quiet dark base with an accent line; the two
    # built-in types are FULL-FILL banners so they can't be missed — warning
    # (the $mod+Shift+e exit confirm, and the power-menu confirms) is a solid
    # orange bar with ink text, error the accent fill with accent_fg. Buttons/
    # details keep the global sunken+text treatment on every section — the
    # neutral wells read fine on the fills and the emitter stays one loop.
    r, a, e = vroles(variant), vansi(variant), vext(variant)
    def b(h):
        return h.lstrip("#")
    sections = [
        ("global / default (dialogs with no -t): dark base, accent line",
         None, r["bg"], r["text"], r["border"], r["accent"]),
        ("warning (the sway exit confirm passes -t warning): full orange banner",
         "warning", a["bright_yellow"], e["ink"], a["yellow"], a["yellow"]),
        ("error: full accent banner",
         "error", r["accent"], r["accent_fg"], r["accent_dark"], r["accent_dark"]),
    ]
    out = [f"# {PROVENANCE}",
           f"# swaynag — wildcharm dialogs, {variant} (config-dark / config-light pair; the",
           "# bootstrap symlinks the `theme_variant` one to ~/.config/swaynag/config).",
           "# Values are bare RRGGBB (no '#'); annotations on their own lines.",
           "#",
           "# GOTCHA: swaynag's built-in `warning`/`error` types ship hardcoded colours and",
           "# do NOT layer the global options — only keys set INSIDE a type's [section]",
           "# override its presets, so the theme is restated in full per section.",
           ""]
    for title, section, bg, text, border, accent_line in sections:
        out.append(f"# --- {title} ---")
        if section:
            out.append(f"[{section}]")
        else:
            out.append("font=Lilex Nerd Font Mono 11")
        out += [
            f"background={b(bg)}",
            f"border={b(border)}",
            f"border-bottom={b(accent_line)}",
            "border-bottom-size=2",
            f"text={b(text)}",
            f"button-background={b(e['sunken'])}",
            f"button-text={b(r['text'])}",
            f"details-background={b(e['sunken'])}",
            "",
        ]
    return "\n".join(out)


def render_zathura(variant: str) -> str:
    r, a = vroles(variant), vansi(variant)
    def rgba(h, alpha):
        v = h.lstrip("#")
        rr, gg, bb = (int(v[i : i + 2], 16) for i in (0, 2, 4))
        return f'"rgba({rr}, {gg}, {bb}, {alpha})"'
    # warning fill takes contrast text: the dark ground on dark's yellow, white
    # on light's darker yellow
    warn_fg = r["bg"] if variant == "dark" else r["accent_fg"]
    # recolour is a dark-mode feature: on by default on dark (white pages ->
    # ground), OFF on light (pages are already light); `r` toggles either way,
    # so both variants carry sensible recolor-* values.
    recolor = "true" if variant == "dark" else "false"
    return f"""# {PROVENANCE}
# zathura colours — {variant} (theme-dark / theme-light pair; the bootstrap
# symlinks the `theme_variant` one to ~/.config/zathura/theme, `include`d by
# zathurarc). zathura takes "#RRGGBB" (+ rgba(...) for translucent highlights).

# --- window / page area ---
set default-bg          "{r["bg"]}"
set default-fg          "{r["text"]}"
set render-loading-bg   "{r["bg"]}"
set render-loading-fg   "{r["text"]}"

# --- statusbar (bottom bar) ---
set statusbar-bg        "{r["surface"]}"
set statusbar-fg        "{r["text"]}"

# --- inputbar (the ':' command line) ---
set inputbar-bg         "{r["surface"]}"
set inputbar-fg         "{r["text"]}"

# --- notifications (info / warning / error) ---
set notification-bg         "{r["surface"]}"
set notification-fg         "{r["text"]}"
set notification-warning-bg "{a["yellow"]}"
set notification-warning-fg "{warn_fg}"
set notification-error-bg   "{r["accent_dark"]}"
set notification-error-fg   "{r["accent_fg"]}"

# --- search highlights (translucent so the text shows through) ---
# all matches = blue; the active/focused match = accent
set highlight-color        {rgba(a["blue"], "0.35")}
set highlight-active-color {rgba(r["accent"], "0.5")}

# --- completion menu (Tab) ---
set completion-bg           "{r["surface"]}"
set completion-fg           "{r["text"]}"
set completion-group-bg     "{r["bg"]}"
set completion-group-fg     "{r["accent"]}"
set completion-highlight-bg "{r["accent"]}"
set completion-highlight-fg "{r["accent_fg"]}"

# --- index / table of contents ---
set index-bg        "{r["bg"]}"
set index-fg        "{r["text"]}"
set index-active-bg "{r["accent"]}"
set index-active-fg "{r["accent_fg"]}"

# --- document recolouring (invert page content toward the theme) ---
set recolor            {recolor}
set recolor-keephue    true
set recolor-lightcolor "{r["bg"]}"
set recolor-darkcolor  "{r["text"]}"
"""


def filetype_colors(variant: str) -> dict:
    """File-type colours shared by vifm AND dircolors — one table so `ls` and
    vifm cannot drift. Dark rides the vivid BRIGHT ANSI slots; on light the
    common groups drop to the BASE slots for readability (decision log — the
    bright slots are dark-tuned; upstream's own light design makes the same
    move). Light Link == Fifo (both base cyan) — accepted, fifos are rare."""
    r, a = vroles(variant), vansi(variant)
    if variant == "dark":
        return {
            "dir": a["bright_blue"], "link": a["bright_cyan"], "exec": a["bright_green"],
            "broken": a["bright_red"], "hardlink": a["bright_yellow"],
            "socket": a["bright_magenta"], "device": a["yellow"], "fifo": a["cyan"],
            "archives": a["bright_red"], "images": a["bright_magenta"],
            "video": a["magenta"], "audio": a["bright_cyan"],
            "docs": a["bright_yellow"], "markdown": a["white"],
        }
    return {
        "dir": a["blue"], "link": a["cyan"], "exec": a["green"],
        "broken": a["bright_red"], "hardlink": a["bright_yellow"],
        "socket": a["bright_magenta"], "device": a["yellow"], "fifo": a["cyan"],
        "archives": a["bright_red"], "images": a["bright_magenta"],
        "video": a["magenta"], "audio": a["cyan"],
        "docs": a["yellow"], "markdown": r["muted"],
    }


def render_vifm(variant: str) -> str:
    r, a, e = vroles(variant), vansi(variant), vext(variant)
    ft = filetype_colors(variant)
    if variant == "dark":
        ui_fg = e["ui_grey"]       # TopLine text / cursor-bar fill
        bar_fg = e["ink"]          # text ON the grey cursor bar
        tab_fg = a["white"]        # inactive tab/JobLine text (#d0d0d0)
    else:
        ui_fg = e["ui_dark"]       # the inversion: dark-grey bar on light
        bar_fg = r["accent_fg"]    # white text on that bar
        tab_fg = r["muted"]
    line_grey = e["line_grey"]
    # Miller parent-column shade (AuxWin). vifm has no separate group for the
    # parent column's cursor bar — it always paints CurrLine (fileview.c mixes
    # CURR_LINE_COLOR for non-main columns too; maintainer-confirmed, Q2A #1844)
    # — so the supported differentiation is shading the WHOLE aux column one
    # quiet step off the ground. Light uses surface, NOT extended.sunken: light
    # sunken is the white below-ground WELL fill, which would read raised here.
    aux_bg = e["sunken"] if variant == "dark" else r["surface"]

    def hl(group, attr, fg, bg="default"):
        cfg = xterm_index(fg) if fg != "default" else "default"
        cbg = xterm_index(bg) if bg != "default" else "default"
        gfg = fg if fg != "default" else "default"
        gbg = bg if bg != "default" else "default"
        return (f"highlight {group:<10} cterm={attr:<12} ctermfg={cfg!s:<7} "
                f"ctermbg={cbg!s:<7} guifg={gfg} guibg={gbg}")

    rows = [
        "\n\" frame — transparent canvas, terminal ground shows through",
        hl("Win", "none", r["text"]),
        hl("OtherWin", "none", r["text"]),
        "\" AuxWin recesses the miller PARENT column (the only per-column knob —",
        "\" the cursor bar itself is always CurrLine, in every column)",
        hl("AuxWin", "none", "default", aux_bg),
        hl("Border", "none", line_grey),
        hl("CmdLine", "none", r["text"]),
        "\n\" title / tab bar",
        hl("TopLine", "none", ui_fg, r["surface"]),
        hl("TopLineSel", "bold", bar_fg, ui_fg),
        hl("TabLine", "none", tab_fg, r["surface_alt"]),
        hl("TabLineSel", "bold", e["ink"], r["accent"]),
        "\n\" status line / messages — the accent lives here (accent status bar)",
        hl("StatusLine", "bold", r["accent_fg"], r["accent"]),
        hl("JobLine", "bold", tab_fg, r["surface_alt"]),
        hl("WildMenu", "bold", e["ink"], r["accent"]),
        hl("SuggestBox", "none", tab_fg, r["surface_alt"]),
        hl("ErrorMsg", "bold", a["bright_red"]),
        hl("LineNr", "none", line_grey),
        "\n\" cursor / selection — a quiet grey bar; the accent stays on the status line",
        hl("CurrLine", "bold", bar_fg, ui_fg),
        hl("Selected", "bold", a["bright_magenta"]),
        "\n\" file types",
        hl("Directory", "bold", ft["dir"]),
        hl("Link", "none", ft["link"]),
        hl("BrokenLink", "bold", ft["broken"]),
        hl("HardLink", "none", ft["hardlink"]),
        hl("Socket", "none", ft["socket"]),
        hl("Device", "none", ft["device"]),
        hl("Fifo", "none", ft["fifo"]),
        hl("Executable", "bold", ft["exec"]),
    ]
    pats = [
        ("{*.tar,*.tgz,*.tbz2,*.txz,*.zip,*.gz,*.bz2,*.xz,*.zst,*.7z,*.rar}", ft["archives"]),
        ("{*.jpg,*.jpeg,*.png,*.gif,*.bmp,*.tiff,*.webp,*.avif,*.svg,*.ico}", ft["images"]),
        ("{*.mp4,*.mkv,*.webm,*.mov,*.avi,*.m4v,*.flv}", ft["video"]),
        ("{*.mp3,*.flac,*.ogg,*.opus,*.wav,*.m4a,*.aac}", ft["audio"]),
        ("{*.pdf,*.epub,*.djvu}", ft["docs"]),
        ("{*.md,*.markdown}", ft["markdown"]),
    ]
    pat_lines = [
        "\n\" file-name patterns — vifm has no LS_COLORS, so these mirror the extension",
        "\" layer in ~/.dircolors by hand (keeps `ls` and vifm in sync on archives/media).",
    ]
    for pat, fg in pats:
        pat_lines.append(f"highlight {pat} cterm=none ctermfg={xterm_index(fg)} ctermbg=default guifg={fg}")

    header = [
        f"\" {PROVENANCE}",
        f"\" wildcharm.vifm — {variant} (wildcharm-{{dark,light}}.vifm pair; the bootstrap",
        "\" symlinks the `theme_variant` one to ~/.config/vifm/colors/wildcharm.vifm, so",
        "\" vifmrc's `colorscheme wildcharm` needs no variant logic).",
        "\" The canvas paints NO background (guibg=default): the terminal's own ground",
        "\" shows through, so vifm always matches kitty exactly.",
        "",
        "highlight clear",
    ]
    return "\n".join(header + rows + pat_lines) + "\n"


def render_dircolors(variant: str) -> str:
    ft = filetype_colors(variant)

    def c(key, bold=False):
        return ("01;" if bold else "") + f"38;5;{xterm_index(ft[key])}"

    exts = [
        ("archives / compressed", "archives",
         [".tar", ".tgz", ".tbz2", ".txz", ".zip", ".gz", ".bz2", ".xz", ".zst", ".7z", ".rar"]),
        ("images", "images",
         [".jpg", ".jpeg", ".png", ".gif", ".bmp", ".tiff", ".webp", ".avif", ".svg", ".ico"]),
        ("video", "video", [".mp4", ".mkv", ".webm", ".mov", ".avi", ".m4v", ".flv"]),
        ("audio", "audio", [".mp3", ".flac", ".ogg", ".opus", ".wav", ".m4a", ".aac"]),
        ("documents", "docs", [".pdf", ".epub", ".djvu"]),
        ("markdown", "markdown", [".md", ".markdown"]),
    ]
    lines = [
        f"# {PROVENANCE}",
        f"# hestia .dircolors — ls/eza/tree file colours, {variant} (.dircolors-{{dark,light}}",
        "# pair; the bootstrap symlinks the `theme_variant` one to ~/.dircolors).",
        "#",
        "# The file-TYPE colours come from the SAME per-variant table as vifm's generated",
        "# colorscheme (render.py filetype_colors), so `ls` and vifm agree by construction.",
        "# Indices 16-255 are the standard xterm cube (not the wildcharm-remapped 0-15).",
        "#",
        '# Loaded by .bashrc: `test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)"`.',
        "",
        "# Terminals colour is enabled for (kitty + the usual 256-colour set + console).",
        "TERM xterm-kitty",
        "TERM xterm-256color",
        "TERM screen-256color",
        "TERM tmux-256color",
        "TERM *-256color",
        "TERM xterm",
        "TERM screen",
        "TERM tmux",
        "TERM linux",
        "",
        "# --- file types (the vifm-shared table) ---",
        "RESET 0",
        "NORMAL 00",
        "FILE 00                         # regular file — plain, like vifm's Normal fg",
        f"DIR {c('dir', bold=True)}                  # vifm Directory",
        f"LINK {c('link')}                    # vifm Link",
        f"ORPHAN {c('broken', bold=True)}              # vifm BrokenLink",
        f"MISSING {c('broken', bold=True)}",
        f"EXEC {c('exec', bold=True)}                # vifm Executable",
        f"MULTIHARDLINK {c('hardlink')}          # vifm HardLink",
        f"SOCK {c('socket')}                    # vifm Socket",
        f"DOOR {c('socket')}",
        f"FIFO {c('fifo')}                    # vifm Fifo",
        f"BLK {c('device')}                     # vifm Device",
        f"CHR {c('device')}",
        "# permission-bit highlights (vifm has no direct analogue — keep them legible)",
        f"SETUID {c('broken', bold=True)}",
        f"SETGID {c('hardlink', bold=True)}",
        f"CAPABILITY {c('broken', bold=True)}",
        f"STICKY {c('dir', bold=True)}",
        f"OTHER_WRITABLE {c('dir')}",
        f"STICKY_OTHER_WRITABLE {c('dir')}",
        "",
        "# --- extension layer (restrained, wildcharm hues) ------------------------------",
        "# vifm shows regular files in the plain fg, so this is a deliberate enhancement on",
        "# top of the vifm-matched types — delete this block for exact `ls`==vifm parity.",
    ]
    for title, key, suffixes in exts:
        lines.append(f"# {title}")
        lines += [f"{s} {c(key)}" for s in suffixes]
    lines.append("")
    return "\n".join(lines)


GLOW_CHROMA = [
    # (chroma key, syntax role or None, extra style dict)
    ("text", "text", {}),
    ("error", "PAIRED", {}),
    ("comment", "comment", {"italic": True}),
    ("comment_preproc", "preproc", {}),
    ("keyword", "keyword", {}),
    ("keyword_reserved", "keyword", {}),
    ("keyword_namespace", "preproc", {}),
    ("keyword_type", "type", {}),
    ("operator", "keyword", {}),
    ("punctuation", "text", {}),
    ("name", "text", {}),
    ("name_builtin", "identifier", {}),
    ("name_tag", "keyword", {}),
    ("name_attribute", "type", {}),
    ("name_class", "type", {}),
    ("name_constant", "constant", {}),
    ("name_decorator", "preproc", {}),
    ("name_function", "identifier", {}),
    ("literal_number", "constant", {}),
    ("literal_string", "string", {}),
    ("literal_string_escape", "string_special", {}),
    ("generic_deleted", "diff_delete", {}),
    ("generic_emph", None, {"italic": True}),
    ("generic_inserted", "diff_add", {}),
    ("generic_strong", None, {"bold": True}),
    ("generic_subheading", "comment", {}),
]


def render_glow(variant: str) -> str:
    c = VARIANTS[variant]
    r = vroles(variant)
    acc, accfg, link, dim = r["accent"], r["accent_fg"], c["link"], r["dim"]
    chroma = {}
    for key, role, style in GLOW_CHROMA:
        entry = {}
        if role == "PAIRED":
            entry = {"color": c["error_fg"], "background_color": c["error_bg"]}
        elif role:
            entry["color"] = c[role]
        for k, v in style.items():
            entry[k] = v
        chroma[key] = entry
    chroma["background"] = {"background_color": r["surface"]}
    doc = {
        "_provenance": PROVENANCE,
        "document": {"block_prefix": "", "block_suffix": "", "color": c["text"], "margin": 2},
        "block_quote": {"color": dim, "indent": 1, "indent_token": "│ "},
        "paragraph": {},
        "list": {"level_indent": 2},
        "heading": {"block_suffix": "\n", "color": acc, "bold": True},
        "h1": {"prefix": " ", "suffix": " ", "color": accfg, "background_color": acc, "bold": True},
        "h2": {"prefix": "## ", "color": acc, "bold": True},
        "h3": {"prefix": "### ", "color": link, "bold": True},
        "h4": {"prefix": "#### ", "color": link, "bold": True},
        "h5": {"prefix": "##### ", "color": link, "bold": True},
        "h6": {"prefix": "###### ", "color": link},
        "text": {},
        "strikethrough": {"crossed_out": True},
        "emph": {"italic": True},
        "strong": {"bold": True},
        "hr": {"color": acc, "format": "\n────────\n"},
        "item": {"block_prefix": "• "},
        "enumeration": {"block_prefix": ". "},
        "task": {"ticked": "[✓] ", "unticked": "[ ] "},
        "link": {"color": link, "underline": True},
        "link_text": {"color": link, "bold": True},
        "image": {"color": link, "underline": True},
        "image_text": {"color": dim, "format": "Image: {{.text}} →"},
        "code": {"prefix": " ", "suffix": " ", "color": link, "background_color": r["surface"]},
        "code_block": {"color": c["text"], "margin": 2, "chroma": chroma},
        "table": {"center_separator": "┼", "column_separator": "│", "row_separator": "─"},
        "definition_list": {},
        "definition_term": {},
        "definition_description": {"block_prefix": "\n🠶 "},
        "html_block": {},
        "html_span": {},
    }
    return json.dumps(doc, indent=2, ensure_ascii=False) + "\n"


def _ld(light_val: str, dark_val: str) -> str:
    """CSS light-dark(), collapsed when both variants agree. Thunderbird follows
    the portal color-scheme (the sway theme fragment's gsettings exec), so ONE
    file with light-dark() covers both theme_variants — no pair + symlink."""
    if light_val == dark_val:
        return light_val
    return f"light-dark({light_val}, {dark_val})"


def render_thunderbird(kind: str) -> str:
    """userChrome.css / userContent.css — Thunderbird 140 (Supernova) accent.

    The GTK theme only reaches native GTK widgets (context menus, file
    chooser); the main window is Gecko-rendered from THREE separate variable
    chains, all blue by default (traced in omni.ja, 2026-07):
      1. --selected-item-color: var(--sidebar-highlight-background-color,
         AccentColor) in messenger's variables.css — selection, primary
         buttons, focus rings, spaces toolbar all derive from it. AccentColor
         itself ignores the GTK3 theme (widget.gtk.libadwaita-colors, user.js).
      2. hardcoded blues that derive from nothing: --primary (#0a84ff),
         --color-primary-{soft,default,hover,pressed} (account hub),
         --color-text-highlight, --button-link-text-color.
      3. the toolkit design-system token --color-accent-primary
         (tokens-brand.css) — about:preferences never loads messenger's
         variables.css; its checkboxes/radios paint from the CSS accent-color
         property, set from that token.
    userChrome targets * (not :root): unified-toolbar tabs are custom elements
    whose shadow-root stylesheets re-declare vars on :host, beating anything
    inherited from :root — but a user-origin !important declared ON the host
    element (which * matches) wins across the shadow boundary."""
    d, l = ROLES, LIGHT["roles"]
    acc = _ld(l["accent"], d["accent"])            # fill — variant-invariant
    accfg = _ld(l["accent_fg"], d["accent_fg"])
    accdark = _ld(l["accent_dark"], d["accent_dark"])
    link = _ld(l["accent"], d["link"])             # accent-as-TEXT (light has no link role)
    hover = _ld(l["accent_dark"], d["accent"])     # hover ramp: darken on light, lift on dark
    tok_hover = _ld(l["accent_dark"], d["link"])
    soft = _ld(LEXT["heading_bg"], EXT["heading_bg"])  # accent-tinted wash
    if kind == "chrome":
        return f"""/* {PROVENANCE}
   Thunderbird chrome accent (see render_thunderbird's docstring for the three
   variable chains + the shadow-DOM reason the selector is *, not :root).
   Deployed by the dotfiles role into each profile's chrome/ dir; needs
   toolkit.legacyUserProfileCustomizations.stylesheets=true (user.js). */

* {{
  --selected-item-color: {acc} !important;
  --selected-item-text-color: {accfg} !important;
  --sidebar-highlight-background-color: {acc} !important;
  --sidebar-highlight-text-color: {accfg} !important;
  --primary: {acc} !important;
  --tabline-color: {acc} !important;
  --lwt-tab-line-color: {acc} !important;
  --color-primary-default: {link} !important;
  --color-primary-hover: {hover} !important;
  --color-primary-pressed: {accdark} !important;
  --color-primary-soft: {soft} !important;
  --color-text-highlight: {link} !important;
  --button-link-text-color: {link} !important;
  /* toolkit design-system tokens (chrome dialogs) */
  --color-accent-primary: {acc} !important;
  --color-accent-primary-hover: {tok_hover} !important;
  --color-accent-primary-active: {accdark} !important;
}}
"""
    return f"""/* {PROVENANCE}
   Thunderbird content accent — the Settings tab and other about: pages are
   content documents (they load the toolkit tokens, not messenger's
   variables.css); form controls (checkboxes/radios/toggles) paint from the
   CSS accent-color property. Also applies to rendered HTML mail — a form in
   an email gets the accent too (uniform, accepted). */

:root {{
  accent-color: {acc} !important;
  --color-accent-primary: {acc} !important;
  --color-accent-primary-hover: {tok_hover} !important;
  --color-accent-primary-active: {accdark} !important;
  --link-color: {link} !important;
  --link-color-hover: {hover} !important;
  --selected-item-color: {acc} !important;
  --selected-item-text-color: {accfg} !important;
  --color-primary-default: {link} !important;
  --color-primary-hover: {hover} !important;
  --color-primary-pressed: {accdark} !important;
  --color-primary-soft: {soft} !important;
}}
"""


def render_yazi(variant: str) -> str:
    """theme.toml — yazi 26.x ([mgr]/[tabs]/[indicator] key era). Only the keys
    we restyle are emitted — yazi deep-merges the user theme over its embedded
    defaults, so omitted sections ([icon], separators, …) keep upstream values.
    File-type rules mirror filetype_colors(), so yazi agrees with ls + vifm by
    construction; code previews reuse bat's DEPLOYED wildcharm.tmTheme via
    syntect_theme (the variant symlink, so it follows theme_variant too)."""
    r, a, e = vroles(variant), vansi(variant), vext(variant)
    ft = filetype_colors(variant)
    acc, accfg, accd = r["accent"], r["accent_fg"], r["accent_dark"]
    # the hestia TUI cursor bar — the exact vifm CurrLine / cmus selection pair
    if variant == "dark":
        bar_bg, bar_fg = e["ui_grey"], e["ink"]
    else:
        bar_bg, bar_fg = e["ui_dark"], r["accent_fg"]

    def st(**kw):  # an inline TOML style table: fg/bg hex strings, flag attrs
        parts = []
        for k, v in kw.items():
            parts.append(f'{k} = true' if v is True else f'{k} = "{v}"')
        return "{ " + ", ".join(parts) + " }"

    archive_mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}"
    return f"""# {PROVENANCE}
# yazi theme — wildcharm {variant} (theme-dark/theme-light pair; the bootstrap
# symlinks the `theme_variant` one to ~/.config/yazi/theme.toml). Partial on
# purpose: yazi merges this over its embedded defaults.

[mgr]
cwd = {st(fg=acc, bold=True)}
find_keyword = {st(fg=e["ink"], bg=a["bright_yellow"], bold=True)}
find_position = {st(fg=a["bright_magenta"], bold=True)}
marker_copied = {st(fg=a["green"], bg=a["green"])}
marker_cut = {st(fg=a["bright_red"], bg=a["bright_red"])}
marker_marked = {st(fg=a["blue"], bg=a["blue"])}
marker_selected = {st(fg=acc, bg=acc)}
count_copied = {st(fg=accfg, bg=a["green"])}
count_cut = {st(fg=e["ink"], bg=a["bright_red"])}
count_selected = {st(fg=accfg, bg=acc)}
border_style = {st(fg=r["border"])}
syntect_theme = "~/.config/bat/themes/wildcharm.tmTheme"

[indicator]
parent = {st(fg=bar_fg, bg=bar_bg)}
current = {st(fg=bar_fg, bg=bar_bg, bold=True)}

[tabs]
active = {st(fg=accfg, bg=acc, bold=True)}
inactive = {st(fg=r["muted"], bg=r["surface"])}

[mode]
normal_main = {st(fg=accfg, bg=acc, bold=True)}
normal_alt = {st(fg=acc, bg=r["surface"])}
select_main = {st(fg=accfg, bg=a["blue"], bold=True)}
select_alt = {st(fg=a["blue"], bg=r["surface"])}
unset_main = {st(fg=e["ink"], bg=a["bright_yellow"], bold=True)}
unset_alt = {st(fg=a["bright_yellow"], bg=r["surface"])}

[status]
perm_sep = {st(fg=r["dim"])}
perm_type = {st(fg=a["green"])}
perm_read = {st(fg=a["yellow"])}
perm_write = {st(fg=acc)}
perm_exec = {st(fg=a["cyan"])}
progress_label = {st(bold=True)}
progress_normal = {st(fg=acc, bg=r["surface"])}
progress_error = {st(fg=accfg, bg=accd)}

[which]
mask = {st(bg=r["bg"])}
cand = {st(fg=a["bright_cyan"])}
rest = {st(fg=r["dim"])}
desc = {st(fg=e["purple"])}
separator_style = {st(fg=r["dim"])}

[confirm]
border = {st(fg=acc)}
title = {st(fg=acc, bold=True)}
btn_yes = {st(fg=accfg, bg=acc)}

[spot]
border = {st(fg=acc)}
title = {st(fg=acc, bold=True)}
tbl_col = {st(fg=acc)}
tbl_cell = {st(fg=a["bright_yellow"], reversed=True)}

[notify]
title_info = {st(fg=a["green"])}
title_warn = {st(fg=a["bright_yellow"])}
title_error = {st(fg=a["bright_red"])}

[pick]
border = {st(fg=acc)}
active = {st(fg=acc, bold=True)}

[input]
border = {st(fg=acc)}

[cmp]
border = {st(fg=acc)}

[tasks]
border = {st(fg=acc)}
hovered = {st(fg=acc, bold=True)}

[help]
on = {st(fg=a["bright_cyan"])}
run = {st(fg=a["bright_magenta"])}
desc = {st(fg=r["dim"])}
footer = {st(fg=r["bg"], bg=r["muted"])}

# File-type rules — from render.py's shared filetype_colors() table (the same
# one vifm's colorscheme and ~/.dircolors render from, so all three agree).
[filetype]
rules = [
    {st(fg=ft["images"])[:-1]}, mime = "image/*" }},
    {st(fg=ft["video"])[:-1]}, mime = "video/*" }},
    {st(fg=ft["audio"])[:-1]}, mime = "audio/*" }},
    {st(fg=ft["archives"])[:-1]}, mime = "{archive_mime}" }},
    {st(fg=ft["docs"])[:-1]}, mime = "application/{{pdf,doc,rtf}}" }},
    {st(fg=ft["broken"], crossed=True)[:-1]}, url = "*", is = "orphan" }},
    {st(fg=ft["exec"])[:-1]}, url = "*", is = "exec" }},
    {st(fg=accfg, bg=accd)[:-1]}, url = "*", is = "dummy" }},
    {st(fg=accfg, bg=accd)[:-1]}, url = "*/", is = "dummy" }},
    {st(fg=ft["dir"], bold=True)[:-1]}, url = "*/" }},
]
"""


def render_ranger(variant: str) -> str:
    """colorschemes/wildcharm.py — ranger. The context-check structure follows
    ranger's stock default.py; colours are exact xterm-256 indices resolved
    from the palette (filetype_colors() for the file classes — the same table
    as vifm/dircolors — plus the accent identity in the hostname/tabs/marks/
    progress spots). One class per variant file; the bootstrap symlinks the
    theme_variant one to colorschemes/wildcharm.py (rc.conf is variant-blind)."""
    r, a, e = vroles(variant), vansi(variant), vext(variant)
    ft = filetype_colors(variant)
    x = xterm_index
    # the hestia TUI cursor-bar fill (vifm CurrLine / the yazi indicator pair):
    # with curses `reverse`, setting fg paints the BAR, text becomes the ground
    bar = e["ui_grey"] if variant == "dark" else e["ui_dark"]
    consts = "\n".join(
        f"{name} = {x(val)}"
        for name, val in [
            ("ACCENT", r["accent"]), ("ACCENT_DARK", r["accent_dark"]),
            ("DIM", r["dim"]), ("MUTED", r["muted"]), ("BORDER", e["line_grey"]),
            ("DIR", ft["dir"]), ("EXEC", ft["exec"]), ("LINK", ft["link"]),
            ("BROKEN", ft["broken"]), ("FIFO", ft["fifo"]), ("DEVICE", ft["device"]),
            ("SOCKET", ft["socket"]), ("IMAGES", ft["images"]), ("VIDEO", ft["video"]),
            ("AUDIO", ft["audio"]), ("DOCS", ft["docs"]), ("ARCHIVES", ft["archives"]),
            ("MARKED", a["bright_yellow"]), ("GREEN", a["green"]),
            ("CYAN", a["cyan"]), ("MAGENTA", a["bright_magenta"]),
            ("BRIGHT_RED", a["bright_red"]), ("YELLOW", a["yellow"]),
            ("BAR", bar),
        ]
    )
    return f'''# {PROVENANCE}
# ranger colorscheme — wildcharm {variant} (wildcharm-dark/-light pair; the
# bootstrap symlinks the `theme_variant` one to colorschemes/wildcharm.py).
# Structure follows ranger's stock default.py; colours are xterm-256 indices
# resolved from palette.yml — the file classes from the SAME filetype_colors()
# table as vifm + dircolors, so all of them agree by construction.

from __future__ import absolute_import, division, print_function

from ranger.gui.color import bold, default, default_colors, normal, reverse
from ranger.gui.colorscheme import ColorScheme

{consts}


class Wildcharm(ColorScheme):
    progress_bar_color = ACCENT

    def use(self, context):  # noqa: C901  pylint: disable=too-many-branches,too-many-statements
        fg, bg, attr = default_colors

        if context.reset:
            return default_colors

        elif context.in_browser:
            attr = reverse if context.selected else normal
            if context.empty or context.error:
                fg, bg = {x(r["accent_fg"])}, ACCENT_DARK
            if context.border:
                fg = BORDER
            if context.media:
                fg = IMAGES if context.image else (AUDIO if context.audio else VIDEO)
            if context.document:
                fg = DOCS
            if context.container:
                fg = ARCHIVES
            if context.directory:
                attr |= bold
                fg = DIR
            elif context.executable and not any(
                    (context.media, context.container, context.fifo, context.socket)):
                attr |= bold
                fg = EXEC
            if context.socket:
                attr |= bold
                fg = SOCKET
            if context.fifo:
                fg = FIFO
            if context.device:
                attr |= bold
                fg = DEVICE
            if context.link:
                fg = LINK if context.good else BROKEN
            if context.tag_marker and not context.selected:
                attr |= bold
                fg = ACCENT
            if not context.selected and (context.cut or context.copied):
                attr |= bold
                fg = DIM
            if context.main_column:
                if context.selected:
                    attr |= bold
                if context.marked:
                    attr |= bold
                    fg = MARKED
            if context.badinfo:
                if attr & reverse:
                    bg = MAGENTA
                else:
                    fg = MAGENTA
            if context.selected:
                # the uniform hestia cursor bar (vifm CurrLine / yazi indicator)
                # instead of reverse-video over the item's own colour
                fg = BAR
            if context.inactive_pane:
                fg = MUTED

        elif context.in_titlebar:
            if context.hostname:
                fg = BRIGHT_RED if context.bad else ACCENT
            elif context.directory:
                fg = DIR
            elif context.tab:
                if context.good:
                    fg, bg = {x(r["accent_fg"])}, ACCENT
            elif context.link:
                fg = LINK
            attr |= bold

        elif context.in_statusbar:
            if context.permissions:
                fg = CYAN if context.good else BRIGHT_RED
            if context.marked:
                attr |= bold | reverse
                fg = MARKED
            if context.frozen:
                attr |= bold | reverse
                fg = CYAN
            if context.message:
                if context.bad:
                    attr |= bold
                    fg = BRIGHT_RED
            if context.loaded:
                bg = self.progress_bar_color
            if context.vcsinfo:
                fg = DIR
                attr &= ~bold
            if context.vcscommit:
                fg = YELLOW
                attr &= ~bold
            if context.vcsdate:
                fg = CYAN
                attr &= ~bold

        if context.text and context.highlight:
            attr |= reverse

        if context.in_taskview:
            if context.title:
                fg = DIR
            if context.selected:
                attr |= reverse
            if context.loaded:
                if context.selected:
                    fg = self.progress_bar_color
                else:
                    bg = self.progress_bar_color

        if context.vcsfile and not context.selected:
            attr &= ~bold
            if context.vcsconflict:
                fg = MAGENTA
            elif context.vcsuntracked:
                fg = ACCENT
            elif context.vcschanged:
                fg = ACCENT
            elif context.vcsunknown:
                fg = BRIGHT_RED
            elif context.vcsstaged:
                fg = GREEN
            elif context.vcssync:
                fg = GREEN
            elif context.vcsignored:
                fg = default
        elif context.vcsremote and not context.selected:
            attr &= ~bold
            if context.vcssync or context.vcsnone:
                fg = GREEN
            elif context.vcsbehind:
                fg = BRIGHT_RED
            elif context.vcsahead:
                fg = DIR
            elif context.vcsdiverged:
                fg = MAGENTA
            elif context.vcsunknown:
                fg = BRIGHT_RED

        return fg, bg, attr
'''


OUTPUTS = {
    REPO / "user/bat/themes/wildcharm-dark.tmTheme": lambda: render_tmtheme("dark"),
    REPO / "user/bat/themes/wildcharm-light.tmTheme": lambda: render_tmtheme("light"),
    HERE / "dist/shiki/hestia-dark.json": lambda: theme_json("dark", "shiki"),
    HERE / "dist/shiki/hestia-light.json": lambda: theme_json("light", "shiki"),
    REPO / "user/vscode/hestia/themes/hestia-dark-color-theme.json": lambda: theme_json("dark", "vscode"),
    REPO / "user/vscode/hestia/themes/hestia-light-color-theme.json": lambda: theme_json("light", "vscode"),
    REPO / "user/kitty/theme-dark.conf": lambda: render_kitty("dark"),
    REPO / "user/kitty/theme-light.conf": lambda: render_kitty("light"),
    REPO / "user/sway/theme-dark.conf": lambda: render_sway("dark"),
    REPO / "user/sway/theme-light.conf": lambda: render_sway("light"),
    REPO / "user/waybar/theme-dark.css": lambda: render_waybar_css("dark"),
    REPO / "user/waybar/theme-light.css": lambda: render_waybar_css("light"),
    REPO / "user/mako/theme-dark.conf": lambda: render_mako("dark"),
    REPO / "user/mako/theme-light.conf": lambda: render_mako("light"),
    REPO / "user/wofi/colors-dark": lambda: render_wofi_colors("dark"),
    REPO / "user/wofi/colors-light": lambda: render_wofi_colors("light"),
    REPO / "user/swaylock/config-dark": lambda: render_swaylock("dark"),
    REPO / "user/swaylock/config-light": lambda: render_swaylock("light"),
    REPO / "user/swaynag/config-dark": lambda: render_swaynag("dark"),
    REPO / "user/swaynag/config-light": lambda: render_swaynag("light"),
    REPO / "user/zathura/theme-dark": lambda: render_zathura("dark"),
    REPO / "user/zathura/theme-light": lambda: render_zathura("light"),
    REPO / "user/vifm/colors/wildcharm-dark.vifm": lambda: render_vifm("dark"),
    REPO / "user/vifm/colors/wildcharm-light.vifm": lambda: render_vifm("light"),
    REPO / "user/bash/.dircolors-dark": lambda: render_dircolors("dark"),
    REPO / "user/bash/.dircolors-light": lambda: render_dircolors("light"),
    REPO / "user/glow/wildcharm-dark.json": lambda: render_glow("dark"),
    REPO / "user/glow/wildcharm-light.json": lambda: render_glow("light"),
    # single light-dark() files, not pairs — TB follows the portal color-scheme
    REPO / "user/thunderbird/userChrome.css": lambda: render_thunderbird("chrome"),
    REPO / "user/thunderbird/userContent.css": lambda: render_thunderbird("content"),
    REPO / "user/yazi/theme-dark.toml": lambda: render_yazi("dark"),
    REPO / "user/yazi/theme-light.toml": lambda: render_yazi("light"),
    REPO / "user/ranger/colorschemes/wildcharm-dark.py": lambda: render_ranger("dark"),
    REPO / "user/ranger/colorschemes/wildcharm-light.py": lambda: render_ranger("light"),
}


def main() -> None:
    aa_gate()
    check = "--check" in sys.argv
    drift = []
    for path, renderer in OUTPUTS.items():
        content = renderer()
        rel = path.relative_to(REPO)
        if check:
            if not path.exists() or path.read_text() != content:
                drift.append(str(rel))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
            print(f"rendered {rel}")
    if check:
        if drift:
            sys.exit("STALE (re-run render.py):\n  " + "\n  ".join(drift))
        print(f"check ok — all {len(OUTPUTS)} artifacts match palette v{VERSION}")


if __name__ == "__main__":
    main()
