#!/usr/bin/env python3
"""render.py — generate the theme artifacts from the palette.

Layer 3 of the theme pipeline (docs/theme-roadmap.md): reads palette.yml
(colours, per variant) + scopes.yml (the shared role→scope map) and renders

TextMate family (syntax + chrome):
  user/bat/themes/wildcharm.tmTheme                      (dark; terminal chrome)
  themes/wildcharm/dist/shiki/hestia-{dark,light}.json   (web code blocks;
                                                          bg = the code SURFACE)
  user/vscode/hestia/themes/hestia-{dark,light}-color-theme.json
                                                         (editor; bg = the app
                                                          CANVAS + UI chrome)

Desktop chrome, both variants each (roles/ANSI only — no scopes; the bootstrap
symlinks the one `theme_variant` selects to a variant-neutral dest, M7):
  fragments   kitty/sway/mako theme-*.conf, waybar/wofi theme-*.css,
              zathura theme-* (include'd/@import'ed by the main configs)
  whole-file  swaylock/swaynag config-* (no include support)
  theme pairs vifm wildcharm-*.vifm, bat wildcharm-*.tmTheme (TM family),
              glow wildcharm-*.json, bash .dircolors-* (ls file colours —
              generated from the SAME table as vifm so they cannot drift)

Same tokenColors everywhere; only the per-target chrome differs. The WCAG AA
contrast gate runs before anything is written — a palette edit that breaks a
plain-text role fails the render (reverse/fill roles are exempt; they are
checked as pairings by eye).

Usage:  render.py            render all artifacts in place
        render.py --check    exit 1 if any committed artifact differs from a
                             fresh render (use before/in review)

Never edit the generated files by hand — scope decisions go in scopes.yml,
colours in palette.yml, chrome maps below.
"""

import json
import sys
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent

PALETTE = yaml.safe_load((HERE / "palette.yml").read_text())
SCOPES = yaml.safe_load((HERE / "scopes.yml").read_text())["rules"]
VERSION = PALETTE["version"]
PROVENANCE = (
    f"GENERATED by themes/wildcharm/render.py from palette.yml v{VERSION} "
    f"+ scopes.yml — do not edit; edit the sources and re-render"
)

ROLES = PALETTE["roles"]
ANSI = PALETTE["ansi"]
LIGHT = PALETTE["light"]

# role → colour, per variant. `link` on light is the accent (it clears AA as
# text on white — decision log); error is the paired fill role.
VARIANTS = {
    "dark": {
        **PALETTE["syntax"],
        "text": ROLES["text"],
        "link": ROLES["link"],
        "error_fg": "#ffffff",
        "error_bg": ROLES["accent_dark"],
        # surfaces the plain-text roles must clear AA against. Since 0.5.0 the
        # web code surface IS the ground (it reads raised on tci's darker
        # page); surface_alt is transient (hover/line-highlight), not a body-
        # text surface, so it is deliberately NOT gated here.
        "_aa_surfaces": [ROLES["bg"]],
        # per-target canvas/surface
        "_canvas": ROLES["bg"],          # vim/bat/VS Code app canvas
        "_code_surface": ROLES["bg"],    # web code blocks == the ground
    },
    "light": {
        **LIGHT["syntax"],
        "text": LIGHT["roles"]["text"],
        "link": LIGHT["roles"]["accent"],
        "error_fg": "#ffffff",
        "error_bg": LIGHT["syntax"]["error"],
        # the light gate runs against the #f5f5f5 DESKTOP ground (M7) — stricter
        # than the #ffffff code surface, so white is covered by implication
        "_aa_surfaces": [LIGHT["roles"]["bg"]],
        "_canvas": LIGHT["roles"]["bg"],
        # the web code surface keeps the M3 pure white (light-only split;
        # dark's code surface == the ground)
        "_code_surface": LIGHT["roles"]["code_surface"],
    },
}

# per-variant role/ANSI tables for the desktop-chrome emitters
def vroles(variant: str) -> dict:
    return ROLES if variant == "dark" else LIGHT["roles"]


def vansi(variant: str) -> dict:
    return ANSI if variant == "dark" else LIGHT["ansi"]

FILL_ROLES = {"error", "todo"}  # reverse/fill — exempt from the plain-text gate


def _lum(hexval: str) -> float:
    h = hexval.lstrip("#")
    c = [int(h[i : i + 2], 16) / 255 for i in (0, 2, 4)]
    c = [x / 12.92 if x <= 0.04045 else ((x + 0.055) / 1.055) ** 2.4 for x in c]
    return 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2]


def contrast(a: str, b: str) -> float:
    la, lb = sorted((_lum(a), _lum(b)), reverse=True)
    return (la + 0.05) / (lb + 0.05)


def aa_gate() -> None:
    failures = []
    for variant, colors in VARIANTS.items():
        for role, hexval in colors.items():
            if role.startswith("_") or role in FILL_ROLES or role.startswith("error"):
                continue
            for surface in colors["_aa_surfaces"]:
                r = contrast(hexval, surface)
                if r < 4.5:
                    failures.append(f"{variant}.{role} {hexval} on {surface}: {r:.2f}:1")
    if failures:
        sys.exit("AA contrast gate FAILED:\n  " + "\n  ".join(failures))


def token_colors(colors: dict) -> list:
    out = []
    for rule in SCOPES:
        settings = {}
        role = rule.get("role")
        if rule.get("paired"):
            settings["foreground"] = colors["error_fg"]
            settings["background"] = colors["error_bg"]
        elif role:
            settings["foreground"] = colors[role]
        if rule.get("font_style"):
            settings["fontStyle"] = rule["font_style"]
        out.append({"name": rule["name"], "scope": rule["scopes"], "settings": settings})
    return out


# ---------------------------------------------------------------- tmTheme (bat)

def render_tmtheme(variant: str = "dark") -> str:
    c = VARIANTS[variant]
    r = vroles(variant)
    chrome = {
        "background": c["_canvas"],
        "foreground": c["text"],
        "caret": r["accent"],
        "lineHighlight": r["surface_alt"],
        "selection": r["border"],
        "invisibles": r["dim"],
        "guide": r["border"],
        "activeGuide": r["dim"],
        "gutterForeground": r["dim"],
    }
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
        f"<!-- {PROVENANCE} -->",
        '<plist version="1.0">',
        "<dict>",
        "  <key>name</key>",
        "  <string>wildcharm</string>",
        "  <key>settings</key>",
        "  <array>",
        "",
        "    <dict>",
        "      <key>settings</key>",
        "      <dict>",
    ]
    for k, v in chrome.items():
        lines.append(f"        <key>{k}</key> <string>{v}</string>")
    lines += ["      </dict>", "    </dict>"]
    for tc in token_colors(c):
        lines += [
            "",
            "    <dict>",
            f"      <key>name</key><string>{tc['name']}</string>",
            f"      <key>scope</key><string>{', '.join(tc['scope'])}</string>",
            "      <key>settings</key>",
            "      <dict>",
        ]
        for k, v in tc["settings"].items():
            lines.append(f"        <key>{k}</key><string>{v}</string>")
        lines += ["      </dict>", "    </dict>"]
    lines += ["", "  </array>", "</dict>", "</plist>", ""]
    return "\n".join(lines)


# ------------------------------------------------------------------ theme JSON

def theme_json(variant: str, target: str) -> str:
    c = VARIANTS[variant]
    if target == "shiki":
        colors = {
            "editor.background": c["_code_surface"],
            "editor.foreground": c["text"],
        }
    else:  # vscode — full UI chrome from the variant's roles + ANSI (since M7
        # PR2 light mirrors dark's chrome key-for-key; before that light shipped
        # minimal chrome and fell back to VS Code's stock light UI)
        r, a = vroles(variant), vansi(variant)
        acc, accfg = r["accent"], r["accent_fg"]
        colors = {
            "focusBorder": acc,
            "foreground": c["text"],
            # links in UI text (chat/welcome/notifications) + ctrl-hover links
            # in the editor — default to VS Code blue unless mapped
            "textLink.foreground": c["link"],
            "textLink.activeForeground": c["link"],
            "editorLink.activeForeground": c["link"],
            "editor.background": c["_canvas"],
            "editor.foreground": c["text"],
            "editor.lineHighlightBackground": r["surface_alt"],
            "editor.selectionBackground": r["border"],
            "editorCursor.foreground": acc,
            "editorLineNumber.foreground": r["dim"],
            "editorLineNumber.activeForeground": c["text"],
            "editorIndentGuide.background1": r["border"],
            "editorIndentGuide.activeBackground1": r["dim"],
            "editorWhitespace.foreground": r["border"],
            "sideBar.background": r["surface"],
            "sideBar.foreground": r["muted"],
            "sideBar.border": r["border"],
            "sideBarTitle.foreground": c["text"],
            "activityBar.background": c["_canvas"],
            "activityBar.foreground": c["text"],
            "activityBar.inactiveForeground": r["dim"],
            "activityBarBadge.background": acc,
            "activityBarBadge.foreground": accfg,
            "statusBar.background": acc,
            "statusBar.foreground": accfg,
            "statusBar.noFolderBackground": r["accent_dark"],
            "statusBar.debuggingBackground": r["accent_dark"],
            "titleBar.activeBackground": r["surface"],
            "titleBar.activeForeground": c["text"],
            "titleBar.inactiveBackground": c["_canvas"],
            "titleBar.inactiveForeground": r["dim"],
            "tab.activeBackground": c["_canvas"],
            "tab.activeForeground": c["text"],
            "tab.activeBorderTop": acc,
            "tab.inactiveBackground": r["surface"],
            "tab.inactiveForeground": r["dim"],
            "editorGroupHeader.tabsBackground": r["surface"],
            "panel.background": c["_canvas"],
            "panel.border": r["border"],
            "input.background": r["surface"],
            "input.foreground": c["text"],
            "input.border": r["border"],
            "dropdown.background": r["surface"],
            "dropdown.foreground": c["text"],
            "button.background": acc,
            "button.foreground": accfg,
            "badge.background": acc,
            "badge.foreground": accfg,
            "list.activeSelectionBackground": acc,
            "list.activeSelectionForeground": accfg,
            "list.inactiveSelectionBackground": r["surface_alt"],
            "list.hoverBackground": r["surface_alt"],
            "scrollbarSlider.background": r["border"],
            "scrollbarSlider.hoverBackground": r["dim"],
            # semantic info/warning/error — same meanings the terminal tools
            # use (buildkit run-blue, git/zathura warning-yellow, vifm
            # ErrorMsg bright-red); covers notification toasts, editor
            # squiggles and the Problems panel
            "notifications.background": r["surface"],
            "notifications.foreground": c["text"],
            "notifications.border": r["border"],
            "notificationCenterHeader.background": r["surface_alt"],
            "notificationsInfoIcon.foreground": a["blue"],
            "notificationsWarningIcon.foreground": a["yellow"],
            "notificationsErrorIcon.foreground": a["bright_red"],
            "editorInfo.foreground": a["blue"],
            "editorWarning.foreground": a["yellow"],
            "editorError.foreground": a["bright_red"],
            "terminal.background": c["_canvas"],
            "terminal.foreground": c["text"],
            "terminalCursor.foreground": acc,
            "terminal.ansiBlack": a["black"],
            "terminal.ansiRed": a["red"],
            "terminal.ansiGreen": a["green"],
            "terminal.ansiYellow": a["yellow"],
            "terminal.ansiBlue": a["blue"],
            "terminal.ansiMagenta": a["magenta"],
            "terminal.ansiCyan": a["cyan"],
            "terminal.ansiWhite": a["white"],
            "terminal.ansiBrightBlack": a["bright_black"],
            "terminal.ansiBrightRed": a["bright_red"],
            "terminal.ansiBrightGreen": a["bright_green"],
            "terminal.ansiBrightYellow": a["bright_yellow"],
            "terminal.ansiBrightBlue": a["bright_blue"],
            "terminal.ansiBrightMagenta": a["bright_magenta"],
            "terminal.ansiBrightCyan": a["bright_cyan"],
            "terminal.ansiBrightWhite": a["bright_white"],
        }
    doc = {
        "_provenance": PROVENANCE,
        "name": f"hestia-{variant}",
        "type": variant,
        "colors": colors,
        "tokenColors": token_colors(c),
    }
    return json.dumps(doc, indent=2, ensure_ascii=False) + "\n"


# ------------------------------------------------- desktop chrome (M7 switch)
# Per-app colour fragments, both variants; the bootstrap manifest symlinks the
# `theme_variant` one to a variant-neutral destination (theme.conf / theme.css).
# Roles/ANSI only — no syntax scopes. Mappings live here (platform-quirk rule).

def render_kitty(variant: str) -> str:
    r, a = vroles(variant), vansi(variant)
    slots = [
        "black", "red", "green", "yellow", "blue", "magenta", "cyan", "white",
        "bright_black", "bright_red", "bright_green", "bright_yellow",
        "bright_blue", "bright_magenta", "bright_cyan", "bright_white",
    ]
    lines = [f"# {PROVENANCE}", f"# kitty colours — {variant} (see kitty.conf: include theme.conf)", ""]
    if variant == "dark":
        lines += ["# Note: bg == ANSI color0 — accepted; watch item in the roadmap backlog.", ""]
    lines += [
        f"background            {r['bg']}",
        f"foreground            {r['text']}",
        f"cursor                {r['accent']}",
        f"cursor_text_color     {r['accent_fg']}",
        f"selection_background  {r['accent']}",
        f"selection_foreground  {r['accent_fg']}",
        "",
    ]
    for i, slot in enumerate(slots):
        lines.append(f"color{i:<2} {a[slot]}")
    lines += [
        "",
        f"active_tab_background   {r['accent']}",
        f"active_tab_foreground   {r['accent_fg']}",
        f"inactive_tab_background {r['surface']}",
        f"inactive_tab_foreground {r['dim']}",
        f"tab_bar_background      {r['bg']}",
        "",
        "# Split borders (kitty's default active is green) — quiet greys",
        f"active_border_color   {r['surface']}",
        f"inactive_border_color {r['border']}",
        "",
    ]
    return "\n".join(lines)


def render_sway(variant: str) -> str:
    r = vroles(variant)
    scheme = "prefer-dark" if variant == "dark" else "prefer-light"
    gtk_theme = "hestia-dark" if variant == "dark" else "hestia"
    return f"""# {PROVENANCE}
# sway theme fragment — {variant} (see config: include ~/.config/sway/theme.conf)

# Colors (roles from palette.yml)
set $bg        {r["bg"]}
set $surface   {r["surface"]}
set $border    {r["border"]}
set $text      {r["text"]}
set $dim       {r["dim"]}
set $accent    {r["accent"]}
set $accent_fg {r["accent_fg"]}

# Desktop background
output * bg {r["bg"]} solid_color

# GTK / portal appearance for this variant (CLAUDE.md GTK section): color-scheme
# is what Firefox/portal-aware/libadwaita apps follow; gtk-theme is what the
# portal file chooser reads (in-process GTK3 apps follow start-sway's GTK_THEME).
# `exec` runs at login only — not re-run on `swaymsg reload`.
exec gsettings set org.gnome.desktop.interface color-scheme {scheme}
exec gsettings set org.gnome.desktop.interface gtk-theme {gtk_theme}
# Icon theme: the #d7005f-accent Yaru built by the opt-in yaru_icons role
# (Yaru-hestia). Guard on the theme actually existing so a spin without that
# role doesn't force a missing theme.
exec sh -c 'test -d "$HOME/.local/share/icons/Yaru-hestia" && gsettings set org.gnome.desktop.interface icon-theme Yaru-hestia'
"""


def render_waybar_css(variant: str) -> str:
    r, a = vroles(variant), vansi(variant)
    tokens = {
        "bg": r["bg"],
        "text": r["text"],
        "muted": r["muted"],
        "border": r["border"],
        "surface_alt": r["surface_alt"],
        "accent": r["accent"],
        "accent_fg": r["accent_fg"],
        # muted-state icons (pulseaudio.muted) — ANSI bright_black, the
        # quietest grey that still reads on the bar
        "icon_muted": a["bright_black"],
    }
    lines = [f"/* {PROVENANCE}",
             f"   waybar colour tokens — {variant} (style.css: @import \"theme.css\") */", ""]
    lines += [f"@define-color {k} {v};" for k, v in tokens.items()]
    lines.append("")
    return "\n".join(lines)


# ----------------------------------------------- xterm-256 index (vifm cterm)

_CUBE = [0, 95, 135, 175, 215, 255]


def xterm_index(hexval: str) -> int:
    """Nearest xterm-256 index (16-255). Palette values are xterm-native except
    the two grounds (#1a1a1a -> 234, #f5f5f5 -> 255) — nearest steps, matching
    the cterm fallbacks hestia.vim uses."""
    h = hexval.lstrip("#")
    r, g, b = (int(h[i : i + 2], 16) for i in (0, 2, 4))
    best, best_d = 16, 3 * 255 ** 2 + 1
    for ri, rv in enumerate(_CUBE):
        for gi, gv in enumerate(_CUBE):
            for bi, bv in enumerate(_CUBE):
                d = (r - rv) ** 2 + (g - gv) ** 2 + (b - bv) ** 2
                if d < best_d:
                    best, best_d = 16 + 36 * ri + 6 * gi + bi, d
    for i in range(24):
        v = 8 + 10 * i
        d = (r - v) ** 2 + (g - v) ** 2 + (b - v) ** 2
        if d < best_d:
            best, best_d = 232 + i, d
    return best


# ------------------------------------------- desktop chrome, the long tail (M7)

EXT = PALETTE["extended"]
LEXT = LIGHT["extended"]


def vext(variant: str) -> dict:
    # light falls back to the shared extended for variant-invariant values (ink)
    return EXT if variant == "dark" else {**EXT, **LEXT}


def _css_tokens(variant: str, tokens: dict, note: str) -> str:
    lines = [f"/* {PROVENANCE}", f"   {note} */", ""]
    lines += [f"@define-color {k} {v};" for k, v in tokens.items()]
    lines.append("")
    return "\n".join(lines)


def render_mako(variant: str) -> str:
    r, e = vroles(variant), vext(variant)
    return f"""# {PROVENANCE}
# mako colours — {variant}. Included LAST by ~/.config/mako/config so the
# [urgency=high] section below can't swallow main-config keys. default-timeout=0
# rides with the section (criteria keys must stay inside it): urgent sticks.

background-color={r["bg"]}
text-color={r["text"]}
border-color={r["accent"]}

[urgency=high]
background-color={r["accent"]}
border-color={r["accent_dark"]}
text-color={r["accent_fg"]}
default-timeout=0
"""


def render_wofi_css(variant: str) -> str:
    r = vroles(variant)
    return _css_tokens(variant, {
        "bg": r["bg"],
        "text": r["text"],
        "muted": r["muted"],
        "border": r["border"],
        "surface": r["surface"],
        "accent": r["accent"],
        "accent_fg": r["accent_fg"],
    }, f'wofi colour tokens — {variant} (style.css: @import "theme.css")')


def render_swaylock(variant: str) -> str:
    r, a, e = vroles(variant), vansi(variant), vext(variant)
    def b(h):  # swaylock wants bare RRGGBB
        return h.lstrip("#")
    return f"""# {PROVENANCE}
# swaylock — wildcharm lockscreen, {variant} (config-dark / config-light pair;
# the bootstrap symlinks the `theme_variant` one to ~/.config/swaylock/config).
#
# IMPORTANT: swaylock's config parser only supports WHOLE-LINE `#` comments — it
# does NOT strip trailing/inline comments. Keep every annotation on its own line;
# values are bare RRGGBB (no leading '#').
#
# Sway invokes `swaylock -f` (no -c flag), so `color` below is the single source
# for the lock background. `indicator-idle-visible` keeps the ring on when idle.

color={b(r["bg"])}
font=Lilex Nerd Font Mono
indicator-radius=110
indicator-thickness=8
indicator-idle-visible
indicator-caps-lock
show-failed-attempts

# idle (no input): inside=sunken, ring=border, line/separator=bg, text=text
inside-color={b(e["sunken"])}
ring-color={b(r["border"])}
line-color={b(r["bg"])}
separator-color={b(r["bg"])}
text-color={b(r["text"])}

# typing: key highlight = accent, backspace = bright_red
key-hl-color={b(r["accent"])}
bs-hl-color={b(a["bright_red"])}

# verifying (checking password): ring = blue
inside-ver-color={b(e["sunken"])}
ring-ver-color={b(a["blue"])}
line-ver-color={b(r["bg"])}
text-ver-color={b(r["text"])}

# wrong password: ring = bright_red, inside = accent_dark, text = accent_fg
inside-wrong-color={b(r["accent_dark"])}
ring-wrong-color={b(a["bright_red"])}
line-wrong-color={b(r["bg"])}
text-wrong-color={b(r["accent_fg"])}

# cleared (input wiped): ring = accent
inside-clear-color={b(e["sunken"])}
ring-clear-color={b(r["accent"])}
line-clear-color={b(r["bg"])}
text-clear-color={b(r["text"])}

# caps lock on: ring + highlight = bright_yellow (warning), backspace = bright_red
inside-caps-lock-color={b(e["sunken"])}
ring-caps-lock-color={b(a["bright_yellow"])}
caps-lock-key-hl-color={b(a["bright_yellow"])}
caps-lock-bs-hl-color={b(a["bright_red"])}
text-caps-lock-color={b(r["text"])}
"""


def render_swaynag(variant: str) -> str:
    r, a, e = vroles(variant), vansi(variant), vext(variant)
    def b(h):
        return h.lstrip("#")
    sections = [
        ("global / default (dialogs with no -t)", None, r["accent"]),
        ("warning (the sway exit confirm passes -t warning): yellow accent line", "warning", a["bright_yellow"]),
        ("error: bright-red accent line", "error", a["bright_red"]),
    ]
    out = [f"# {PROVENANCE}",
           f"# swaynag — wildcharm dialogs, {variant} (config-dark / config-light pair; the",
           "# bootstrap symlinks the `theme_variant` one to ~/.config/swaynag/config).",
           "# Values are bare RRGGBB (no '#'); annotations on their own lines.",
           "#",
           "# GOTCHA: swaynag's built-in `warning`/`error` types ship hardcoded colours and",
           "# do NOT layer the global options — only keys set INSIDE a type's [section]",
           "# override its presets, so the theme is restated in full per section.",
           ""]
    for title, section, accent_line in sections:
        out.append(f"# --- {title} ---")
        if section:
            out.append(f"[{section}]")
        else:
            out.append("font=Lilex Nerd Font Mono 11")
        out += [
            f"background={b(r['bg'])}",
            f"border={b(r['border'])}",
            f"border-bottom={b(accent_line)}",
            "border-bottom-size=2",
            f"text={b(r['text'])}",
            f"button-background={b(e['sunken'])}",
            f"button-text={b(r['text'])}",
            f"details-background={b(e['sunken'])}",
            "",
        ]
    return "\n".join(out)


def render_zathura(variant: str) -> str:
    r, a = vroles(variant), vansi(variant)
    def rgba(h, alpha):
        v = h.lstrip("#")
        rr, gg, bb = (int(v[i : i + 2], 16) for i in (0, 2, 4))
        return f'"rgba({rr}, {gg}, {bb}, {alpha})"'
    # warning fill takes contrast text: the dark ground on dark's yellow, white
    # on light's darker yellow
    warn_fg = r["bg"] if variant == "dark" else r["accent_fg"]
    # recolour is a dark-mode feature: on by default on dark (white pages ->
    # ground), OFF on light (pages are already light); `r` toggles either way,
    # so both variants carry sensible recolor-* values.
    recolor = "true" if variant == "dark" else "false"
    return f"""# {PROVENANCE}
# zathura colours — {variant} (theme-dark / theme-light pair; the bootstrap
# symlinks the `theme_variant` one to ~/.config/zathura/theme, `include`d by
# zathurarc). zathura takes "#RRGGBB" (+ rgba(...) for translucent highlights).

# --- window / page area ---
set default-bg          "{r["bg"]}"
set default-fg          "{r["text"]}"
set render-loading-bg   "{r["bg"]}"
set render-loading-fg   "{r["text"]}"

# --- statusbar (bottom bar) ---
set statusbar-bg        "{r["surface"]}"
set statusbar-fg        "{r["text"]}"

# --- inputbar (the ':' command line) ---
set inputbar-bg         "{r["surface"]}"
set inputbar-fg         "{r["text"]}"

# --- notifications (info / warning / error) ---
set notification-bg         "{r["surface"]}"
set notification-fg         "{r["text"]}"
set notification-warning-bg "{a["yellow"]}"
set notification-warning-fg "{warn_fg}"
set notification-error-bg   "{r["accent_dark"]}"
set notification-error-fg   "{r["accent_fg"]}"

# --- search highlights (translucent so the text shows through) ---
# all matches = blue; the active/focused match = accent
set highlight-color        {rgba(a["blue"], "0.35")}
set highlight-active-color {rgba(r["accent"], "0.5")}

# --- completion menu (Tab) ---
set completion-bg           "{r["surface"]}"
set completion-fg           "{r["text"]}"
set completion-group-bg     "{r["bg"]}"
set completion-group-fg     "{r["accent"]}"
set completion-highlight-bg "{r["accent"]}"
set completion-highlight-fg "{r["accent_fg"]}"

# --- index / table of contents ---
set index-bg        "{r["bg"]}"
set index-fg        "{r["text"]}"
set index-active-bg "{r["accent"]}"
set index-active-fg "{r["accent_fg"]}"

# --- document recolouring (invert page content toward the theme) ---
set recolor            {recolor}
set recolor-keephue    true
set recolor-lightcolor "{r["bg"]}"
set recolor-darkcolor  "{r["text"]}"
"""


def filetype_colors(variant: str) -> dict:
    """File-type colours shared by vifm AND dircolors — one table so `ls` and
    vifm cannot drift. Dark rides the vivid BRIGHT ANSI slots; on light the
    common groups drop to the BASE slots for readability (decision log — the
    bright slots are dark-tuned; upstream's own light design makes the same
    move). Light Link == Fifo (both base cyan) — accepted, fifos are rare."""
    r, a = vroles(variant), vansi(variant)
    if variant == "dark":
        return {
            "dir": a["bright_blue"], "link": a["bright_cyan"], "exec": a["bright_green"],
            "broken": a["bright_red"], "hardlink": a["bright_yellow"],
            "socket": a["bright_magenta"], "device": a["yellow"], "fifo": a["cyan"],
            "archives": a["bright_red"], "images": a["bright_magenta"],
            "video": a["magenta"], "audio": a["bright_cyan"],
            "docs": a["bright_yellow"], "markdown": a["white"],
        }
    return {
        "dir": a["blue"], "link": a["cyan"], "exec": a["green"],
        "broken": a["bright_red"], "hardlink": a["bright_yellow"],
        "socket": a["bright_magenta"], "device": a["yellow"], "fifo": a["cyan"],
        "archives": a["bright_red"], "images": a["bright_magenta"],
        "video": a["magenta"], "audio": a["cyan"],
        "docs": a["yellow"], "markdown": r["muted"],
    }


def render_vifm(variant: str) -> str:
    r, a, e = vroles(variant), vansi(variant), vext(variant)
    ft = filetype_colors(variant)
    if variant == "dark":
        ui_fg = e["ui_grey"]       # TopLine text / cursor-bar fill
        bar_fg = e["ink"]          # text ON the grey cursor bar
        tab_fg = a["white"]        # inactive tab/JobLine text (#d0d0d0)
    else:
        ui_fg = e["ui_dark"]       # the inversion: dark-grey bar on light
        bar_fg = r["accent_fg"]    # white text on that bar
        tab_fg = r["muted"]
    line_grey = e["line_grey"]

    def hl(group, attr, fg, bg="default"):
        cfg = xterm_index(fg) if fg != "default" else "default"
        cbg = xterm_index(bg) if bg != "default" else "default"
        gfg = fg if fg != "default" else "default"
        gbg = bg if bg != "default" else "default"
        return (f"highlight {group:<10} cterm={attr:<12} ctermfg={cfg!s:<7} "
                f"ctermbg={cbg!s:<7} guifg={gfg} guibg={gbg}")

    rows = [
        "\n\" frame — transparent canvas, terminal ground shows through",
        hl("Win", "none", r["text"]),
        hl("OtherWin", "none", r["text"]),
        hl("Border", "none", line_grey),
        hl("CmdLine", "none", r["text"]),
        "\n\" title / tab bar",
        hl("TopLine", "none", ui_fg, r["surface"]),
        hl("TopLineSel", "bold", bar_fg, ui_fg),
        hl("TabLine", "none", tab_fg, r["surface_alt"]),
        hl("TabLineSel", "bold", e["ink"], r["accent"]),
        "\n\" status line / messages — the accent lives here (accent status bar)",
        hl("StatusLine", "bold", r["accent_fg"], r["accent"]),
        hl("JobLine", "bold", tab_fg, r["surface_alt"]),
        hl("WildMenu", "bold", e["ink"], r["accent"]),
        hl("SuggestBox", "none", tab_fg, r["surface_alt"]),
        hl("ErrorMsg", "bold", a["bright_red"]),
        hl("LineNr", "none", line_grey),
        "\n\" cursor / selection — a quiet grey bar; the accent stays on the status line",
        hl("CurrLine", "bold", bar_fg, ui_fg),
        hl("Selected", "bold", a["bright_magenta"]),
        "\n\" file types",
        hl("Directory", "bold", ft["dir"]),
        hl("Link", "none", ft["link"]),
        hl("BrokenLink", "bold", ft["broken"]),
        hl("HardLink", "none", ft["hardlink"]),
        hl("Socket", "none", ft["socket"]),
        hl("Device", "none", ft["device"]),
        hl("Fifo", "none", ft["fifo"]),
        hl("Executable", "bold", ft["exec"]),
    ]
    pats = [
        ("{*.tar,*.tgz,*.tbz2,*.txz,*.zip,*.gz,*.bz2,*.xz,*.zst,*.7z,*.rar}", ft["archives"]),
        ("{*.jpg,*.jpeg,*.png,*.gif,*.bmp,*.tiff,*.webp,*.avif,*.svg,*.ico}", ft["images"]),
        ("{*.mp4,*.mkv,*.webm,*.mov,*.avi,*.m4v,*.flv}", ft["video"]),
        ("{*.mp3,*.flac,*.ogg,*.opus,*.wav,*.m4a,*.aac}", ft["audio"]),
        ("{*.pdf,*.epub,*.djvu}", ft["docs"]),
        ("{*.md,*.markdown}", ft["markdown"]),
    ]
    pat_lines = [
        "\n\" file-name patterns — vifm has no LS_COLORS, so these mirror the extension",
        "\" layer in ~/.dircolors by hand (keeps `ls` and vifm in sync on archives/media).",
    ]
    for pat, fg in pats:
        pat_lines.append(f"highlight {pat} cterm=none ctermfg={xterm_index(fg)} ctermbg=default guifg={fg}")

    header = [
        f"\" {PROVENANCE}",
        f"\" wildcharm.vifm — {variant} (wildcharm-{{dark,light}}.vifm pair; the bootstrap",
        "\" symlinks the `theme_variant` one to ~/.config/vifm/colors/wildcharm.vifm, so",
        "\" vifmrc's `colorscheme wildcharm` needs no variant logic).",
        "\" The canvas paints NO background (guibg=default): the terminal's own ground",
        "\" shows through, so vifm always matches kitty exactly.",
        "",
        "highlight clear",
    ]
    return "\n".join(header + rows + pat_lines) + "\n"


def render_dircolors(variant: str) -> str:
    ft = filetype_colors(variant)

    def c(key, bold=False):
        return ("01;" if bold else "") + f"38;5;{xterm_index(ft[key])}"

    exts = [
        ("archives / compressed", "archives",
         [".tar", ".tgz", ".tbz2", ".txz", ".zip", ".gz", ".bz2", ".xz", ".zst", ".7z", ".rar"]),
        ("images", "images",
         [".jpg", ".jpeg", ".png", ".gif", ".bmp", ".tiff", ".webp", ".avif", ".svg", ".ico"]),
        ("video", "video", [".mp4", ".mkv", ".webm", ".mov", ".avi", ".m4v", ".flv"]),
        ("audio", "audio", [".mp3", ".flac", ".ogg", ".opus", ".wav", ".m4a", ".aac"]),
        ("documents", "docs", [".pdf", ".epub", ".djvu"]),
        ("markdown", "markdown", [".md", ".markdown"]),
    ]
    lines = [
        f"# {PROVENANCE}",
        f"# hestia .dircolors — ls/eza/tree file colours, {variant} (.dircolors-{{dark,light}}",
        "# pair; the bootstrap symlinks the `theme_variant` one to ~/.dircolors).",
        "#",
        "# The file-TYPE colours come from the SAME per-variant table as vifm's generated",
        "# colorscheme (render.py filetype_colors), so `ls` and vifm agree by construction.",
        "# Indices 16-255 are the standard xterm cube (not the wildcharm-remapped 0-15).",
        "#",
        '# Loaded by .bashrc: `test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)"`.',
        "",
        "# Terminals colour is enabled for (kitty + the usual 256-colour set + console).",
        "TERM xterm-kitty",
        "TERM xterm-256color",
        "TERM screen-256color",
        "TERM tmux-256color",
        "TERM *-256color",
        "TERM xterm",
        "TERM screen",
        "TERM tmux",
        "TERM linux",
        "",
        "# --- file types (the vifm-shared table) ---",
        "RESET 0",
        "NORMAL 00",
        "FILE 00                         # regular file — plain, like vifm's Normal fg",
        f"DIR {c('dir', bold=True)}                  # vifm Directory",
        f"LINK {c('link')}                    # vifm Link",
        f"ORPHAN {c('broken', bold=True)}              # vifm BrokenLink",
        f"MISSING {c('broken', bold=True)}",
        f"EXEC {c('exec', bold=True)}                # vifm Executable",
        f"MULTIHARDLINK {c('hardlink')}          # vifm HardLink",
        f"SOCK {c('socket')}                    # vifm Socket",
        f"DOOR {c('socket')}",
        f"FIFO {c('fifo')}                    # vifm Fifo",
        f"BLK {c('device')}                     # vifm Device",
        f"CHR {c('device')}",
        "# permission-bit highlights (vifm has no direct analogue — keep them legible)",
        f"SETUID {c('broken', bold=True)}",
        f"SETGID {c('hardlink', bold=True)}",
        f"CAPABILITY {c('broken', bold=True)}",
        f"STICKY {c('dir', bold=True)}",
        f"OTHER_WRITABLE {c('dir')}",
        f"STICKY_OTHER_WRITABLE {c('dir')}",
        "",
        "# --- extension layer (restrained, wildcharm hues) ------------------------------",
        "# vifm shows regular files in the plain fg, so this is a deliberate enhancement on",
        "# top of the vifm-matched types — delete this block for exact `ls`==vifm parity.",
    ]
    for title, key, suffixes in exts:
        lines.append(f"# {title}")
        lines += [f"{s} {c(key)}" for s in suffixes]
    lines.append("")
    return "\n".join(lines)


GLOW_CHROMA = [
    # (chroma key, syntax role or None, extra style dict)
    ("text", "text", {}),
    ("error", "PAIRED", {}),
    ("comment", "comment", {"italic": True}),
    ("comment_preproc", "preproc", {}),
    ("keyword", "keyword", {}),
    ("keyword_reserved", "keyword", {}),
    ("keyword_namespace", "preproc", {}),
    ("keyword_type", "type", {}),
    ("operator", "keyword", {}),
    ("punctuation", "text", {}),
    ("name", "text", {}),
    ("name_builtin", "identifier", {}),
    ("name_tag", "keyword", {}),
    ("name_attribute", "type", {}),
    ("name_class", "type", {}),
    ("name_constant", "constant", {}),
    ("name_decorator", "preproc", {}),
    ("name_function", "identifier", {}),
    ("literal_number", "constant", {}),
    ("literal_string", "string", {}),
    ("literal_string_escape", "string_special", {}),
    ("generic_deleted", "diff_delete", {}),
    ("generic_emph", None, {"italic": True}),
    ("generic_inserted", "diff_add", {}),
    ("generic_strong", None, {"bold": True}),
    ("generic_subheading", "comment", {}),
]


def render_glow(variant: str) -> str:
    c = VARIANTS[variant]
    r = vroles(variant)
    acc, accfg, link, dim = r["accent"], r["accent_fg"], c["link"], r["dim"]
    chroma = {}
    for key, role, style in GLOW_CHROMA:
        entry = {}
        if role == "PAIRED":
            entry = {"color": c["error_fg"], "background_color": c["error_bg"]}
        elif role:
            entry["color"] = c[role]
        for k, v in style.items():
            entry[k] = v
        chroma[key] = entry
    chroma["background"] = {"background_color": r["surface"]}
    doc = {
        "_provenance": PROVENANCE,
        "document": {"block_prefix": "", "block_suffix": "", "color": c["text"], "margin": 2},
        "block_quote": {"color": dim, "indent": 1, "indent_token": "│ "},
        "paragraph": {},
        "list": {"level_indent": 2},
        "heading": {"block_suffix": "\n", "color": acc, "bold": True},
        "h1": {"prefix": " ", "suffix": " ", "color": accfg, "background_color": acc, "bold": True},
        "h2": {"prefix": "## ", "color": acc, "bold": True},
        "h3": {"prefix": "### ", "color": link, "bold": True},
        "h4": {"prefix": "#### ", "color": link, "bold": True},
        "h5": {"prefix": "##### ", "color": link, "bold": True},
        "h6": {"prefix": "###### ", "color": link},
        "text": {},
        "strikethrough": {"crossed_out": True},
        "emph": {"italic": True},
        "strong": {"bold": True},
        "hr": {"color": acc, "format": "\n────────\n"},
        "item": {"block_prefix": "• "},
        "enumeration": {"block_prefix": ". "},
        "task": {"ticked": "[✓] ", "unticked": "[ ] "},
        "link": {"color": link, "underline": True},
        "link_text": {"color": link, "bold": True},
        "image": {"color": link, "underline": True},
        "image_text": {"color": dim, "format": "Image: {{.text}} →"},
        "code": {"prefix": " ", "suffix": " ", "color": link, "background_color": r["surface"]},
        "code_block": {"color": c["text"], "margin": 2, "chroma": chroma},
        "table": {"center_separator": "┼", "column_separator": "│", "row_separator": "─"},
        "definition_list": {},
        "definition_term": {},
        "definition_description": {"block_prefix": "\n🠶 "},
        "html_block": {},
        "html_span": {},
    }
    return json.dumps(doc, indent=2, ensure_ascii=False) + "\n"


OUTPUTS = {
    REPO / "user/bat/themes/wildcharm-dark.tmTheme": lambda: render_tmtheme("dark"),
    REPO / "user/bat/themes/wildcharm-light.tmTheme": lambda: render_tmtheme("light"),
    HERE / "dist/shiki/hestia-dark.json": lambda: theme_json("dark", "shiki"),
    HERE / "dist/shiki/hestia-light.json": lambda: theme_json("light", "shiki"),
    REPO / "user/vscode/hestia/themes/hestia-dark-color-theme.json": lambda: theme_json("dark", "vscode"),
    REPO / "user/vscode/hestia/themes/hestia-light-color-theme.json": lambda: theme_json("light", "vscode"),
    REPO / "user/kitty/theme-dark.conf": lambda: render_kitty("dark"),
    REPO / "user/kitty/theme-light.conf": lambda: render_kitty("light"),
    REPO / "user/sway/theme-dark.conf": lambda: render_sway("dark"),
    REPO / "user/sway/theme-light.conf": lambda: render_sway("light"),
    REPO / "user/waybar/theme-dark.css": lambda: render_waybar_css("dark"),
    REPO / "user/waybar/theme-light.css": lambda: render_waybar_css("light"),
    REPO / "user/mako/theme-dark.conf": lambda: render_mako("dark"),
    REPO / "user/mako/theme-light.conf": lambda: render_mako("light"),
    REPO / "user/wofi/theme-dark.css": lambda: render_wofi_css("dark"),
    REPO / "user/wofi/theme-light.css": lambda: render_wofi_css("light"),
    REPO / "user/swaylock/config-dark": lambda: render_swaylock("dark"),
    REPO / "user/swaylock/config-light": lambda: render_swaylock("light"),
    REPO / "user/swaynag/config-dark": lambda: render_swaynag("dark"),
    REPO / "user/swaynag/config-light": lambda: render_swaynag("light"),
    REPO / "user/zathura/theme-dark": lambda: render_zathura("dark"),
    REPO / "user/zathura/theme-light": lambda: render_zathura("light"),
    REPO / "user/vifm/colors/wildcharm-dark.vifm": lambda: render_vifm("dark"),
    REPO / "user/vifm/colors/wildcharm-light.vifm": lambda: render_vifm("light"),
    REPO / "user/bash/.dircolors-dark": lambda: render_dircolors("dark"),
    REPO / "user/bash/.dircolors-light": lambda: render_dircolors("light"),
    REPO / "user/glow/wildcharm-dark.json": lambda: render_glow("dark"),
    REPO / "user/glow/wildcharm-light.json": lambda: render_glow("light"),
}


def main() -> None:
    aa_gate()
    check = "--check" in sys.argv
    drift = []
    for path, renderer in OUTPUTS.items():
        content = renderer()
        rel = path.relative_to(REPO)
        if check:
            if not path.exists() or path.read_text() != content:
                drift.append(str(rel))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
            print(f"rendered {rel}")
    if check:
        if drift:
            sys.exit("STALE (re-run render.py):\n  " + "\n  ".join(drift))
        print(f"check ok — all {len(OUTPUTS)} artifacts match palette v{VERSION}")


if __name__ == "__main__":
    main()
