#!/usr/bin/env python3
"""render.py — generate the theme artifacts from the palette.

Layer 3 of the theme pipeline (docs/theme-roadmap.md): reads palette.yml
(colours, per variant) + scopes.yml (the shared role→scope map) and renders

TextMate family (syntax + chrome):
  user/bat/themes/hestia.tmTheme                      (dark; terminal chrome)
  themes/hestia/dist/shiki/hestia-{dark,light}.json   (web code blocks;
                                                          bg = the code SURFACE)
  user/vscode/hestia/themes/hestia-{dark,light}-color-theme.json
                                                         (editor; bg = the app
                                                          CANVAS + UI chrome)

Desktop chrome, both variants each (roles/ANSI only — no scopes; the bootstrap
symlinks the one `theme_variant` selects to a variant-neutral dest, M7):
  fragments   kitty/sway/mako theme-*.conf, waybar theme-*.css, zathura
              theme-* (include'd/@import'ed by the main configs), wofi
              colors-* (wofi's own colors-file macro mechanism — no @import)
  whole-file  swaylock/swaynag config-* (no include support)
  theme pairs vifm hestia-*.vifm, bat hestia-*.tmTheme (TM family),
              glow hestia-*.json, bash .dircolors-* (ls file colours —
              generated from the SAME table as vifm so they cannot drift)
  single-file thunderbird userChrome/userContent.css — CSS light-dark()
              carries both variants in one file (TB follows the portal
              color-scheme), so no pair + variant symlink
  editor      user/vim/colors/hestia.vim — the Vim/Neovim colorscheme, one
              symlinked file carrying both &background branches (not a pair);
              dark reproduces wildcharm, light lands on the AA-tuned values

Same tokenColors everywhere; only the per-target chrome differs. The WCAG AA
contrast gate runs before anything is written — a palette edit that breaks a
plain-text role fails the render (reverse/fill roles are exempt; they are
checked as pairings by eye).

Usage:  render.py            render all artifacts in place
        render.py --check    exit 1 if any committed artifact differs from a
                             fresh render (use before/in review)

Never edit the generated files by hand — scope decisions go in scopes.yml,
colours in palette.yml, chrome maps below.
"""

import json
import sys
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent

PALETTE = yaml.safe_load((HERE / "palette.yml").read_text())
SCOPES = yaml.safe_load((HERE / "scopes.yml").read_text())["rules"]
VERSION = PALETTE["version"]
PROVENANCE = (
    f"GENERATED by themes/hestia/render.py from palette.yml v{VERSION} "
    f"+ scopes.yml — do not edit; edit the sources and re-render"
)

ROLES = PALETTE["roles"]
ANSI = PALETTE["ansi"]
LIGHT = PALETTE["light"]

# role → colour, per variant. `link` on light is the accent (it clears AA as
# text on white — decision log); error is the paired fill role.
VARIANTS = {
    "dark": {
        **PALETTE["syntax"],
        "text": ROLES["text"],
        "link": ROLES["link"],
        # exposed for the markdown scope map (scopes.yml): bat's rendered-markdown
        # headings mirror glow — H2–H6 = bright_cyan (H1 uses the AA-safe `link` violet).
        "bright_cyan": ANSI["bright_cyan"],
        "error_fg": "#ffffff",
        "error_bg": ROLES["danger_dark"],   # 0.10.0: danger red (light already uses syntax.error red)
        # surfaces the plain-text roles must clear AA against. Since 0.5.0 the
        # web code surface IS the ground (it reads raised on tci's darker
        # page); surface_alt is transient (hover/line-highlight), not a body-
        # text surface, so it is deliberately NOT gated here.
        "_aa_surfaces": [ROLES["bg"]],
        # per-target canvas/surface
        "_canvas": ROLES["bg"],          # vim/bat/VS Code app canvas
        "_code_surface": ROLES["bg"],    # web code blocks == the ground
    },
    "light": {
        **LIGHT["syntax"],
        "text": LIGHT["roles"]["text"],
        "link": LIGHT["roles"]["accent"],
        "bright_cyan": LIGHT["ansi"]["bright_cyan"],
        "error_fg": "#ffffff",
        "error_bg": LIGHT["syntax"]["error"],
        # the light gate runs against the #f5f5f5 DESKTOP ground (M7) — stricter
        # than the #ffffff code surface, so white is covered by implication
        "_aa_surfaces": [LIGHT["roles"]["bg"]],
        "_canvas": LIGHT["roles"]["bg"],
        # the web code surface keeps the M3 pure white (light-only split;
        # dark's code surface == the ground)
        "_code_surface": LIGHT["roles"]["code_surface"],
    },
}

# per-variant role/ANSI tables for the desktop-chrome emitters
def vroles(variant: str) -> dict:
    return ROLES if variant == "dark" else LIGHT["roles"]


def vansi(variant: str) -> dict:
    return ANSI if variant == "dark" else LIGHT["ansi"]

FILL_ROLES = {"error", "todo"}  # reverse/fill — exempt from the plain-text gate


def _lum(hexval: str) -> float:
    h = hexval.lstrip("#")
    c = [int(h[i : i + 2], 16) / 255 for i in (0, 2, 4)]
    c = [x / 12.92 if x <= 0.04045 else ((x + 0.055) / 1.055) ** 2.4 for x in c]
    return 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2]


def contrast(a: str, b: str) -> float:
    la, lb = sorted((_lum(a), _lum(b)), reverse=True)
    return (la + 0.05) / (lb + 0.05)


def aa_gate() -> None:
    failures = []
    for variant, colors in VARIANTS.items():
        for role, hexval in colors.items():
            if role.startswith("_") or role in FILL_ROLES or role.startswith("error"):
                continue
            for surface in colors["_aa_surfaces"]:
                r = contrast(hexval, surface)
                if r < 4.5:
                    failures.append(f"{variant}.{role} {hexval} on {surface}: {r:.2f}:1")
    if failures:
        sys.exit("AA contrast gate FAILED:\n  " + "\n  ".join(failures))


def token_colors(colors: dict) -> list:
    out = []
    for rule in SCOPES:
        settings = {}
        role = rule.get("role")
        if rule.get("paired"):
            settings["foreground"] = colors["error_fg"]
            settings["background"] = colors["error_bg"]
        elif role:
            settings["foreground"] = colors[role]
        # `is not None` so font_style: "" is emitted as fontStyle:"" — an
        # explicit CLEAR (TextMate resolves fontStyle independently of
        # foreground by specificity, so a bare fg rule would otherwise inherit
        # italic/bold from a less-specific scope; see the keys/property rule).
        if rule.get("font_style") is not None:
            settings["fontStyle"] = rule["font_style"]
        out.append({"name": rule["name"], "scope": rule["scopes"], "settings": settings})
    return out


# ---------------------------------------------------------------- tmTheme (bat)

def render_tmtheme(variant: str = "dark") -> str:
    c = VARIANTS[variant]
    r = vroles(variant)
    chrome = {
        "background": c["_canvas"],
        "foreground": c["text"],
        "caret": r["accent"],
        "lineHighlight": r["surface_alt"],
        "selection": r["border"],
        "invisibles": r["dim"],
        "guide": r["border"],
        "activeGuide": r["dim"],
        "gutterForeground": r["dim"],
    }
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
        f"<!-- {PROVENANCE} -->",
        '<plist version="1.0">',
        "<dict>",
        "  <key>name</key>",
        "  <string>hestia</string>",
        "  <key>settings</key>",
        "  <array>",
        "",
        "    <dict>",
        "      <key>settings</key>",
        "      <dict>",
    ]
    for k, v in chrome.items():
        lines.append(f"        <key>{k}</key> <string>{v}</string>")
    lines += ["      </dict>", "    </dict>"]
    for tc in token_colors(c):
        lines += [
            "",
            "    <dict>",
            f"      <key>name</key><string>{tc['name']}</string>",
            f"      <key>scope</key><string>{', '.join(tc['scope'])}</string>",
            "      <key>settings</key>",
            "      <dict>",
        ]
        for k, v in tc["settings"].items():
            lines.append(f"        <key>{k}</key><string>{v}</string>")
        lines += ["      </dict>", "    </dict>"]
    lines += ["", "  </array>", "</dict>", "</plist>", ""]
    return "\n".join(lines)


# ------------------------------------------------------------------ theme JSON

def theme_json(variant: str, target: str) -> str:
    c = VARIANTS[variant]
    if target == "shiki":
        colors = {
            "editor.background": c["_code_surface"],
            "editor.foreground": c["text"],
        }
    else:  # vscode — full UI chrome from the variant's roles + ANSI (since M7
        # PR2 light mirrors dark's chrome key-for-key; before that light shipped
        # minimal chrome and fell back to VS Code's stock light UI)
        r, a = vroles(variant), vansi(variant)
        acc, accfg = r["accent"], r["accent_fg"]
        colors = {
            "focusBorder": acc,
            "foreground": c["text"],
            # links in UI text (chat/welcome/notifications) + ctrl-hover links
            # in the editor — default to VS Code blue unless mapped
            "textLink.foreground": c["link"],
            "textLink.activeForeground": c["link"],
            "editorLink.activeForeground": c["link"],
            "editor.background": c["_canvas"],
            "editor.foreground": c["text"],
            "editor.lineHighlightBackground": r["surface_alt"],
            "editor.selectionBackground": r["border"],
            "editorCursor.foreground": acc,
            "editorLineNumber.foreground": r["dim"],
            "editorLineNumber.activeForeground": c["text"],
            "editorIndentGuide.background1": r["border"],
            "editorIndentGuide.activeBackground1": r["dim"],
            "editorWhitespace.foreground": r["border"],
            "sideBar.background": r["surface"],
            "sideBar.foreground": r["muted"],
            "sideBar.border": r["border"],
            "sideBarTitle.foreground": c["text"],
            "activityBar.background": c["_canvas"],
            "activityBar.foreground": c["text"],
            "activityBar.inactiveForeground": r["dim"],
            "activityBarBadge.background": acc,
            "activityBarBadge.foreground": accfg,
            "statusBar.background": acc,
            "statusBar.foreground": accfg,
            "statusBar.noFolderBackground": r["accent_dark"],
            "statusBar.debuggingBackground": r["accent_dark"],
            "titleBar.activeBackground": r["surface"],
            "titleBar.activeForeground": c["text"],
            "titleBar.inactiveBackground": c["_canvas"],
            "titleBar.inactiveForeground": r["dim"],
            "tab.activeBackground": c["_canvas"],
            "tab.activeForeground": c["text"],
            "tab.activeBorderTop": acc,
            "tab.inactiveBackground": r["surface"],
            "tab.inactiveForeground": r["dim"],
            "editorGroupHeader.tabsBackground": r["surface"],
            "panel.background": c["_canvas"],
            "panel.border": r["border"],
            "input.background": r["surface"],
            "input.foreground": c["text"],
            "input.border": r["border"],
            "dropdown.background": r["surface"],
            "dropdown.foreground": c["text"],
            "button.background": acc,
            "button.foreground": accfg,
            "badge.background": acc,
            "badge.foreground": accfg,
            "list.activeSelectionBackground": acc,
            "list.activeSelectionForeground": accfg,
            "list.inactiveSelectionBackground": r["surface_alt"],
            "list.hoverBackground": r["surface_alt"],
            "scrollbarSlider.background": r["border"],
            "scrollbarSlider.hoverBackground": r["dim"],
            # semantic info/warning/error — same meanings the terminal tools
            # use (buildkit run-blue, git/zathura warning-yellow, vifm
            # ErrorMsg bright-red); covers notification toasts, editor
            # squiggles and the Problems panel
            "notifications.background": r["surface"],
            "notifications.foreground": c["text"],
            "notifications.border": r["border"],
            "notificationCenterHeader.background": r["surface_alt"],
            "notificationsInfoIcon.foreground": a["blue"],
            "notificationsWarningIcon.foreground": a["yellow"],
            "notificationsErrorIcon.foreground": a["bright_red"],
            "editorInfo.foreground": a["blue"],
            "editorWarning.foreground": a["yellow"],
            "editorError.foreground": a["bright_red"],
            "terminal.background": c["_canvas"],
            "terminal.foreground": c["text"],
            "terminalCursor.foreground": acc,
            "terminal.ansiBlack": a["black"],
            "terminal.ansiRed": a["red"],
            "terminal.ansiGreen": a["green"],
            "terminal.ansiYellow": a["yellow"],
            "terminal.ansiBlue": a["blue"],
            "terminal.ansiMagenta": a["magenta"],
            "terminal.ansiCyan": a["cyan"],
            "terminal.ansiWhite": a["white"],
            "terminal.ansiBrightBlack": a["bright_black"],
            "terminal.ansiBrightRed": a["bright_red"],
            "terminal.ansiBrightGreen": a["bright_green"],
            "terminal.ansiBrightYellow": a["bright_yellow"],
            "terminal.ansiBrightBlue": a["bright_blue"],
            "terminal.ansiBrightMagenta": a["bright_magenta"],
            "terminal.ansiBrightCyan": a["bright_cyan"],
            "terminal.ansiBrightWhite": a["bright_white"],
        }
    doc = {
        "_provenance": PROVENANCE,
        "name": f"hestia-{variant}",
        "type": variant,
        "colors": colors,
        "tokenColors": token_colors(c),
    }
    return json.dumps(doc, indent=2, ensure_ascii=False) + "\n"


# ------------------------------------------------- desktop chrome (M7 switch)
# Per-app colour fragments, both variants; the bootstrap manifest symlinks the
# `theme_variant` one to a variant-neutral destination (theme.conf / theme.css).
# Roles/ANSI only — no syntax scopes. Mappings live here (platform-quirk rule).

def render_kitty(variant: str) -> str:
    r, a = vroles(variant), vansi(variant)
    slots = [
        "black", "red", "green", "yellow", "blue", "magenta", "cyan", "white",
        "bright_black", "bright_red", "bright_green", "bright_yellow",
        "bright_blue", "bright_magenta", "bright_cyan", "bright_white",
    ]
    lines = [f"# {PROVENANCE}", f"# kitty colours — {variant} (see kitty.conf: include theme.conf)", ""]
    if variant == "dark":
        lines += ["# Note: bg == ANSI color0 — accepted; watch item in the roadmap backlog.", ""]
    lines += [
        f"background            {r['bg']}",
        f"foreground            {r['text']}",
        f"cursor                {r['accent']}",
        f"cursor_text_color     {r['accent_fg']}",
        f"selection_background  {r['accent']}",
        f"selection_foreground  {r['accent_fg']}",
        "",
    ]
    for i, slot in enumerate(slots):
        lines.append(f"color{i:<2} {a[slot]}")
    lines += [
        "",
        f"active_tab_background   {r['accent']}",
        f"active_tab_foreground   {r['accent_fg']}",
        f"inactive_tab_background {r['surface']}",
        f"inactive_tab_foreground {r['dim']}",
        f"tab_bar_background      {r['bg']}",
        "",
        "# Split borders (kitty's default active is green) — quiet greys",
        f"active_border_color   {r['surface']}",
        f"inactive_border_color {r['border']}",
        "",
    ]
    return "\n".join(lines)


def render_sway(variant: str) -> str:
    r, a = vroles(variant), vansi(variant)
    # Focused-tile border (client.focused in user/sway/config) — cyan, not the
    # accent, so "this tile has focus" reads apart from the red accent surfaces.
    # Both variants ride ANSI 14 (bright_cyan): each table's own step (dark
    # #00d7d7, light #00afaf). Light was cyan-6 (#008787) at first for ground
    # contrast, but the brighter step won the live A/B — a 2px border needs
    # less contrast than text.
    focus = a["bright_cyan"]
    scheme = "prefer-dark" if variant == "dark" else "prefer-light"
    gtk_theme = "hestia-dark" if variant == "dark" else "hestia"
    # KDE Breeze cursors (breeze-cursor-theme, apt): the WHITE cursor on the
    # dark desktop, the standard dark "Breeze" on light. Names are the theme
    # DIRS in /usr/share/icons (index.theme: Breeze Light / Breeze).
    cursor = "Breeze_Light" if variant == "dark" else "breeze_cursors"
    return f"""# {PROVENANCE}
# sway theme fragment — {variant} (see config: include ~/.config/sway/theme.conf)

# Colors (roles from palette.yml)
set $bg        {r["bg"]}
set $surface   {r["surface"]}
set $border    {r["border"]}
set $text      {r["text"]}
set $dim       {r["dim"]}
set $accent    {r["accent"]}
set $accent_fg {r["accent_fg"]}
set $focus     {focus}

# Desktop background — the solid ground is the base and the fallback; the
# plain-mesh wallpaper (below) layers over it when its assets are installed.
output * bg {r["bg"]} solid_color

# Default wallpaper — per-output static mesh PNGs via wpaperd (the wallpaper
# verdict; the mpvpaper video loop was dropped for an unfixed upstream mpv
# memory leak — see wallpaper.sh; assets from the `wallpapers` role).
# exec_always is load-bearing: a reload respawns swaybg ABOVE the wallpaper
# layer, and the re-run re-kills it. No-ops (solid ground stays) when
# wpaperd/assets are absent.
exec_always $HOME/.config/sway/scripts/wallpaper.sh {variant}

# Mouse cursor — sway's own cursor (window drags, resize, the bare desktop).
# Clients draw their own: GTK reads the gsettings exec below + settings.ini,
# XWayland/Qt read start-sway's XCURSOR_THEME export (all follow the variant).
seat * xcursor_theme {cursor} 24

# GTK / portal appearance for this variant (CLAUDE.md GTK section): color-scheme
# is what GTK4/libadwaita + Firefox + portal-aware apps follow; gtk-theme is what
# GTK3 apps (and the portal file chooser) follow — GTK_THEME is deliberately unset
# (it broke GTK4 dark mode), so gsettings is the single GTK theme source now.
# `exec` runs at login only — not re-run on `swaymsg reload`.
exec gsettings set org.gnome.desktop.interface color-scheme {scheme}
exec gsettings set org.gnome.desktop.interface gtk-theme {gtk_theme}
exec gsettings set org.gnome.desktop.interface cursor-theme {cursor}
# Icon theme: the #7c3aed-accent Yaru built by the opt-in yaru_icons role
# (Yaru-hestia). Guard on the theme actually existing so a spin without that
# role doesn't force a missing theme.
exec sh -c 'test -d "$HOME/.local/share/icons/Yaru-hestia" && gsettings set org.gnome.desktop.interface icon-theme Yaru-hestia'
"""


def render_waybar_css(variant: str) -> str:
    r, a = vroles(variant), vansi(variant)
    tokens = {
        "bg": r["bg"],
        "text": r["text"],
        "muted": r["muted"],
        "border": r["border"],
        "surface_alt": r["surface_alt"],
        "accent": r["accent"],
        "accent_fg": r["accent_fg"],
        # per-widget signature accents (style.css): the power ⏻ is DANGER red
        # (power-off is a destructive action) and the focused-workspace marker is
        # the CYAN that matches sway's window-focus border ($focus == ansi
        # .bright_cyan). The launcher stays the violet accent (@accent).
        "danger": r["danger"],
        "focus": a["bright_cyan"],
        # muted-state icons (pulseaudio.muted) — ANSI bright_black, the
        # quietest grey that still reads on the bar
        "icon_muted": a["bright_black"],
    }
    lines = [f"/* {PROVENANCE}",
             f"   waybar colour tokens — {variant} (style.css: @import \"theme.css\") */", ""]
    lines += [f"@define-color {k} {v};" for k, v in tokens.items()]
    lines.append("")
    return "\n".join(lines)


# ----------------------------------------------- xterm-256 index (vifm cterm)

_CUBE = [0, 95, 135, 175, 215, 255]


def xterm_index(hexval: str) -> int:
    """Nearest xterm-256 index (16-255). Palette values are xterm-native except
    the two grounds (#1a1a1a -> 234, #f5f5f5 -> 255) — nearest steps, matching
    the cterm fallbacks hestia.vim uses."""
    h = hexval.lstrip("#")
    r, g, b = (int(h[i : i + 2], 16) for i in (0, 2, 4))
    best, best_d = 16, 3 * 255 ** 2 + 1
    for ri, rv in enumerate(_CUBE):
        for gi, gv in enumerate(_CUBE):
            for bi, bv in enumerate(_CUBE):
                d = (r - rv) ** 2 + (g - gv) ** 2 + (b - bv) ** 2
                if d < best_d:
                    best, best_d = 16 + 36 * ri + 6 * gi + bi, d
    for i in range(24):
        v = 8 + 10 * i
        d = (r - v) ** 2 + (g - v) ** 2 + (b - v) ** 2
        if d < best_d:
            best, best_d = 232 + i, d
    return best


# ------------------------------------------- desktop chrome, the long tail (M7)

EXT = PALETTE["extended"]
LEXT = LIGHT["extended"]


def vext(variant: str) -> dict:
    # light falls back to the shared extended for variant-invariant values (ink)
    return EXT if variant == "dark" else {**EXT, **LEXT}


def _css_tokens(variant: str, tokens: dict, note: str) -> str:
    lines = [f"/* {PROVENANCE}", f"   {note} */", ""]
    lines += [f"@define-color {k} {v};" for k, v in tokens.items()]
    lines.append("")
    return "\n".join(lines)


def render_mako(variant: str) -> str:
    r, e = vroles(variant), vext(variant)
    return f"""# {PROVENANCE}
# mako colours — {variant}. Included LAST by ~/.config/mako/config so the
# [urgency=high] section below can't swallow main-config keys. default-timeout=0
# rides with the section (criteria keys must stay inside it): urgent sticks.

background-color={r["bg"]}
text-color={r["text"]}
border-color={r["accent"]}

[urgency=high]
background-color={r["danger"]}
border-color={r["danger_dark"]}
text-color={r["accent_fg"]}
default-timeout=0
"""


# wofi does NOT support @import/@define-color fragments: it preprocesses the
# stylesheet TEXT itself (substituting --wofi-color<n> macros from its "colors
# file") and then hands the result to GTK, so a relative @import never resolves
# (caught live — the launcher rendered transparent). The native mechanism is the
# colors file: newline-separated hexes, line N referenced as --wofi-color<N-1>
# in style.css, path wired by `colors=` in the wofi config (relative paths
# resolve against ~/.config/wofi). SLOT ORDER (style.css documents it too):
WOFI_SLOTS = ["bg", "text", "muted", "border", "surface", "accent", "accent_fg", "focus"]


def render_wofi_colors(variant: str) -> str:
    # NO comments/provenance in this file — wofi parses every line as a hex
    # "focus" = the variant's bright_cyan, the same slot sway's client.focused
    # border rides ($focus in the theme fragment) — the launcher IS the focused
    # window, so its frame speaks the focus colour, not the accent
    r, a = vroles(variant), vansi(variant)
    vals = {**r, "focus": a["bright_cyan"]}
    return "\n".join(vals[slot] for slot in WOFI_SLOTS) + "\n"


def render_swaylock(variant: str) -> str:
    r, a, e = vroles(variant), vansi(variant), vext(variant)
    def b(h):  # swaylock wants bare RRGGBB
        return h.lstrip("#")
    return f"""# {PROVENANCE}
# swaylock — hestia lockscreen, {variant} (config-dark / config-light pair;
# the bootstrap symlinks the `theme_variant` one to ~/.config/swaylock/config).
#
# IMPORTANT: swaylock's config parser only supports WHOLE-LINE `#` comments — it
# does NOT strip trailing/inline comments. Keep every annotation on its own line;
# values are bare RRGGBB (no leading '#').
#
# Sway invokes `swaylock -f` (no -c flag), so `color` below is the single source
# for the lock background. `indicator-idle-visible` keeps the ring on when idle.

color={b(r["bg"])}
font=Lilex Nerd Font Mono
indicator-radius=110
indicator-thickness=8
indicator-idle-visible
indicator-caps-lock
show-failed-attempts

# idle (no input): inside=sunken, ring=border, line/separator=bg, text=text
inside-color={b(e["sunken"])}
ring-color={b(r["border"])}
line-color={b(r["bg"])}
separator-color={b(r["bg"])}
text-color={b(r["text"])}

# typing: key highlight = accent, backspace = bright_red
key-hl-color={b(r["accent"])}
bs-hl-color={b(a["bright_red"])}

# verifying (checking password): ring = blue
inside-ver-color={b(e["sunken"])}
ring-ver-color={b(a["blue"])}
line-ver-color={b(r["bg"])}
text-ver-color={b(r["text"])}

# wrong password: ring = bright_red, inside = danger_dark (0.10.0: red, not the
# now-violet accent), text = accent_fg
inside-wrong-color={b(r["danger_dark"])}
ring-wrong-color={b(a["bright_red"])}
line-wrong-color={b(r["bg"])}
text-wrong-color={b(r["accent_fg"])}

# cleared (input wiped): ring = accent
inside-clear-color={b(e["sunken"])}
ring-clear-color={b(r["accent"])}
line-clear-color={b(r["bg"])}
text-clear-color={b(r["text"])}

# caps lock on: ring + highlight = bright_yellow (warning), backspace = bright_red
inside-caps-lock-color={b(e["sunken"])}
ring-caps-lock-color={b(a["bright_yellow"])}
caps-lock-key-hl-color={b(a["bright_yellow"])}
caps-lock-bs-hl-color={b(a["bright_red"])}
text-caps-lock-color={b(r["text"])}

# keyboard-layout indicator (the "language" field): match the lock background so
# the box blends in — swaylock's default is a separate translucent-dark fill,
# which read as a different background against color= above.
layout-bg-color={b(r["bg"])}
layout-border-color={b(r["bg"])}
layout-text-color={b(r["text"])}
"""


def render_swaynag(variant: str) -> str:
    # Typeless dialogs keep the quiet dark base with an accent line; the two
    # built-in types are FULL-ACCENT banners (2026-07 redesign — they read as
    # the waybar accent baseline grown into a bar; the earlier orange warning
    # dropped so every destructive confirm speaks the one accent language).
    # Buttons on the accent are inverse chips — accent_fg fill, accent text —
    # flat (border-size 0) with roomier padding/gaps, the "modern" available
    # in swaynag's flat-rectangle vocabulary (no corner radius exists).
    # Typeless keeps the sunken-well buttons on the dark base.
    r, a, e = vroles(variant), vansi(variant), vext(variant)
    def b(h):
        return h.lstrip("#")
    # Since 0.10.0 the destructive-confirm banners (warning/error) speak DANGER
    # red, not the brand accent — the accent went violet, but "reboot? / exit?"
    # is a careful-now prompt, so it stays red. The typeless dialog keeps the
    # quiet accent (violet) line — it's decorative, not a loud confirm.
    danger_chip = (r["accent_fg"], r["danger"])
    sunken_well = (e["sunken"], r["text"])
    sections = [
        ("global / default (dialogs with no -t): dark base, accent line",
         None, r["bg"], r["text"], r["border"], r["accent"], sunken_well),
        ("warning (the sway exit confirm + power-menu confirms pass -t warning):",
         "warning", r["danger"], r["accent_fg"], r["danger_dark"], r["danger_dark"], danger_chip),
        ("error: same danger banner — one language for everything loud",
         "error", r["danger"], r["accent_fg"], r["danger_dark"], r["danger_dark"], danger_chip),
    ]
    out = [f"# {PROVENANCE}",
           f"# swaynag — hestia dialogs, {variant} (config-dark / config-light pair; the",
           "# bootstrap symlinks the `theme_variant` one to ~/.config/swaynag/config).",
           "# Values are bare RRGGBB (no '#'); annotations on their own lines.",
           "#",
           "# GOTCHA: swaynag's built-in `warning`/`error` types ship hardcoded colours and",
           "# do NOT layer the global options — only keys set INSIDE a type's [section]",
           "# override its presets, so the theme is restated in full per section.",
           ""]
    for title, section, bg, text, border, accent_line, (btn_bg, btn_fg) in sections:
        out.append(f"# --- {title} ---")
        if section:
            out.append(f"[{section}]")
        else:
            out += [
                "font=Lilex Nerd Font Mono 11",
                "# flat, roomy buttons (geometry is global-only — set before any [section])",
                "button-border-size=0",
                # button-padding matches message-padding on purpose: swaynag draws
                # buttons top-pinned (not vertically centred) and sizes the bar from the
                # message, so a smaller button-padding leaves the extra height as a gap
                # *below* the buttons (top-heavy). Equal paddings make the buttons fill
                # the bar height → symmetric top/bottom. (No top-padding key exists.)
                "button-padding=12",
                "button-gap=10",
                "button-dismiss-gap=10",
                "button-margin-right=6",
                "message-padding=12",
            ]
        out += [
            f"background={b(bg)}",
            f"border={b(border)}",
            f"border-bottom={b(accent_line)}",
            "border-bottom-size=2",
            f"text={b(text)}",
            f"button-background={b(btn_bg)}",
            f"button-text={b(btn_fg)}",
            f"details-background={b(e['sunken'])}",
            "",
        ]
    return "\n".join(out)


def render_zathura(variant: str) -> str:
    r, a = vroles(variant), vansi(variant)
    def rgba(h, alpha):
        v = h.lstrip("#")
        rr, gg, bb = (int(v[i : i + 2], 16) for i in (0, 2, 4))
        return f'"rgba({rr}, {gg}, {bb}, {alpha})"'
    # warning fill takes contrast text: the dark ground on dark's yellow, white
    # on light's darker yellow
    warn_fg = r["bg"] if variant == "dark" else r["accent_fg"]
    # recolour is a dark-mode feature: on by default on dark (white pages ->
    # ground), OFF on light (pages are already light); `r` toggles either way,
    # so both variants carry sensible recolor-* values.
    recolor = "true" if variant == "dark" else "false"
    return f"""# {PROVENANCE}
# zathura colours — {variant} (theme-dark / theme-light pair; the bootstrap
# symlinks the `theme_variant` one to ~/.config/zathura/theme, `include`d by
# zathurarc). zathura takes "#RRGGBB" (+ rgba(...) for translucent highlights).

# --- window / page area ---
set default-bg          "{r["bg"]}"
set default-fg          "{r["text"]}"
set render-loading-bg   "{r["bg"]}"
set render-loading-fg   "{r["text"]}"

# --- statusbar (bottom bar) ---
set statusbar-bg        "{r["surface"]}"
set statusbar-fg        "{r["text"]}"

# --- inputbar (the ':' command line) ---
set inputbar-bg         "{r["surface"]}"
set inputbar-fg         "{r["text"]}"

# --- notifications (info / warning / error) ---
set notification-bg         "{r["surface"]}"
set notification-fg         "{r["text"]}"
set notification-warning-bg "{a["yellow"]}"
set notification-warning-fg "{warn_fg}"
set notification-error-bg   "{r["danger_dark"]}"
set notification-error-fg   "{r["accent_fg"]}"

# --- search highlights (translucent so the text shows through) ---
# all matches = blue; the active/focused match = accent
set highlight-color        {rgba(a["blue"], "0.35")}
set highlight-active-color {rgba(r["accent"], "0.5")}

# --- completion menu (Tab) ---
set completion-bg           "{r["surface"]}"
set completion-fg           "{r["text"]}"
set completion-group-bg     "{r["bg"]}"
set completion-group-fg     "{r["accent"]}"
set completion-highlight-bg "{r["accent"]}"
set completion-highlight-fg "{r["accent_fg"]}"

# --- index / table of contents ---
set index-bg        "{r["bg"]}"
set index-fg        "{r["text"]}"
set index-active-bg "{r["accent"]}"
set index-active-fg "{r["accent_fg"]}"

# --- document recolouring (invert page content toward the theme) ---
set recolor            {recolor}
set recolor-keephue    true
set recolor-lightcolor "{r["bg"]}"
set recolor-darkcolor  "{r["text"]}"
"""


def filetype_colors(variant: str) -> dict:
    """File-type colours shared by vifm AND dircolors — one table so `ls` and
    vifm cannot drift. Dark rides the vivid BRIGHT ANSI slots; on light the
    common groups drop to the BASE slots for readability (decision log — the
    bright slots are dark-tuned; upstream's own light design makes the same
    move). Light Link == Fifo (both base cyan) — accepted, fifos are rare."""
    r, a = vroles(variant), vansi(variant)
    if variant == "dark":
        return {
            "dir": a["bright_blue"], "link": a["bright_cyan"], "exec": a["bright_green"],
            "broken": a["bright_red"], "hardlink": a["bright_yellow"],
            "socket": a["bright_magenta"], "device": a["yellow"], "fifo": a["cyan"],
            "archives": a["bright_red"], "images": a["bright_magenta"],
            "video": a["magenta"], "audio": a["bright_cyan"],
            "docs": a["bright_yellow"], "markdown": a["white"],
        }
    return {
        "dir": a["blue"], "link": a["cyan"], "exec": a["green"],
        "broken": a["bright_red"], "hardlink": a["bright_yellow"],
        "socket": a["bright_magenta"], "device": a["yellow"], "fifo": a["cyan"],
        "archives": a["bright_red"], "images": a["bright_magenta"],
        "video": a["magenta"], "audio": a["cyan"],
        "docs": a["yellow"], "markdown": r["muted"],
    }


def render_vifm(variant: str) -> str:
    r, a, e = vroles(variant), vansi(variant), vext(variant)
    ft = filetype_colors(variant)
    if variant == "dark":
        ui_fg = e["ui_grey"]       # TopLine text / cursor-bar fill
        bar_fg = e["ink"]          # text ON the grey cursor bar
        tab_fg = a["white"]        # inactive tab/JobLine text (#d0d0d0)
    else:
        ui_fg = e["ui_dark"]       # the inversion: dark-grey bar on light
        bar_fg = r["accent_fg"]    # white text on that bar
        tab_fg = r["muted"]
    line_grey = e["line_grey"]
    # Miller parent-column shade (AuxWin). vifm has no separate group for the
    # parent column's cursor bar — it always paints CurrLine (fileview.c mixes
    # CURR_LINE_COLOR for non-main columns too; maintainer-confirmed, Q2A #1844)
    # — so the supported differentiation is shading the WHOLE aux column one
    # quiet step off the ground. Light uses surface, NOT extended.sunken: light
    # sunken is the white below-ground WELL fill, which would read raised here.
    aux_bg = e["sunken"] if variant == "dark" else r["surface"]

    def hl(group, attr, fg, bg="default"):
        cfg = xterm_index(fg) if fg != "default" else "default"
        cbg = xterm_index(bg) if bg != "default" else "default"
        gfg = fg if fg != "default" else "default"
        gbg = bg if bg != "default" else "default"
        return (f"highlight {group:<10} cterm={attr:<12} ctermfg={cfg!s:<7} "
                f"ctermbg={cbg!s:<7} guifg={gfg} guibg={gbg}")

    rows = [
        "\n\" frame — transparent canvas, terminal ground shows through",
        hl("Win", "none", r["text"]),
        hl("OtherWin", "none", r["text"]),
        "\" AuxWin recesses the miller PARENT column (the only per-column knob —",
        "\" the cursor bar itself is always CurrLine, in every column)",
        hl("AuxWin", "none", "default", aux_bg),
        hl("Border", "none", line_grey),
        hl("CmdLine", "none", r["text"]),
        "\n\" title / tab bar",
        hl("TopLine", "none", ui_fg, r["surface"]),
        # active pane's path/title bar → the violet accent (matches StatusLine
        # below + TabLineSel; the inactive TopLine stays a quiet grey)
        hl("TopLineSel", "bold", r["accent_fg"], r["accent"]),
        hl("TabLine", "none", tab_fg, r["surface_alt"]),
        hl("TabLineSel", "bold", e["ink"], r["accent"]),
        "\n\" status line / messages — the accent lives here (accent status bar)",
        hl("StatusLine", "bold", r["accent_fg"], r["accent"]),
        hl("JobLine", "bold", tab_fg, r["surface_alt"]),
        hl("WildMenu", "bold", e["ink"], r["accent"]),
        hl("SuggestBox", "none", tab_fg, r["surface_alt"]),
        hl("ErrorMsg", "bold", a["bright_red"]),
        hl("LineNr", "none", line_grey),
        "\n\" cursor / selection — a quiet grey bar; the accent stays on the status line",
        hl("CurrLine", "bold", bar_fg, ui_fg),
        hl("Selected", "bold", a["bright_magenta"]),
        "\n\" file types",
        hl("Directory", "bold", ft["dir"]),
        hl("Link", "none", ft["link"]),
        hl("BrokenLink", "bold", ft["broken"]),
        hl("HardLink", "none", ft["hardlink"]),
        hl("Socket", "none", ft["socket"]),
        hl("Device", "none", ft["device"]),
        hl("Fifo", "none", ft["fifo"]),
        hl("Executable", "bold", ft["exec"]),
    ]
    pats = [
        ("{*.tar,*.tgz,*.tbz2,*.txz,*.zip,*.gz,*.bz2,*.xz,*.zst,*.7z,*.rar}", ft["archives"]),
        ("{*.jpg,*.jpeg,*.png,*.gif,*.bmp,*.tiff,*.webp,*.avif,*.svg,*.ico}", ft["images"]),
        ("{*.mp4,*.mkv,*.webm,*.mov,*.avi,*.m4v,*.flv}", ft["video"]),
        ("{*.mp3,*.flac,*.ogg,*.opus,*.wav,*.m4a,*.aac}", ft["audio"]),
        ("{*.pdf,*.epub,*.djvu}", ft["docs"]),
        ("{*.md,*.markdown}", ft["markdown"]),
    ]
    pat_lines = [
        "\n\" file-name patterns — vifm has no LS_COLORS, so these mirror the extension",
        "\" layer in ~/.dircolors by hand (keeps `ls` and vifm in sync on archives/media).",
    ]
    for pat, fg in pats:
        pat_lines.append(f"highlight {pat} cterm=none ctermfg={xterm_index(fg)} ctermbg=default guifg={fg}")

    header = [
        f"\" {PROVENANCE}",
        f"\" hestia.vifm — {variant} (hestia-{{dark,light}}.vifm pair; the bootstrap",
        "\" symlinks the `theme_variant` one to ~/.config/vifm/colors/hestia.vifm, so",
        "\" vifmrc's `colorscheme hestia` needs no variant logic).",
        "\" The canvas paints NO background (guibg=default): the terminal's own ground",
        "\" shows through, so vifm always matches kitty exactly.",
        "",
        "highlight clear",
    ]
    return "\n".join(header + rows + pat_lines) + "\n"


def render_dircolors(variant: str) -> str:
    ft = filetype_colors(variant)

    def c(key, bold=False):
        return ("01;" if bold else "") + f"38;5;{xterm_index(ft[key])}"

    exts = [
        ("archives / compressed", "archives",
         [".tar", ".tgz", ".tbz2", ".txz", ".zip", ".gz", ".bz2", ".xz", ".zst", ".7z", ".rar"]),
        ("images", "images",
         [".jpg", ".jpeg", ".png", ".gif", ".bmp", ".tiff", ".webp", ".avif", ".svg", ".ico"]),
        ("video", "video", [".mp4", ".mkv", ".webm", ".mov", ".avi", ".m4v", ".flv"]),
        ("audio", "audio", [".mp3", ".flac", ".ogg", ".opus", ".wav", ".m4a", ".aac"]),
        ("documents", "docs", [".pdf", ".epub", ".djvu"]),
        ("markdown", "markdown", [".md", ".markdown"]),
    ]
    lines = [
        f"# {PROVENANCE}",
        f"# hestia .dircolors — ls/eza/tree file colours, {variant} (.dircolors-{{dark,light}}",
        "# pair; the bootstrap symlinks the `theme_variant` one to ~/.dircolors).",
        "#",
        "# The file-TYPE colours come from the SAME per-variant table as vifm's generated",
        "# colorscheme (render.py filetype_colors), so `ls` and vifm agree by construction.",
        "# Indices 16-255 are the standard xterm cube (not the hestia-remapped 0-15).",
        "#",
        '# Loaded by .bashrc: `test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)"`.',
        "",
        "# Terminals colour is enabled for (kitty + the usual 256-colour set + console).",
        "TERM xterm-kitty",
        "TERM xterm-256color",
        "TERM screen-256color",
        "TERM tmux-256color",
        "TERM *-256color",
        "TERM xterm",
        "TERM screen",
        "TERM tmux",
        "TERM linux",
        "",
        "# --- file types (the vifm-shared table) ---",
        "RESET 0",
        "NORMAL 00",
        "FILE 00                         # regular file — plain, like vifm's Normal fg",
        f"DIR {c('dir', bold=True)}                  # vifm Directory",
        f"LINK {c('link')}                    # vifm Link",
        f"ORPHAN {c('broken', bold=True)}              # vifm BrokenLink",
        f"MISSING {c('broken', bold=True)}",
        f"EXEC {c('exec', bold=True)}                # vifm Executable",
        f"MULTIHARDLINK {c('hardlink')}          # vifm HardLink",
        f"SOCK {c('socket')}                    # vifm Socket",
        f"DOOR {c('socket')}",
        f"FIFO {c('fifo')}                    # vifm Fifo",
        f"BLK {c('device')}                     # vifm Device",
        f"CHR {c('device')}",
        "# permission-bit highlights (vifm has no direct analogue — keep them legible)",
        f"SETUID {c('broken', bold=True)}",
        f"SETGID {c('hardlink', bold=True)}",
        f"CAPABILITY {c('broken', bold=True)}",
        f"STICKY {c('dir', bold=True)}",
        f"OTHER_WRITABLE {c('dir')}",
        f"STICKY_OTHER_WRITABLE {c('dir')}",
        "",
        "# --- extension layer (restrained, hestia hues) ------------------------------",
        "# vifm shows regular files in the plain fg, so this is a deliberate enhancement on",
        "# top of the vifm-matched types — delete this block for exact `ls`==vifm parity.",
    ]
    for title, key, suffixes in exts:
        lines.append(f"# {title}")
        lines += [f"{s} {c(key)}" for s in suffixes]
    lines.append("")
    return "\n".join(lines)


GLOW_CHROMA = [
    # (chroma key, syntax role or None, extra style dict)
    ("text", "text", {}),
    ("error", "PAIRED", {}),
    ("comment", "comment", {"italic": True}),
    ("comment_preproc", "preproc", {}),
    ("keyword", "keyword", {}),
    ("keyword_reserved", "keyword", {}),
    ("keyword_namespace", "preproc", {}),
    ("keyword_type", "type", {}),
    ("operator", "keyword", {}),
    ("punctuation", "text", {}),
    ("name", "text", {}),
    ("name_builtin", "identifier", {}),
    ("name_tag", "keyword", {}),
    ("name_attribute", "type", {}),
    ("name_class", "type", {}),
    ("name_constant", "constant", {}),
    ("name_decorator", "preproc", {}),
    ("name_function", "identifier", {}),
    ("literal_number", "constant", {}),
    ("literal_string", "string", {}),
    ("literal_string_escape", "string_special", {}),
    ("generic_deleted", "diff_delete", {}),
    ("generic_emph", None, {"italic": True}),
    ("generic_inserted", "diff_add", {}),
    ("generic_strong", None, {"bold": True}),
    ("generic_subheading", "comment", {}),
]


def render_glow(variant: str) -> str:
    c = VARIANTS[variant]
    r = vroles(variant)
    acc, accfg, link, dim = r["accent"], r["accent_fg"], c["link"], r["dim"]
    # SECTION headings (h2–h6) go cyan (bright_cyan: dark #22cdda / light #087a84, both
    # AA) instead of the violet accent — a full-screen render with all-violet headings
    # is too much purple. The h1 TITLE keeps the violet ACCENT banner (white-on-accent,
    # readable at 5.70:1; white-on-cyan was only 1.94:1) — one violet title over cyan
    # sections reads as hierarchy, not a purple wall. Code/links stay `link` violet.
    head = vansi(variant)["bright_cyan"]
    chroma = {}
    for key, role, style in GLOW_CHROMA:
        entry = {}
        if role == "PAIRED":
            entry = {"color": c["error_fg"], "background_color": c["error_bg"]}
        elif role:
            entry["color"] = c[role]
        for k, v in style.items():
            entry[k] = v
        chroma[key] = entry
    chroma["background"] = {"background_color": r["surface"]}
    doc = {
        "_provenance": PROVENANCE,
        "document": {"block_prefix": "", "block_suffix": "", "color": c["text"], "margin": 2},
        "block_quote": {"color": dim, "indent": 1, "indent_token": "│ "},
        "paragraph": {},
        "list": {"level_indent": 2},
        "heading": {"block_suffix": "\n", "color": head, "bold": True},
        "h1": {"prefix": " ", "suffix": " ", "color": accfg, "background_color": acc, "bold": True},
        "h2": {"prefix": "## ", "color": head, "bold": True},
        "h3": {"prefix": "### ", "color": head, "bold": True},
        "h4": {"prefix": "#### ", "color": head, "bold": True},
        "h5": {"prefix": "##### ", "color": head, "bold": True},
        "h6": {"prefix": "###### ", "color": head},
        "text": {},
        "strikethrough": {"crossed_out": True},
        "emph": {"italic": True},
        "strong": {"bold": True},
        "hr": {"color": acc, "format": "\n────────\n"},
        "item": {"block_prefix": "• "},
        "enumeration": {"block_prefix": ". "},
        "task": {"ticked": "[✓] ", "unticked": "[ ] "},
        "link": {"color": link, "underline": True},
        "link_text": {"color": link, "bold": True},
        "image": {"color": link, "underline": True},
        "image_text": {"color": dim, "format": "Image: {{.text}} →"},
        "code": {"prefix": " ", "suffix": " ", "color": link, "background_color": r["surface"]},
        "code_block": {"color": c["text"], "margin": 2, "chroma": chroma},
        "table": {"center_separator": "┼", "column_separator": "│", "row_separator": "─"},
        "definition_list": {},
        "definition_term": {},
        "definition_description": {"block_prefix": "\n🠶 "},
        "html_block": {},
        "html_span": {},
    }
    return json.dumps(doc, indent=2, ensure_ascii=False) + "\n"


def _ld(light_val: str, dark_val: str) -> str:
    """CSS light-dark(), collapsed when both variants agree. Thunderbird follows
    the portal color-scheme (the sway theme fragment's gsettings exec), so ONE
    file with light-dark() covers both theme_variants — no pair + symlink."""
    if light_val == dark_val:
        return light_val
    return f"light-dark({light_val}, {dark_val})"


def render_thunderbird(kind: str) -> str:
    """userChrome.css / userContent.css — Thunderbird 140 (Supernova) accent.

    The GTK theme only reaches native GTK widgets (context menus, file
    chooser); the main window is Gecko-rendered from THREE separate variable
    chains, all blue by default (traced in omni.ja, 2026-07):
      1. --selected-item-color: var(--sidebar-highlight-background-color,
         AccentColor) in messenger's variables.css — selection, primary
         buttons, focus rings, spaces toolbar all derive from it. AccentColor
         itself ignores the GTK3 theme (widget.gtk.libadwaita-colors, user.js).
      2. hardcoded blues that derive from nothing: --primary (#0a84ff),
         --color-primary-{soft,default,hover,pressed} (account hub),
         --color-text-highlight, --button-link-text-color.
      3. the toolkit design-system token --color-accent-primary
         (tokens-brand.css) — about:preferences never loads messenger's
         variables.css; its checkboxes/radios paint from the CSS accent-color
         property, set from that token.
    userChrome targets * (not :root): unified-toolbar tabs are custom elements
    whose shadow-root stylesheets re-declare vars on :host, beating anything
    inherited from :root — but a user-origin !important declared ON the host
    element (which * matches) wins across the shadow boundary."""
    d, l = ROLES, LIGHT["roles"]
    acc = _ld(l["accent"], d["accent"])            # fill — variant-invariant
    accfg = _ld(l["accent_fg"], d["accent_fg"])
    accdark = _ld(l["accent_dark"], d["accent_dark"])
    link = _ld(l["accent"], d["link"])             # accent-as-TEXT (light has no link role)
    hover = _ld(l["accent_dark"], d["accent"])     # hover ramp: darken on light, lift on dark
    tok_hover = _ld(l["accent_dark"], d["link"])
    soft = _ld(LEXT["heading_bg"], EXT["heading_bg"])  # accent-tinted wash
    if kind == "chrome":
        return f"""/* {PROVENANCE}
   Thunderbird chrome accent (see render_thunderbird's docstring for the three
   variable chains + the shadow-DOM reason the selector is *, not :root).
   Deployed by the dotfiles role into each profile's chrome/ dir; needs
   toolkit.legacyUserProfileCustomizations.stylesheets=true (user.js). */

* {{
  --selected-item-color: {acc} !important;
  --selected-item-text-color: {accfg} !important;
  --sidebar-highlight-background-color: {acc} !important;
  --sidebar-highlight-text-color: {accfg} !important;
  --primary: {acc} !important;
  --tabline-color: {acc} !important;
  --lwt-tab-line-color: {acc} !important;
  --color-primary-default: {link} !important;
  --color-primary-hover: {hover} !important;
  --color-primary-pressed: {accdark} !important;
  --color-primary-soft: {soft} !important;
  --color-text-highlight: {link} !important;
  --button-link-text-color: {link} !important;
  /* toolkit design-system tokens (chrome dialogs) */
  --color-accent-primary: {acc} !important;
  --color-accent-primary-hover: {tok_hover} !important;
  --color-accent-primary-active: {accdark} !important;
}}
"""
    return f"""/* {PROVENANCE}
   Thunderbird content accent — the Settings tab and other about: pages are
   content documents (they load the toolkit tokens, not messenger's
   variables.css); form controls (checkboxes/radios/toggles) paint from the
   CSS accent-color property. Also applies to rendered HTML mail — a form in
   an email gets the accent too (uniform, accepted). */

:root {{
  accent-color: {acc} !important;
  --color-accent-primary: {acc} !important;
  --color-accent-primary-hover: {tok_hover} !important;
  --color-accent-primary-active: {accdark} !important;
  --link-color: {link} !important;
  --link-color-hover: {hover} !important;
  --selected-item-color: {acc} !important;
  --selected-item-text-color: {accfg} !important;
  --color-primary-default: {link} !important;
  --color-primary-hover: {hover} !important;
  --color-primary-pressed: {accdark} !important;
  --color-primary-soft: {soft} !important;
}}
"""


def render_yazi(variant: str) -> str:
    """theme.toml — yazi 26.x ([mgr]/[tabs]/[indicator] key era). Only the keys
    we restyle are emitted — yazi deep-merges the user theme over its embedded
    defaults, so omitted sections ([icon], separators, …) keep upstream values.
    File-type rules mirror filetype_colors(), so yazi agrees with ls + vifm by
    construction; code previews reuse bat's DEPLOYED hestia.tmTheme via
    syntect_theme (the variant symlink, so it follows theme_variant too)."""
    r, a, e = vroles(variant), vansi(variant), vext(variant)
    ft = filetype_colors(variant)
    acc, accfg, accd = r["accent"], r["accent_fg"], r["accent_dark"]
    # the hestia TUI cursor bar — the exact vifm CurrLine / cmus selection pair
    if variant == "dark":
        bar_bg, bar_fg = e["ui_grey"], e["ink"]
    else:
        bar_bg, bar_fg = e["ui_dark"], r["accent_fg"]

    def st(**kw):  # an inline TOML style table: fg/bg hex strings, flag attrs
        parts = []
        for k, v in kw.items():
            parts.append(f'{k} = true' if v is True else f'{k} = "{v}"')
        return "{ " + ", ".join(parts) + " }"

    archive_mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}"
    return f"""# {PROVENANCE}
# yazi theme — hestia {variant} (theme-dark/theme-light pair; the bootstrap
# symlinks the `theme_variant` one to ~/.config/yazi/theme.toml). Partial on
# purpose: yazi merges this over its embedded defaults.

[mgr]
cwd = {st(fg=acc, bold=True)}
find_keyword = {st(fg=e["ink"], bg=a["bright_yellow"], bold=True)}
find_position = {st(fg=a["bright_magenta"], bold=True)}
marker_copied = {st(fg=a["green"], bg=a["green"])}
marker_cut = {st(fg=a["bright_red"], bg=a["bright_red"])}
marker_marked = {st(fg=a["blue"], bg=a["blue"])}
marker_selected = {st(fg=acc, bg=acc)}
count_copied = {st(fg=accfg, bg=a["green"])}
count_cut = {st(fg=e["ink"], bg=a["bright_red"])}
count_selected = {st(fg=accfg, bg=acc)}
border_style = {st(fg=r["border"])}
syntect_theme = "~/.config/bat/themes/hestia.tmTheme"

[indicator]
parent = {st(fg=bar_fg, bg=bar_bg)}
current = {st(fg=bar_fg, bg=bar_bg, bold=True)}

[tabs]
active = {st(fg=accfg, bg=acc, bold=True)}
inactive = {st(fg=r["muted"], bg=r["surface"])}

[mode]
normal_main = {st(fg=accfg, bg=acc, bold=True)}
normal_alt = {st(fg=acc, bg=r["surface"])}
select_main = {st(fg=accfg, bg=a["blue"], bold=True)}
select_alt = {st(fg=a["blue"], bg=r["surface"])}
unset_main = {st(fg=e["ink"], bg=a["bright_yellow"], bold=True)}
unset_alt = {st(fg=a["bright_yellow"], bg=r["surface"])}

[status]
perm_sep = {st(fg=r["dim"])}
perm_type = {st(fg=a["green"])}
perm_read = {st(fg=a["yellow"])}
perm_write = {st(fg=acc)}
perm_exec = {st(fg=a["cyan"])}
progress_label = {st(bold=True)}
progress_normal = {st(fg=acc, bg=r["surface"])}
progress_error = {st(fg=accfg, bg=accd)}

[which]
mask = {st(bg=r["bg"])}
cand = {st(fg=a["bright_cyan"])}
rest = {st(fg=r["dim"])}
desc = {st(fg=e["purple"])}
separator_style = {st(fg=r["dim"])}

[confirm]
border = {st(fg=acc)}
title = {st(fg=acc, bold=True)}
btn_yes = {st(fg=accfg, bg=acc)}

[spot]
border = {st(fg=acc)}
title = {st(fg=acc, bold=True)}
tbl_col = {st(fg=acc)}
tbl_cell = {st(fg=a["bright_yellow"], reversed=True)}

[notify]
title_info = {st(fg=a["green"])}
title_warn = {st(fg=a["bright_yellow"])}
title_error = {st(fg=a["bright_red"])}

[pick]
border = {st(fg=acc)}
active = {st(fg=acc, bold=True)}

[input]
border = {st(fg=acc)}

[cmp]
border = {st(fg=acc)}

[tasks]
border = {st(fg=acc)}
hovered = {st(fg=acc, bold=True)}

[help]
on = {st(fg=a["bright_cyan"])}
run = {st(fg=a["bright_magenta"])}
desc = {st(fg=r["dim"])}
footer = {st(fg=r["bg"], bg=r["muted"])}

# File-type rules — from render.py's shared filetype_colors() table (the same
# one vifm's colorscheme and ~/.dircolors render from, so all three agree).
[filetype]
rules = [
    {st(fg=ft["images"])[:-1]}, mime = "image/*" }},
    {st(fg=ft["video"])[:-1]}, mime = "video/*" }},
    {st(fg=ft["audio"])[:-1]}, mime = "audio/*" }},
    {st(fg=ft["archives"])[:-1]}, mime = "{archive_mime}" }},
    {st(fg=ft["docs"])[:-1]}, mime = "application/{{pdf,doc,rtf}}" }},
    {st(fg=ft["broken"], crossed=True)[:-1]}, url = "*", is = "orphan" }},
    {st(fg=ft["exec"])[:-1]}, url = "*", is = "exec" }},
    {st(fg=accfg, bg=accd)[:-1]}, url = "*", is = "dummy" }},
    {st(fg=accfg, bg=accd)[:-1]}, url = "*/", is = "dummy" }},
    {st(fg=ft["dir"], bold=True)[:-1]}, url = "*/" }},
]
"""


def render_ranger(variant: str) -> str:
    """colorschemes/hestia.py — ranger. The context-check structure follows
    ranger's stock default.py; colours are exact xterm-256 indices resolved
    from the palette (filetype_colors() for the file classes — the same table
    as vifm/dircolors — plus the accent identity in the hostname/tabs/marks/
    progress spots). One class per variant file; the bootstrap symlinks the
    theme_variant one to colorschemes/hestia.py (rc.conf is variant-blind)."""
    r, a, e = vroles(variant), vansi(variant), vext(variant)
    ft = filetype_colors(variant)
    x = xterm_index
    # the hestia TUI cursor-bar fill (vifm CurrLine / the yazi indicator pair):
    # with curses `reverse`, setting fg paints the BAR, text becomes the ground
    bar = e["ui_grey"] if variant == "dark" else e["ui_dark"]
    consts = "\n".join(
        f"{name} = {x(val)}"
        for name, val in [
            ("ACCENT", r["accent"]), ("ACCENT_DARK", r["accent_dark"]),
            ("DIM", r["dim"]), ("MUTED", r["muted"]), ("BORDER", e["line_grey"]),
            ("DIR", ft["dir"]), ("EXEC", ft["exec"]), ("LINK", ft["link"]),
            ("BROKEN", ft["broken"]), ("FIFO", ft["fifo"]), ("DEVICE", ft["device"]),
            ("SOCKET", ft["socket"]), ("IMAGES", ft["images"]), ("VIDEO", ft["video"]),
            ("AUDIO", ft["audio"]), ("DOCS", ft["docs"]), ("ARCHIVES", ft["archives"]),
            ("MARKED", a["bright_yellow"]), ("GREEN", a["green"]),
            ("CYAN", a["cyan"]), ("MAGENTA", a["bright_magenta"]),
            ("BRIGHT_RED", a["bright_red"]), ("YELLOW", a["yellow"]),
            ("BAR", bar),
        ]
    )
    return f'''# {PROVENANCE}
# ranger colorscheme — hestia {variant} (hestia-dark/-light pair; the
# bootstrap symlinks the `theme_variant` one to colorschemes/hestia.py).
# Structure follows ranger's stock default.py; colours are xterm-256 indices
# resolved from palette.yml — the file classes from the SAME filetype_colors()
# table as vifm + dircolors, so all of them agree by construction.

from __future__ import absolute_import, division, print_function

from ranger.gui.color import bold, default, default_colors, normal, reverse
from ranger.gui.colorscheme import ColorScheme

{consts}


class Hestia(ColorScheme):
    progress_bar_color = ACCENT

    def use(self, context):  # noqa: C901  pylint: disable=too-many-branches,too-many-statements
        fg, bg, attr = default_colors

        if context.reset:
            return default_colors

        elif context.in_browser:
            attr = reverse if context.selected else normal
            if context.empty or context.error:
                fg, bg = {x(r["accent_fg"])}, ACCENT_DARK
            if context.border:
                fg = BORDER
            if context.media:
                fg = IMAGES if context.image else (AUDIO if context.audio else VIDEO)
            if context.document:
                fg = DOCS
            if context.container:
                fg = ARCHIVES
            if context.directory:
                attr |= bold
                fg = DIR
            elif context.executable and not any(
                    (context.media, context.container, context.fifo, context.socket)):
                attr |= bold
                fg = EXEC
            if context.socket:
                attr |= bold
                fg = SOCKET
            if context.fifo:
                fg = FIFO
            if context.device:
                attr |= bold
                fg = DEVICE
            if context.link:
                fg = LINK if context.good else BROKEN
            if context.tag_marker and not context.selected:
                attr |= bold
                fg = ACCENT
            if not context.selected and (context.cut or context.copied):
                attr |= bold
                fg = DIM
            if context.main_column:
                if context.selected:
                    attr |= bold
                if context.marked:
                    attr |= bold
                    fg = MARKED
            if context.badinfo:
                if attr & reverse:
                    bg = MAGENTA
                else:
                    fg = MAGENTA
            if context.selected:
                # the uniform hestia cursor bar (vifm CurrLine / yazi indicator)
                # instead of reverse-video over the item's own colour
                fg = BAR
            if context.inactive_pane:
                fg = MUTED

        elif context.in_titlebar:
            if context.hostname:
                fg = BRIGHT_RED if context.bad else ACCENT
            elif context.directory:
                fg = DIR
            elif context.tab:
                if context.good:
                    fg, bg = {x(r["accent_fg"])}, ACCENT
            elif context.link:
                fg = LINK
            attr |= bold

        elif context.in_statusbar:
            if context.permissions:
                fg = CYAN if context.good else BRIGHT_RED
            if context.marked:
                attr |= bold | reverse
                fg = MARKED
            if context.frozen:
                attr |= bold | reverse
                fg = CYAN
            if context.message:
                if context.bad:
                    attr |= bold
                    fg = BRIGHT_RED
            if context.loaded:
                bg = self.progress_bar_color
            if context.vcsinfo:
                fg = DIR
                attr &= ~bold
            if context.vcscommit:
                fg = YELLOW
                attr &= ~bold
            if context.vcsdate:
                fg = CYAN
                attr &= ~bold

        if context.text and context.highlight:
            attr |= reverse

        if context.in_taskview:
            if context.title:
                fg = DIR
            if context.selected:
                attr |= reverse
            if context.loaded:
                if context.selected:
                    fg = self.progress_bar_color
                else:
                    bg = self.progress_bar_color

        if context.vcsfile and not context.selected:
            attr &= ~bold
            if context.vcsconflict:
                fg = MAGENTA
            elif context.vcsuntracked:
                fg = ACCENT
            elif context.vcschanged:
                fg = ACCENT
            elif context.vcsunknown:
                fg = BRIGHT_RED
            elif context.vcsstaged:
                fg = GREEN
            elif context.vcssync:
                fg = GREEN
            elif context.vcsignored:
                fg = default
        elif context.vcsremote and not context.selected:
            attr &= ~bold
            if context.vcssync or context.vcsnone:
                fg = GREEN
            elif context.vcsbehind:
                fg = BRIGHT_RED
            elif context.vcsahead:
                fg = DIR
            elif context.vcsdiverged:
                fg = MAGENTA
            elif context.vcsunknown:
                fg = BRIGHT_RED

        return fg, bg, attr
'''


# --------------------------------------------------- vim / neovim colorscheme

# <256-colour degradation: attribute-only, palette-independent (emitted verbatim
# after the truecolor + 256-colour blocks so a low-colour terminal still gets
# sane reverse/bold/underline structure).
VIM_TERM_TAIL = """
if s:t_Co >= 0
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=reverse
  hi CursorColumn term=NONE
  hi CursorLine term=underline
  hi CursorLineNr term=bold
  hi DiffAdd term=reverse
  hi DiffChange term=NONE
  hi DiffDelete term=reverse
  hi DiffText term=reverse
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,reverse
  hi FoldColumn term=NONE
  hi Folded term=NONE
  hi IncSearch term=bold,reverse,underline
  hi LineNr term=NONE
  hi MatchParen term=bold,underline
  hi ModeMsg term=bold
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=reverse
  hi PmenuSel term=bold
  hi PmenuThumb term=NONE
  hi Question term=standout
  hi Search term=reverse
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=underline
  hi SpellCap term=underline
  hi SpellLocal term=underline
  hi SpellRare term=underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=bold,underline
  hi TabLine term=bold,underline
  hi TabLineFill term=NONE
  hi Terminal term=NONE
  hi TabLineSel term=bold,reverse
  hi Title term=NONE
  hi VertSplit term=NONE
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=bold
  hi Constant term=NONE
  hi Error term=bold,reverse
  hi Identifier term=NONE
  hi Ignore term=NONE
  hi PreProc term=NONE
  hi Special term=NONE
  hi Statement term=NONE
  hi Todo term=bold,reverse
  hi Type term=NONE
  hi Underlined term=underline
  unlet s:t_Co
  finish
endif
""".rstrip("\n")

# structural links (variant/t_Co-independent)
VIM_LINKS = [
    ("Terminal", "Normal"), ("StatuslineTerm", "Statusline"),
    ("StatuslineTermNC", "StatuslineNC"), ("LineNrAbove", "LineNr"),
    ("LineNrBelow", "LineNr"), ("MessageWindow", "Pmenu"),
    ("PopupNotification", "Todo"), ("PopupSelected", "PmenuSel"),
    ("CurSearch", "IncSearch"),
]

# Treesitter capture groups -> standard groups, for PARITY with Vim's regex
# syntax (phase A). Neovim highlights via these finer-grained @* captures and
# its defaults OVER-colour vs Vim — builtins/constructors -> Special (purple),
# punctuation -> Delimiter, operators -> Operator (blue). We relink them to the
# coarse groups Vim actually uses so nvim == vim; the things Vim leaves plain
# (symbolic operators, punctuation, plain/member variables, module names, call
# sites) link to Normal. Harmless in Vim (the @* groups just go unused).
# Phase B (gradual, stack-wide) adds tasteful DETAIL on top of parity: the
# *.builtin / variable.parameter captures link to the hestiaBuiltin*/hestiaParam
# intermediate groups (coarse role colour + ITALIC), mirrored in scopes.yml so
# bat/Shiki/VSCode agree by role. More distinctions land here over time.
VIM_TS_LINKS = [
    # comments
    ("@comment", "Comment"), ("@comment.documentation", "Comment"),
    ("@comment.todo", "Todo"), ("@comment.note", "Todo"),
    ("@comment.warning", "Todo"), ("@comment.error", "Error"),
    # literals / constants — builtins to their natural group, NOT Special
    ("@constant", "Constant"), ("@constant.builtin", "hestiaBuiltinConst"),
    ("@constant.macro", "PreProc"), ("@number", "Constant"),
    ("@number.float", "Constant"), ("@boolean", "hestiaBuiltinConst"),
    ("@character", "Constant"), ("@character.special", "Special"),
    # strings — escapes/regex special (Vim colours these too)
    ("@string", "String"), ("@string.documentation", "String"),
    ("@string.escape", "Special"), ("@string.regexp", "Special"),
    ("@string.special", "Special"), ("@string.special.symbol", "Constant"),
    ("@string.special.url", "Underlined"), ("@string.special.path", "Underlined"),
    # keywords / statements — all blue, like Vim (sub-captures fall back here)
    ("@keyword", "Statement"), ("@conditional", "Statement"),
    ("@repeat", "Statement"), ("@label", "Statement"),
    ("@exception", "Statement"),
    # imports/includes -> cyan (PreProc), like bat/Shiki keyword.control.import
    ("@include", "PreProc"), ("@keyword.import", "PreProc"),
    ("@type.qualifier", "Statement"),
    # symbolic operators -> blue (unify with bat/Shiki keyword.operator);
    # punctuation stays plain
    ("@operator", "Statement"), ("@punctuation", "Normal"),
    ("@punctuation.delimiter", "Normal"), ("@punctuation.bracket", "Normal"),
    ("@punctuation.special", "Special"),
    # functions — def name + builtins coloured; plain call sites plain (Vim)
    ("@function", "Function"), ("@function.builtin", "hestiaBuiltinFunc"),
    # call sites coloured like definitions (magenta) — the TextMate grammars do
    # this for every language (entity.name.function), so nvim matches
    ("@function.call", "Function"), ("@function.method", "Function"),
    ("@function.method.call", "Function"), ("@function.macro", "PreProc"),
    ("@constructor", "Function"),
    # types — yellow, builtins included
    ("@type", "Type"), ("@type.builtin", "hestiaBuiltinType"), ("@type.definition", "Type"),
    ("@attribute", "PreProc"), ("@attribute.builtin", "PreProc"),
    # variables / members / modules — Vim leaves these Normal
    ("@variable", "Normal"), ("@variable.builtin", "hestiaSelf"),
    ("@variable.parameter", "hestiaParam"), ("@variable.member", "Normal"),
    ("@property", "Normal"), ("@field", "Normal"),
    ("@module", "Normal"), ("@module.builtin", "Normal"), ("@namespace", "Normal"),
    # markup / tags (html, markdown)
    ("@tag", "Statement"), ("@tag.attribute", "Type"), ("@tag.delimiter", "Normal"),
    ("@markup.link.url", "Underlined"), ("@markup.raw", "String"),
    # LSP semantic tokens chain to @* by nvim default; pin the ones that don't
    ("@lsp.type.namespace", "Normal"), ("@lsp.type.variable", "Normal"),
    ("@lsp.type.property", "Normal"), ("@lsp.type.parameter", "Normal"),
]

# Neovim's :terminal reads g:terminal_color_0..15; Vim reads g:terminal_ansi_colors.
VIM_ANSI = {
    "dark": "['#000000', '#d7005f', '#00af5f', '#d78700', '#0087d7', '#d787d7', '#00afaf', '#d0d0d0', '#767676', '#ff5f87', '#00d75f', '#ffaf00', '#00afff', '#ff87ff', '#00d7d7', '#ffffff']",
    "light": "['#000000', '#af0000', '#008700', '#af5f00', '#005faf', '#870087', '#008787', '#8a8a8a', '#808080', '#d70000', '#5faf5f', '#d78700', '#0087d7', '#af00af', '#00afaf', '#ffffff']",
}


def _vim_rows(variant: str) -> list:
    """(group, guifg, guibg, gui_attr[, guisp]) for one variant. Colours resolve
    from palette roles: dark reproduces wildcharm (the palette derives from it)
    save the documented comment/purple/diff-delete deviations; light lands on the
    palette's AA-tuned values. The vimdiff fills come from the palette `diff:`
    section (Claude-style: tinted row bg, guifg=NONE so syntax shows through).
    Only three vim-only UI accents with no cross-app role stay literal here —
    Visual/lCursor/MatchParen."""
    r, a, e = vroles(variant), vansi(variant), vext(variant)
    s = PALETTE["syntax"] if variant == "dark" else LIGHT["syntax"]
    df = PALETTE["diff"] if variant == "dark" else LIGHT["diff"]
    dark = variant == "dark"
    N = "NONE"
    ln, ink, white = e["line_grey"], e["ink"], a["bright_white"]
    # text ON a saturated/dark fill: black on the bright dark-variant fills,
    # white on the AA-darkened light-variant fills.
    fill_fg = ink if dark else white
    if dark:
        tab_bg, tabsel_bg = a["bright_black"], e["ui_grey"]
        tool_bg = a["white"]
        pmenu_bg, pmenu_fg, pmsel_bg = r["surface_alt"], a["white"], e["line_grey"]
        line_hi, colcol = r["surface"], r["surface_alt"]
        cur_bg, pthumb = white, a["white"]
        eob, curnr = a["bright_black"], white
        vis, lcur, mparen = "#5fd7ff", "#ff5fff", "#ff00af"
        stl = (r["accent_fg"], r["accent"], "bold")       # white on the violet accent (matches waybar/swaynag)
        stlnc = (a["bright_black"], r["bg"], "reverse")
        split = a["bright_black"]
        moremsg, question, warnmsg = a["bright_green"], a["bright_magenta"], a["bright_yellow"]
        # nvim diagnostics — err on link (bright_red, AA) not the accent fill
        diag = (r["link"], a["bright_yellow"], a["bright_blue"], a["bright_cyan"], a["bright_green"])
    else:
        tab_bg, tabsel_bg = r["surface_alt"], e["ui_dark"]
        tool_bg = e["ui_dark"]
        pmenu_bg, pmenu_fg, pmsel_bg = r["surface"], ink, r["surface_alt"]
        line_hi, colcol = r["surface"], r["surface"]
        cur_bg, pthumb = ink, a["bright_black"]
        eob, curnr = ln, ink
        vis, lcur, mparen = "#0087d7", "#ff00ff", "#ff00af"
        stl = (r["accent_fg"], r["accent"], "bold")       # white on the violet accent (matches waybar/swaynag)
        stlnc = (ink, r["surface_alt"], N)                # inactive: light-grey bar
        split = e["ui_dark"]
        moremsg, question, warnmsg = a["green"], a["magenta"], a["yellow"]
        diag = (s["error"], a["yellow"], a["blue"], a["cyan"], a["green"])
    return [
        ("Normal", r["text"], r["bg"], N),
        ("Statusline", stl[0], stl[1], stl[2]),
        ("StatuslineNC", stlnc[0], stlnc[1], stlnc[2]),
        ("VertSplit", split, N, N),
        ("TabLine", ink, tab_bg, N),
        ("TabLineFill", N, r["bg"], N),
        ("TabLineSel", fill_fg, tabsel_bg, "bold"),
        ("ToolbarLine", N, N, N),
        ("ToolbarButton", fill_fg, tool_bg, N),
        ("QuickFixLine", fill_fg, s["identifier"], N),
        ("CursorLineNr", curnr, N, "bold"),
        ("LineNr", ln, N, N),
        ("NonText", ln, N, N),
        ("FoldColumn", ln, N, N),
        ("SpecialKey", ln, N, N),
        ("EndOfBuffer", eob, N, N),
        ("Pmenu", pmenu_fg, pmenu_bg, N),
        ("PmenuSel", pmenu_fg, pmsel_bg, N),
        ("PmenuThumb", N, pthumb, N),
        ("PmenuSbar", N, N, N),
        ("PmenuKind", r["link"] if dark else s["diff_delete"], pmenu_bg, N),
        ("PmenuKindSel", r["link"] if dark else s["diff_delete"], pmsel_bg, N),
        ("PmenuExtra", a["bright_black"], pmenu_bg, N),
        ("PmenuExtraSel", a["bright_black"], pmsel_bg, N),
        ("PmenuMatch", a["magenta"] if dark else s["identifier"], pmenu_bg, N),
        ("PmenuMatchSel", a["magenta"] if dark else s["identifier"], pmsel_bg, N),
        ("SignColumn", N, N, N),
        ("Error", s["error"], white, "reverse"),
        ("ErrorMsg", s["error"], white, "reverse"),
        ("ModeMsg", N, N, "bold"),
        ("MoreMsg", moremsg, N, N),
        ("Question", question, N, N),
        ("WarningMsg", warnmsg, N, N),
        ("Todo", s["todo"], r["bg"], "reverse"),
        ("Search", fill_fg, s["string"], N),
        ("IncSearch", fill_fg, s["type"], N),
        ("WildMenu", fill_fg, s["type"], N),
        ("debugPC", s["diff_change"], N, "reverse"),
        ("debugBreakpoint", a["cyan"], N, "reverse"),
        ("Cursor", fill_fg, cur_bg, N),
        ("lCursor", ink, lcur, N),
        ("Visual", vis, fill_fg, "reverse"),
        ("VisualNOS", fill_fg, s["keyword"], N),
        ("CursorLine", N, line_hi, N),
        ("CursorColumn", N, line_hi, N),
        ("Folded", a["bright_black"], pmenu_bg, N),
        ("ColorColumn", N, colcol, N),
        ("MatchParen", mparen, N, "bold"),
        ("SpellBad", N, N, "undercurl", s["constant"]),
        ("SpellCap", N, N, "undercurl", a["cyan"]),
        ("SpellLocal", N, N, "undercurl", a["green"]),
        ("SpellRare", N, N, "undercurl", a["bright_magenta"]),
        ("Comment", s["comment"], N, "italic"),
        ("Constant", s["constant"], N, N),
        ("String", s["string"], N, N),
        ("Identifier", s["identifier"], N, N),
        ("Statement", s["keyword"], N, N),
        ("Type", s["type"], N, N),
        ("PreProc", s["preproc"], N, N),
        ("Special", s["special"], N, N),
        ("Underlined", N, N, "underline"),
        ("Title", N, N, "bold"),
        ("Directory", s["keyword"], N, "bold"),
        ("Conceal", ln, N, N),
        ("Ignore", N, N, N),
        ("DiffAdd", N, df["add_bg"], N),
        ("DiffChange", N, df["change_bg"], N),
        ("DiffText", N, df["text_bg"], "bold"),
        ("DiffDelete", df["delete_fg"], df["delete_bg"], N),
        ("Added", s["diff_add"], N, N),
        ("Changed", s["diff_change"], N, N),
        ("Removed", s["diff_delete"], N, N),
        # nvim diagnostics (harmless in Vim; the underlines carry the colour as
        # guisp, the sign/virtual-text variants chain to these by nvim default)
        ("DiagnosticError", diag[0], N, N),
        ("DiagnosticWarn", diag[1], N, N),
        ("DiagnosticInfo", diag[2], N, N),
        ("DiagnosticHint", diag[3], N, N),
        ("DiagnosticOk", diag[4], N, N),
        ("DiagnosticUnderlineError", N, N, "undercurl", diag[0]),
        ("DiagnosticUnderlineWarn", N, N, "undercurl", diag[1]),
        ("DiagnosticUnderlineInfo", N, N, "undercurl", diag[2]),
        ("DiagnosticUnderlineHint", N, N, "undercurl", diag[3]),
        # phase-B syntax detail — intermediate groups the treesitter captures
        # link to (plain names, so Vim defines-but-ignores them; nvim links its
        # @* captures to them inside the has('nvim') guard). The COLOUR is the
        # coarse role; the DISTINCTION is font-style (italic), so no new hues.
        ("hestiaBuiltinFunc", s["identifier"], N, "italic"),
        ("hestiaBuiltinConst", s["constant"], N, "italic"),
        ("hestiaBuiltinType", s["type"], N, "italic"),
        ("hestiaParam", r["text"], N, "italic"),
        ("hestiaSelf", s["constant"], N, "italic"),  # self/this/cls — pink italic
    ]


def render_vim() -> str:
    """The hestia Vim/Neovim colorscheme — one file, both `&background` branches,
    truecolor + 256-colour, from palette.yml. Symlinked (not include'd), so it is
    the sole render.py target that is a single file rather than a dark/light pair."""
    def guiline(row):
        g, fg, bg, attr = row[0], row[1], row[2], row[3]
        parts = [f"hi {g}", f"guifg={fg}", f"guibg={bg}"]
        if len(row) == 5:                       # spell groups carry guisp
            parts.append(f"guisp={row[4]}")
        parts += [f"gui={attr}", f"cterm={attr}"]
        return "  " + " ".join(parts)

    def ctermline(row):
        g, fg, bg, attr = row[0], row[1], row[2], row[3]
        cf = "NONE" if fg == "NONE" else str(xterm_index(fg))
        cb = "NONE" if bg == "NONE" else str(xterm_index(bg))
        return f"    hi {g} ctermfg={cf} ctermbg={cb} cterm={attr}"

    def ansi_loop():
        return ("    if has('nvim')\n"
                "      for s:i in range(len(g:terminal_ansi_colors)) | "
                "let g:terminal_color_{s:i} = g:terminal_ansi_colors[s:i] | endfor\n"
                "    endif")

    L = [
        f'" {PROVENANCE}',
        '" hestia.vim — hestia\'s editor colorscheme (Vim + Neovim). Inspired by the',
        '" wildcharm scheme (Maxim Kim); hestia owns it now — the palette was derived',
        '" from wildcharm, so the look is unchanged save hestia\'s documented deviations',
        '" (comment/purple/diff-delete on the dark syntax roles; the AA-tuned light',
        '" values). Vim and Neovim render identically. Edit palette.yml + re-render.',
        "",
        "hi clear",
        "if has('nvim')",
        "  \" match Vim's default group baseline so unset groups agree across editors",
        "  silent! source $VIMRUNTIME/colors/vim.lua",
        "endif",
        "let g:colors_name = 'hestia'",
        "",
        "let s:t_Co = has('gui_running') ? -1 : (&t_Co ?? 0)",
        "",
    ]
    L += [f"hi! link {x} {y}" for x, y in VIM_LINKS]
    L.append("")
    L.append('" treesitter / LSP captures -> standard groups (nvim parity with Vim).')
    L.append('" Nvim-ONLY: Vim has no treesitter, and older Vim patchlevels reject the')
    L.append('" @ in these group names (W18) — so guard the whole block on has(\'nvim\').')
    L.append("if has('nvim')")
    L += [f"  hi! link {x} {y}" for x, y in VIM_TS_LINKS]
    L.append("endif")
    L.append("")
    # truecolor (gui) — always evaluated; harmless when a cterm block also runs
    for i, v in enumerate(("dark", "light")):
        L.append("if &background ==# 'dark'" if i == 0 else "else")
        L.append("  if (has('termguicolors') && &termguicolors) || has('gui_running')")
        L.append(f"    let g:terminal_ansi_colors = {VIM_ANSI[v]}")
        L.append(ansi_loop())
        L.append("  endif")
        L += [guiline(row) for row in _vim_rows(v)]
    L.append("endif")
    L.append("")
    # 256-colour cterm indices (nearest xterm-256), then stop
    L.append("if s:t_Co >= 256")
    for i, v in enumerate(("dark", "light")):
        L.append("  if &background ==# 'dark'" if i == 0 else "  else")
        L += [ctermline(row) for row in _vim_rows(v)]
    L.append("  endif")
    L.append("  unlet s:t_Co")
    L.append("  finish")
    L.append("endif")
    L.append(VIM_TERM_TAIL)
    L.append("")
    L.append('" vim: et ts=8 sw=2 sts=2')
    return "\n".join(L) + "\n"


def render_vscode_pkg() -> str:
    """Keep the VS Code extension version in lock-step with the palette version.
    The vscode_theme role is idempotent on THIS version (code --install-extension
    no-ops at an equal version), and it used to silently drift because nothing
    bumped it — so theme changes never reached VS Code. render.py owns it now: a
    palette bump rolls the extension out. Only the value changes; the rest of
    package.json is preserved verbatim. (Corollary: any change to a generated
    artifact must bump the palette version — patch minimum — or VS Code, and
    other version-gated deploys, won't see it.)"""
    import re
    text = (REPO / "user/vscode/hestia/package.json").read_text()
    return re.sub(r'("version":\s*")[^"]*(")', rf"\g<1>{VERSION}\g<2>", text, count=1)


OUTPUTS = {
    REPO / "user/vscode/hestia/package.json": lambda: render_vscode_pkg(),
    REPO / "user/bat/themes/hestia-dark.tmTheme": lambda: render_tmtheme("dark"),
    REPO / "user/bat/themes/hestia-light.tmTheme": lambda: render_tmtheme("light"),
    HERE / "dist/shiki/hestia-dark.json": lambda: theme_json("dark", "shiki"),
    HERE / "dist/shiki/hestia-light.json": lambda: theme_json("light", "shiki"),
    REPO / "user/vscode/hestia/themes/hestia-dark-color-theme.json": lambda: theme_json("dark", "vscode"),
    REPO / "user/vscode/hestia/themes/hestia-light-color-theme.json": lambda: theme_json("light", "vscode"),
    REPO / "user/kitty/theme-dark.conf": lambda: render_kitty("dark"),
    REPO / "user/kitty/theme-light.conf": lambda: render_kitty("light"),
    REPO / "user/sway/theme-dark.conf": lambda: render_sway("dark"),
    REPO / "user/sway/theme-light.conf": lambda: render_sway("light"),
    REPO / "user/waybar/theme-dark.css": lambda: render_waybar_css("dark"),
    REPO / "user/waybar/theme-light.css": lambda: render_waybar_css("light"),
    REPO / "user/mako/theme-dark.conf": lambda: render_mako("dark"),
    REPO / "user/mako/theme-light.conf": lambda: render_mako("light"),
    REPO / "user/wofi/colors-dark": lambda: render_wofi_colors("dark"),
    REPO / "user/wofi/colors-light": lambda: render_wofi_colors("light"),
    REPO / "user/swaylock/config-dark": lambda: render_swaylock("dark"),
    REPO / "user/swaylock/config-light": lambda: render_swaylock("light"),
    REPO / "user/swaynag/config-dark": lambda: render_swaynag("dark"),
    REPO / "user/swaynag/config-light": lambda: render_swaynag("light"),
    REPO / "user/zathura/theme-dark": lambda: render_zathura("dark"),
    REPO / "user/zathura/theme-light": lambda: render_zathura("light"),
    REPO / "user/vifm/colors/hestia-dark.vifm": lambda: render_vifm("dark"),
    REPO / "user/vifm/colors/hestia-light.vifm": lambda: render_vifm("light"),
    REPO / "user/bash/.dircolors-dark": lambda: render_dircolors("dark"),
    REPO / "user/bash/.dircolors-light": lambda: render_dircolors("light"),
    REPO / "user/glow/hestia-dark.json": lambda: render_glow("dark"),
    REPO / "user/glow/hestia-light.json": lambda: render_glow("light"),
    # single light-dark() files, not pairs — TB follows the portal color-scheme
    REPO / "user/thunderbird/userChrome.css": lambda: render_thunderbird("chrome"),
    REPO / "user/thunderbird/userContent.css": lambda: render_thunderbird("content"),
    REPO / "user/yazi/theme-dark.toml": lambda: render_yazi("dark"),
    REPO / "user/yazi/theme-light.toml": lambda: render_yazi("light"),
    REPO / "user/ranger/colorschemes/hestia-dark.py": lambda: render_ranger("dark"),
    REPO / "user/ranger/colorschemes/hestia-light.py": lambda: render_ranger("light"),
    REPO / "user/vim/colors/hestia.vim": lambda: render_vim(),
}


def main() -> None:
    aa_gate()
    check = "--check" in sys.argv
    drift = []
    for path, renderer in OUTPUTS.items():
        content = renderer()
        rel = path.relative_to(REPO)
        if check:
            if not path.exists() or path.read_text() != content:
                drift.append(str(rel))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
            print(f"rendered {rel}")
    if check:
        if drift:
            sys.exit("STALE (re-run render.py):\n  " + "\n  ".join(drift))
        print(f"check ok — all {len(OUTPUTS)} artifacts match palette v{VERSION}")


if __name__ == "__main__":
    main()
